### ISSUE TITLE
Severe memory leak on mixer 0.2.7 when driving load

### ISSUE THREAD

**Issue by jnativio** [istio/issues#100]
**Is this a BUG or FEATURE REQUEST?: BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version  0.2.7
kubectl version  
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.4-1+1540c973d4ff9d", GitCommit:"1540c973d4ff9da2d6a204a7709084488a459ed4", GitTreeState:"clean", BuildDate:"2017-10-06T15:08:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
No. Used istio.yaml

**What happened**:
I installed Istio on IBM Container Service (Armada) cluster with 3 worker nodes. All Istio pods in one of the nodes. I monitor the CPU and memory usage of nodes and pods while driving load to a microservices app benchmark. In the example below the load ran for about 40 min, and since the beginning the memory usage by the mixer kept growing. If the load continues, the node runs out of memory and kubernetes would restart all pods running there. After stopping the load, the memory usage goes down very slowly, and the CPU usage by the mixer pod is still very high.

![image](https://user-images.githubusercontent.com/18554027/31780725-8f10808c-b4c4-11e7-8e0d-69a8ea1ac5f7.png)

![image](https://user-images.githubusercontent.com/18554027/31780903-09fb3512-b4c5-11e7-9002-345a8983b588.png)

**What you expected to happen:**

**How to reproduce it:**
Drive continuous load to microservices using Istio 0.2.7 and mixer enabled. 

**Feature Request:**
N

**Describe the feature:**

**Comment by mandarjog** [comment]
Thanks @jnativio 
How long did you leave it running? You mentioned that memory goes down slowly once load stops, does it go back all the way to pre-run state?

**Comment by mandarjog** [comment]
Potentially related to https://github.com/istio/mixer/issues/1369
However the expected behaviour in the IL memory leak case is that memory usage will not go down as the load stops in absence of config changes.

**Comment by jnativio** [comment]
The chart below shows throughput and number of jmeter clients for the previous mixer memory/cpu  charts, to answer the questions about of time and tps:
![image](https://user-images.githubusercontent.com/18554027/31786778-998480dc-b4d7-11e7-9270-b1f6f280e77a.png)

**Comment by jnativio** [comment]
I don't have any data at goroutines level. It appears mixer does not go back all the way to the same memory usage as when it first starts but stabilize at some higher value. The chart below shows its memory after 2 short runs:
![image](https://user-images.githubusercontent.com/18554027/31787111-a33ae35e-b4d8-11e7-9cf1-2410427c1473.png)

**Comment by mandarjog** [comment]
@jnativio Can you get a heap dump for us.
port forward to mixer port 9093
and run

 `curl localhost:9093/debug/pprof/heap?debug=1`
Thanks,
- Mandar

**Comment by jnativio** [comment]
@mandarjog I got two heap dumps: one before any load (freshly installed) and another after some load.

[hd_before_load.txt](https://github.com/istio/issues/files/1407849/hd_before_load.txt)
[hd_after_load.txt](https://github.com/istio/issues/files/1407852/hd_after_load.txt)

**Comment by mandarjog** [comment]
Thanks @jnativio

**Comment by mandarjog** [comment]
So far I am seeing a lot of allocations via opentracing/zipkin. Mixer does not sample traces, it is producing trace info for every request, so that needs to be addressed.
I would like to do a simple repro.

**Comment by jnativio** [comment]
I took more heapdumps as requested by Mandar. The load was 60 jmeter clients during 5 minutes, with an average TPS of 272. The approximate times when the heap dumps were obtained are indicated in the chart below.
![image](https://user-images.githubusercontent.com/18554027/31957966-5691dea6-b8be-11e7-827e-3f6ebb3a9804.png)

[1_hd_initial.txt](https://github.com/istio/issues/files/1411796/1_hd_initial.txt)
[2_hd_after2min_load.txt](https://github.com/istio/issues/files/1411797/2_hd_after2min_load.txt)
[3_hd_after5min_load.txt](https://github.com/istio/issues/files/1411798/3_hd_after5min_load.txt)
[4_hd_after60min_noload.txt](https://github.com/istio/issues/files/1411794/4_hd_after60min_noload.txt)
[5_hd_after90min_noload.txt](https://github.com/istio/issues/files/1411795/5_hd_after90min_noload.txt)

**Comment by mandarjog** [comment]
Thanks @jnativio, that is awesome !

**Comment by mandarjog** [comment]
@jnativio Is this still 0.2.7 or 0.2.9 now ?

**Comment by jnativio** [comment]
@mandarjog 0.2.9. Sorry, I forgot to mention.

**Comment by jnativio** [comment]
One more heap dump and a go thread dump:
[td_resting.txt](https://github.com/istio/issues/files/1412059/td_resting.txt)
[hd_resting.txt](https://github.com/istio/issues/files/1412060/hd_resting.txt)

**Comment by jnativio** [comment]
New batch of dumps (load: 10 clients, 5min):

[dumps_1025.zip](https://github.com/istio/issues/files/1415815/dumps_1025.zip)

**Comment by mandarjog** [comment]
Thanks @jnativio.
As I said in a previous comment the issue is twofold
 * We tracing each and every request
 * zipkin library creates 1 go-routine per request to handle trace data, and has no notion of back pressure. 

To verify this is the case, please do the following.
Remove `--traceOutput=http://zipkin:9411/api/v1/spans` from the deployment spec of mixer.

Do do this in the running system do the following.
`kubectl edit deployments/istio-mixer -n istio-system`
search for `zipkin` and remove that entire line and save.

Thanks.

**Comment by mandarjog** [comment]
Some details about the actual mechanisms of memory leaks.
1. Go runtime permanently allocates goroutine structures equal to the high watermark of number of concurrent goroutines in the system.
2. There were 93k go routines related open tracing in one of the goroutine dumps.
    This high water mark can continue to grow, so usage never returns to baseline.

```
  93381 created by github.com/openzipkin/zipkin-go-opentracing.(*HTTPCollector).loop
   2050 created by istio.io/mixer/pkg/pool.(*GoroutinePool).AddWorkers
     72 created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
     40 created by google.golang.org/grpc/transport.newHTTP2Server
     20 created by google.golang.org/grpc.(*Server).Serve
     18 created by k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
     18 created by k8s.io/client-go/tools/cache.(*controller).Run
     17 created by istio.io/mixer/pkg/config/crd.(*Store).checkAndCreateCaches
     13 created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
```

3. Under load, unsampled traces pile up individually in goroutines, and without any backpressure these goroutines hold onto a lot of memory while the load continues. This is why you see continually increasing memory usage. When load goes away, the trace goroutines finish their work and return most of the memory .

**Comment by jmuk** [comment]
It is very likely to be HTTPCollector as Mandar suggested -- it creates a goroutine per send of traces. To be fair, it batches the traces, but maybe it does not expect that many number of requests.

As I tried locally, mixer with `--traceOutput=STDERR` (or `STDOUT`) will prevent this happening -- i.e., printing the trace data instead of sending traces to the actual zipkin. Of course this means the trace data will never be recorded.

**Comment by jnativio** [comment]
I confirmed that after removing the requests tracing the memory used by the mixer did not grow with load.

**Comment by jmuk** [comment]
@jnativio can you try out `gcr.io/istio-testing/mixer:e495f82c92542d8d8e48701f19a77401f916e0bc` for mixer's image on your environment?

We merged a fix which we believe resolves this issue, so I want you to make sure that's true on your environment. This image includes the fix we merged.

**Comment by jnativio** [comment]
@jmuk Sorry for the delay, but I have tested this image and the fix seems to be working fine. I have not observed any memory growth with load and the general performance also improved.

**Comment by jmuk** [comment]
Great news!  Meanwhile, the fix was also merged into 0.2 branch, I think the next release will come with the fix. Stay tuned.

**Comment by ldemailly** [comment]
awesome, so we can close this ?

**Comment by jnativio** [comment]
Tested in later versions and no leak was observed
