### ISSUE TITLE
Hard coded 

### ISSUE THREAD

**Issue by fleeto** [istio/issues#101]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.2.7
kubectl version: 1.8.1
kubernetes version: 1.7.6
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....

No

**What happened**:

In mixer log, I saw the destination in  a different domain name.

**What you expected to happen:**

The destination should be "workload.default.svc.cloud.ctrm" ?

**How to reproduce it:**

The domain suffix of my kubernetes cluster is : "cloud.ctrm"

1. Running two istio-injected service, apache as the server, and debian as the client.
2. Open a window, `kubectl logs -f [mixer pod name] mixer -n istio0system`, watching logs of mixer.
3. `kubectl exec -it sleep-2696925455-120l0 bash -n default`, enter its shell.
4. `curl http://workload-200`
5. in mixer log, I saw: 

~~~
[istio-mixer-113835218-fkqbn mixer] destination.ip                : [172 200 180 211]
[istio-mixer-113835218-fkqbn mixer] destination.labels            : map[pod-template-hash:2584901376 version:http200 app:workload]
[istio-mixer-113835218-fkqbn mixer] destination.namespace         : default
[istio-mixer-113835218-fkqbn mixer] destination.service           : workload.default.svc.cluster.local
[istio-mixer-113835218-fkqbn mixer] destination.serviceAccount    : default
~~~

**Comment by costinm** [comment]
To reproduce: how did you setup the cluster ? Kube-admin or on a cloud provider ?

**Comment by fleeto** [comment]
@costinm 

Bare metal

**Comment by douglas-reid** [comment]
fwiw, the `kubernetes` adapter in Mixer (if that is source of the `destination.service` value) has a parameter for controlling the cluster name: `cluster_domain_name`.  The default value there is `svc.cluster.local`, but if specified in config, it can use `cloud.ctrm` as desired.

if the proxy is sending the correct value and Mixer is overriding it, there is also a Mixer PR out to fix that behavior (https://github.com/istio/mixer/pull/1460).

**Comment by kyessenov** [comment]
There are flags in pilot service to insert the domain suffix: 
https://github.com/istio/pilot/blob/master/cmd/pilot-discovery/main.go#L247
and
https://github.com/istio/pilot/blob/master/cmd/pilot-agent/main.go#L191

The underlying cause is that k8s does not expose the setting for the domain suffix.

**Comment by fleeto** [comment]
@kyessenov @douglas-reid Thanks for your help, the issues is solved.

Add  lines into pilot pod, and each sidecar pod.
~~~yaml
- --domain
- cloud.ctrm
~~~
