### ISSUE TITLE
all helloworld  pods  are in  CrashLoopBackOff

### ISSUE THREAD

**Issue by tgllres** [istio/issues#102]
Bug:

**Bug:**
Y
istioctl version

[root@hdfs01 helloworld]# istioctl version
Version: 0.2.9
GitRevision: 48ce32e6909d120a8ecee58b6b7a84094da36b7c
GitBranch: master
User: root@881c9704f303
GolangVersion: go1.8.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not ?**
enabled

**What happened**:
I am attempting to run the Istio helloworld app and after running the following command:
istioctl kube-inject -f helloworld.yaml -o helloworld-istio.yaml  
kubectl apply -f helloworld-istio.yaml  -n istio-system

I see that all the corresponding pods are in CrashLoopBackOff state:
log info is :
 kubectl logs helloworld-v1-3960969699-xpx0v -n istio-system -c istio-proxy 

I1023 10:42:46.363669       1 main.go:65] Version root@881c9704f303-0.2.9-48ce32e6909d120a8ecee58b6b7a84094da36b7c
I1023 10:42:46.363864       1 main.go:104] Proxy role: proxy.Node{Type:"sidecar", IPAddress:"172.17.7.4", ID:"helloworld-v1-3960969699-xpx0v.istio-system", Domain:"istio-system.svc.cluster.local"}
I1023 10:42:46.363910       1 resolve.go:21] Attempting to lookup address: istio-mixer.istio-system
I1023 10:43:01.364136       1 resolve.go:28] Finished lookup of address: istio-mixer.istio-system
Error: lookup failed for udp address: i/o timeout
Usage:
  agent proxy [flags]

Flags:
      --availabilityZone string           Availability zone
      --binaryPath string                 Path to the proxy binary (default "/usr/local/bin/envoy")
      --configPath string                 Path to the generated configuration file directory (default "/etc/istio/proxy")
      --connectTimeout duration           Connection timeout used by Envoy for supporting services (default 1s)
      --discoveryAddress string           Address of the discovery service exposing xDS (e.g. istio-pilot:8080) (default "istio-pilot:8080")
      --discoveryRefreshDelay duration    Polling interval for service discovery (used by EDS, CDS, LDS, but not RDS) (default 1s)
      --domain string                     DNS domain suffix. If not provided uses ${POD_NAMESPACE}.svc.cluster.local
      --drainDuration duration            The time in seconds that Envoy will drain connections during a hot restart (default 2s)
  -h, --help                              help for proxy
      --id string                         Proxy unique ID. If not provided uses ${POD_NAME}.${POD_NAMESPACE} from environment variables
      --ip string                         Proxy IP address. If not provided uses ${INSTANCE_IP} environment variable.
      --parentShutdownDuration duration   The time in seconds that Envoy will wait before shutting down the parent process during a hot restart (default 3s)
      --proxyAdminPort int                Port on which Envoy should listen for administrative commands (default 15000)
      --serviceCluster string             Service cluster (default "istio-proxy")
      --serviceregistry string            Select the platform for service registry, options are {Kubernetes, Consul, Eureka} (default "Kubernetes")
      --statsdUdpAddress string           IP Address and Port of a statsd UDP listener (e.g. 10.75.241.127:9125)
      --zipkinAddress string              Address of the Zipkin service (e.g. zipkin:9411)

Global Flags:
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
  -v, --v Level                          log level for V logs (default 0)
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

E1023 10:43:01.365846       1 main.go:232] lookup failed for udp address: i/o timeout
--------------------------------------
thanks

**Comment by tgllres** [comment]
it's my fault, The problem has been solved；the reasion is /usr/lib/systemd/system/kubelet.service  dns parameter configuration error；

**Comment by sandylss** [comment]
hi
I also met the problem,can u tell me the details about how to resolve this error?
thank u~
