### ISSUE TITLE
Port name `redis` not working in Istio 0.2.9

### ISSUE THREAD

**Issue by msogrin** [istio/issues#103]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): YES

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.2.9
GitRevision: 48ce32e6909d120a8ecee58b6b7a84094da36b7c
GitBranch: master
User: root@881c9704f303
GolangVersion: go1.8

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-12T00:45:05Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-06T20:53:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

minikube version
minikube version: v0.22.3
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
With Auth.

**What happened**: with service defined as 
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
```
I'm getting "Error: Connection reset by peer" when connecting to it.
```
# redis-cli -h redis                                                                                
redis:6379> PING
Error: Connection reset by peer
```

**What you expected to happen:**  Connection successful as in 
```
# redis-cli -h redis
redis:6379> PING
PONG
```

If using Istio 0.2.7, it works properly.

If changing port spec from `name: redis` to `name: tcp`, it works properly even with Istio 0.2.9.
But according to https://istio.io/docs/setup/kubernetes/sidecar-injection.html (item 2 "Named ports"), the `redis` is the correct name here.

**How to reproduce it:**

1. Deploy Redis 4 service with name `redis`. 
2. Deploy any other pod, install `redis-tools` package for `redis-cli`, and use it to ping Redis server using command `redis-cli -h redis`.

**Comment by GregHanson** [comment]
@msogrin are you still seeing this problem in istio version 0.5.1 or later?

**Comment by msogrin** [comment]
The problem is not reproducible anymore in 0.5.1.

**Comment by ldemailly** [comment]
great to hear! thx for having checked!

**Comment by vadimeisenbergibm** [comment]
the issue should have been resolved by https://github.com/istio/istio/pull/1915.
