### ISSUE TITLE
istio-pilot crashloop on istio-auth.yaml installation - cannot find custom resources

### ISSUE THREAD

**Issue by booninite** [istio/issues#104]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

Searched all issues available to me and did not find anything.

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
Version: 0.2.9
GitRevision: 48ce32e6909d120a8ecee58b6b7a84094da36b7c
GitBranch: master
User: root@881c9704f303
GolangVersion: go1.8
```
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.10-gke.1", GitCommit:"5399ab6217c2f2f4bb4de52a2a23ccc4cd034df2", GitTreeState:"clean", BuildDate:"2017-09-27T18:06:48Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Installed `istio-auth.yaml`

**What happened**:
Pilot pod hung in CrashLoop with following error:
```
failed to register custom resources. the server could not find the requested resource
```

**What you expected to happen:**
Pod to work.

**How to reproduce it:**
Create new GKE cluster, follow Quick Start Guide.

**Comment by kyessenov** [comment]
Please use k8s 1.7 on the server-side.
