### ISSUE TITLE
istioctl on Windows 10 - for any command (even version): panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lucasjellema** [istio/issues#105]
**Is this a BUG or FEATURE REQUEST?:** Bug

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):
it is perhaps related to https://github.com/istio/pilot/issues/1336

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.2.9
kubectl version: 1.7.5 
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....

**What happened**:
When I run 
(a detailed description of the installation and the issue is in this blog article: https://technology.amis.nl/2017/10/25/first-steps-with-istio-on-kubernetes-on-minikube-on-windows-10/)

 istioctl version

the result is:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x121513f]

goroutine 1 [running]:
main.getDefaultNamespace(0x14b878a, 0xd, 0x0, 0x0)
        /tmp/gopath/src/istio.io/pilot/cmd/istioctl/main.go:700 +0xbf
main.glob..func4(0x1cbb3c0, 0x1ce6f58, 0x0, 0x0)
        /tmp/gopath/src/istio.io/pilot/cmd/istioctl/main.go:86 +0x40
istio.io/pilot/vendor/github.com/spf13/cobra.(*Command).execute(0x1cbb3c0, 0x1ce6f58, 0x0, 0x0, 0x1cbb3c0, 0x1ce6f58)
        /tmp/gopath/src/istio.io/pilot/vendor/github.com/spf13/cobra/command.go:637 +0x550
istio.io/pilot/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1cb9f80, 0x121ac0a, 0x0, 0x0)
        /tmp/gopath/src/istio.io/pilot/vendor/github.com/spf13/cobra/command.go:729 +0x340
istio.io/pilot/vendor/github.com/spf13/cobra.(*Command).Execute(0x1cb9f80, 0x0, 0x154)
        /tmp/gopath/src/istio.io/pilot/vendor/github.com/spf13/cobra/command.go:688 +0x32
main.main()
        /tmp/gopath/src/istio.io/pilot/cmd/istioctl/main.go:531 +0xc7

Note: I have just tried to do the same thing with release 0.2.7 and this was successful for me:
C:\temp\istio-0.2.7\bin>istioctl version
Version: 0.2.7
GitRevision: 6b145c189aad8306b13af1725123bebfbc7eefd4
GitBranch: master
User: root@f1eeb85f62ab
GolangVersion: go1.8

**What you expected to happen:**
I expect a version label to be written to the output

**How to reproduce it:**
- install minikube on Windows 10
- download istio.zip for Windows; extract zip file to directory; add directory to Windows PATH  environment variable
- run istioctl version

**Feature Request:**
N

**Describe the feature:**

**Comment by MCLDG** [comment]
+1

I have the same problem, except I've installed on Linux.

I installed Istio 0.2.10 on a brand new server, Ubuntu 14.04, as follows:

```
curl -L https://git.io/getLatestIstio | sh -
export PATH=$PWD/bin:$PATH
istioctl version
```

The result

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x11f2018]

goroutine 1 [running]:
main.getDefaultNamespace(0xc4202cc280, 0x12, 0x0, 0x0)
cmd/istioctl/main.go:700 +0xb8
main.glob..func4(0x1c35de0, 0x1c61be8, 0x0, 0x0)
cmd/istioctl/main.go:86 +0x39
github.com/spf13/cobra.(*Command).execute(0x1c35de0, 0x1c61be8, 0x0, 0x0, 0x1c35de0, 0x1c61be8)
external/com_github_spf13_cobra/command.go:637 +0x549
github.com/spf13/cobra.(*Command).ExecuteC(0x1c349a0, 0x41172d, 0xc4200002a8, 0x0)
external/com_github_spf13_cobra/command.go:729 +0x339
github.com/spf13/cobra.(*Command).Execute(0x1c349a0, 0xc4204f7f78, 0x434056)
external/com_github_spf13_cobra/command.go:688 +0x2b
main.main()
cmd/istioctl/main.go:531 +0xc0
```

Doing exactly the same thing on v0.2.7 works:

```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=0.2.7 sh -
export PATH=$PWD/istio-0.2.7/bin:$PATH
istioctl version
```

results in:

```
Version: 0.2.7
GitRevision: 6b145....
GitBranch: master
User: blah, blah, blah
GolangVersion: go1.8.3
```

**Comment by ayj** [comment]
Looks like kubectl's `current-context` may not be point to a valid context yet when istioctl is invoked. Does`kubectl config get-contexts` show valid currently selected context information?

See https://github.com/istio/pilot/pull/1667 for potential fix.

**Comment by MCLDG** [comment]
You nailed it @ayj - in my case I'm using a separate config file. This fixed it:

`istioctl --kubeconfig=kubeconfig.conf version`

**Comment by kahootali** [comment]
I have also having same issue, but my kubectl context is set to minikube. When I

 `kubectl config get-contexts` 

I get:

```
CURRENT   NAME       CLUSTER    AUTHINFO   NAMESPACE
      *   minikube   minikube   minikube
```

I am using minikube 0.23 Windows 10, kubernetes 1.8.0 and istio 0.2.12

**Comment by ayj** [comment]
@kahootali, did explicitly specifying `--kubeconfig` work for you?

**Comment by kahootali** [comment]
@ayj  Yes it did work.  Thank you

**Comment by techy16** [comment]
I am using minikube 0.22.2 Windows 7, kubernetes 1.7.5 and istio 0.2.12 and also i tried this istioctl --kubeconfig=kubeconfig.conf version but i am still get the error

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x12152f0]

goroutine 1 [running]:
main.getDefaultNamespace(0xc04203a44d, 0xf, 0x0, 0x0)
        /home/sebastienvas/go/src/istio.io/pilot/cmd/istioctl/main.go:700 +0xa0
main.glob..func4(0x1cbd3c0, 0xc042105450, 0x0, 0x1)
        /home/sebastienvas/go/src/istio.io/pilot/cmd/istioctl/main.go:86 +0x40
istio.io/pilot/vendor/github.com/spf13/cobra.(*Command).execute(0x1cbd3c0, 0xc0421053e0, 0x1, 0x1, 0x1cbd3c0, 0xc0421053e0)
        /home/sebastienvas/go/src/istio.io/pilot/vendor/github.com/spf13/cobra/command.go:637 +0x550
istio.io/pilot/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1cbbf80, 0x121ae0a, 0x0, 0x0)
        /home/sebastienvas/go/src/istio.io/pilot/vendor/github.com/spf13/cobra/command.go:729 +0x340
istio.io/pilot/vendor/github.com/spf13/cobra.(*Command).Execute(0x1cbbf80, 0x0, 0x154)
        /home/sebastienvas/go/src/istio.io/pilot/vendor/github.com/spf13/cobra/command.go:688 +0x32
main.main()
        /home/sebastienvas/go/src/istio.io/pilot/cmd/istioctl/main.go:531 +0xc7

**Comment by kahootali** [comment]
@techy16 Try specifying the kubeconfig explicitly by: 
`istioctl --kubeconfig C:\Users\...\.kube\config version`
