### ISSUE TITLE
containerized istioctl - jenkins kubernetes pipeline (on GKE)

### ISSUE THREAD

**Issue by jensneuse** [istio/issues#111]
**Is this a BUG or FEATURE REQUEST?:**
Feature Request

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**

istioctl version
Version: 0.2.9
GitRevision: 48ce32e6909d120a8ecee58b6b7a84094da36b7c
GitBranch: master
User: root@881c9704f303
GolangVersion: go1.8.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not ?**
disabled

**Feature Request:**

I'd like to achieve canary + green blue deployment via jenkins kubernetes pipelines.
Therefore I have to run kubectl and istioctl containerized.
Running kubectl with RBAC works fine because jenkins kubernetes pipeline allows to configure the serviceAccount to run a pod. However, istioctl needs '/root/.kube/config' to work. This is not trivial because the usual procedure on GKE would be to login via gcloud cli and create a kubectl config which is undesireable.

I'd be super happy for any pointers. I think it would be useful to others too because such solution would make it easy to "script" deployment pipelines of any kind.

**Comment by ldemailly** [comment]
can you combine kubectl and istioctl in 1 image ? if your pipeline includes deployment you do need a .kubeconfig no ?

**Comment by GregHanson** [comment]
@jensneuse any follow up questions on this?

**Comment by Sneko** [comment]
@jensneuse @GregHanson 

Just found that: https://github.com/controlplaneio/theseus

Didn't tried but may it could help you. Do not hesitate to share other ones if you have :)

**Comment by ayj** [comment]
Closing in favor of https://github.com/istio/istio/issues/1971
