### ISSUE TITLE
commands don't work with zsh

### ISSUE THREAD

**Issue by linsun** [istio/issues#12]
Using this command as an example.  I think there maybe one or two other commands like this one.  

→ export GATEWAY_URL=$(kubectl get po -l istio=ingress -o jsonpath={.items[0].status.hostIP}):$(kubectl get svc istio-ingress -o jsonpath={.spec.ports[0].nodePort})

zsh: no matches found: jsonpath={.items[0].status.hostIP}
zsh: no matches found: jsonpath={.spec.ports[0].nodePort}

bash worked

bash-3.2$ export GATEWAY_URL=$(kubectl get po -l istio=ingress -o jsonpath={.items[0].status.hostIP}):$(kubectl get svc istio-ingress -o jsonpath={.spec.ports[0].nodePort})

**Comment by ldemailly** [comment]
Those are examples assuming bash yes

Eventually we want everything to work without any manual variable setting

**Comment by linsun** [comment]
ok thanks for clarifying that.  Would be good to explain what this gateway_url is and recommend people to use bash since that is well tested.

**Comment by kyessenov** [comment]
Yeah, thanks for reporting. We need to add quotes around jsonpath values everywhere @ldemailly

**Comment by ldemailly** [comment]
Yes I had fixed an earlier instance of this, but again we should shoot for no cryptic variable setting necessary at all

**Comment by ldemailly** [comment]
@linsun let me know if you find more of these or still having problems, and reopen this or file a new issue - thanks for the repor!
