### ISSUE TITLE
Proxy agent fails with Minikube started with --extra-config=apiserver.Authorization.Mode=RBAC

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/issues#120]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version - istio built from HEAD
kubectl version 1.8.0
minikube version 0.23.0
```

**Is Istio Auth enabled or not ?**
The bug happens with and without Istio Auth

**What happened**:
istio-ingress crashes.
The logs shows:

```
Finished lookup of address: istio-mixer.istio-system 
Error: lookup failed for udp address: i/o timeout
```
The same error as in 
https://groups.google.com/forum/#!topic/istio-users/Ry6TO3FjlTg 
**What you expected to happen:**
istio-ingress to start running
**How to reproduce it:**
just deploy istio:   kubectl apply -f install/kubernetes/istio.yaml or   kubectl apply -f install/kubernetes/istio-auth.yaml

**Feature Request:**
N

**Describe the feature:**

**Comment by chentao1596** [comment]
@vadimeisenbergibm Hi, have you solved this problem? I meet it, too. And, i can't solve it when follow the method of https://groups.google.com/forum/#!topic/istio-users/Ry6TO3FjlTg.

**Comment by vadimeisenbergibm** [comment]
@chentao1596 sorry, I did not see your comment. I do not experience this problem now with Istio 0.5.1. I am closing the issue.

**Comment by chentao1596** [comment]
@vadimeisenbergibm ok, thank you for your reply!
