### ISSUE TITLE
grpc over http2

### ISSUE THREAD

**Issue by dudu8** [istio/issues#122]
Hi, I configured ingress for grpc service by following [configuring-ingress-for-grpc](https://github.com/istio/istio.github.io/blob/master/_docs/tasks/traffic-management/ingress.md#configuring-ingress-for-grpc), but how can I call grpc service with http2. I noticed linkerd uses `identifier` [https://github.com/linkerd/linkerd/pull/1116], is `Ingress Identifier` being supported by istio so that I can call grpc service outside k8s from the url  `$GATEWAY_URL/helloworld.Greeter/SayHello`?

**Comment by kyessenov** [comment]
The ingress is using auto codec which works with grpc and http/1.1 with no extra configuration. The backend service should have the port prefixed with `grpc-` or `http2-` to enable h2 features on the  upstream from the ingress.

**Comment by GregHanson** [comment]
@dudu8 are you still having this problem in istio version 0.5.1 or later?
