### ISSUE TITLE
upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by Morriz** [istio/issues#128]
Running minikube with:
```
minikube start \
    --kubernetes-version v1.8.0 \
    --extra-config=apiserver.Authorization.Mode=RBAC \
    --extra-config=apiserver.Admission.PluginNames="NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,GenericAdmissionWebhook,PodPreset" 
```
or with:
```
minikube start \
    --bootstrapper kubeadm \
    --kubernetes-version v1.8.4 \
    --extra-config=apiserver.admission-control="NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,GenericAdmissionWebhook,PodPreset" 
```
and then applying `istio-auth.yaml` (2.1.12) and `bookinfo.yaml` in succession gives me the following error when I visit `${loadbalancerIp}/productpage`:
```
upstream connect error or disconnect/reset before headers
```
When I visit the services from busybox I get the correct responses. I can't see any errors in the pilot's logs, but in the ingress logs I see a lot of these:
```
external/envoy/source/common/upstream/cds_subscription.cc:65] cds: fetch failure: Failed to load certificate '/etc/certs/root-cert.pem'
```
and this:
```
[warning][http] src/envoy/mixer/mixer_control.cc:419] Could not convert to ip: destination.ip: 
[libprotobuf INFO external/mixerclient_git/src/check_cache.cc:153] Add a new Referenced for check cache: Absence-keys: source.uid, target.service, destination.service, Exact-keys: source.ip, destination.uid, destination.ip, context.protocol, 
```

**Comment by markvincze** [comment]
Hey @Morriz,

Did you find out anything about this issue? I'm seeing the same `upstream connect error or disconnect/reset before headers` error when deploying bookinfo to a k8s cluster run on GKE.

**Comment by GregHanson** [comment]
@Morriz are you still seeing this problem with istio version 0.5.1 or later?  We have included minikube test as part of our automated testing.  You can see how we start minikube here:
https://github.com/istio/istio/blob/master/bin/testEnvRootMinikube.sh
