### ISSUE TITLE
Access Istio Grafana dashboard via node port doesn’t work

### ISSUE THREAD

**Issue by linsun** [istio/issues#13]
Access Istio Grafana dashboard via node port doesn’t work, got “page not responding” error.  We should clarify this requires changes to the yaml file on the service type NodePort to get it working.  The instruction written as it is kinda indicated that it would work out of box as I was following it.

https://istio.io/docs/tasks/installing-istio.html -- Verifying the Grafana dashboard

**Comment by douglas-reid** [comment]
@linsun would you mind providing a few additional details?

Did you try port-forwarding (via `kubectl port-forward $(kubectl get pod -l app=grafana -o jsonpath='{.items[0].metadata.name}') 3000:3000`) or something else ?

**Comment by linsun** [comment]
@douglas-reid yes i did port forwarding, that worked for me.  What i have trouble is to reach the service on the node port.

→ kubectl get services
NAME            CLUSTER-IP     EXTERNAL-IP   PORT(S)                       AGE
details         10.10.10.206   <none>        9080/TCP                      6h
grafana         10.10.10.234   <pending>     3000:31685/TCP                6h

**Comment by linsun** [comment]
Closing this out as this appears to be working on my new cluster.   I was able to reach the grafana via node-ip:node-port.  Reading K8s doc confirmed this is the expected behavior:   “LoadBalancer: Exposes the service externally using a cloud provider’s load balancer. NodePort and ClusterIP services, to which the external load balancer will route, are automatically created.”
