### ISSUE TITLE
Images of sidecar and proxy isn't existing on docker hub

### ISSUE THREAD

**Issue by fleeto** [istio/issues#130]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.3.0
kubectl version: v1.8.4
apiserver version: 1.7.9
```
**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....

No

**What happened**:

Injected deployment won't run successfully on kubernetes.

**What you expected to happen:**

**How to reproduce it:**

`istioctl kube-inject -f sleep.yaml | grep image:` returned

~~~
      - image: dustise/sleep
        image: docker.io/istio/proxy_debug:0.3.0.0-c5a2b3bc3afe3f5bc4198df726bd0455505212d7
        image: docker.io/istio/proxy_init:0.3.0.0-c5a2b3bc3afe3f5bc4198df726bd0455505212d7
        image: alpine
~~~

Then pull them:

`docker pull docker.io/istio/proxy_debug:0.3.0.0-c5a2b3bc3afe3f5bc4198df726bd0455505212d7`

~~~
Error response from daemon: manifest for istio/proxy_debug:0.3.0.0-c5a2b3bc3afe3f5bc4198df726bd0455505212d7 not found
~~~

**Feature Request:**

N

**Describe the feature:**

**Comment by ldemailly** [comment]
0.3.0.0 is not a real release, just a test
