### ISSUE TITLE
istioctl 0.3.0 kube-inject dies silently if istio namespace is not matching

### ISSUE THREAD

**Issue by c0dingarchit3ct** [istio/issues#133]
**Is this a BUG or FEATURE REQUEST?:**
A bug
**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):
Yes and found nothing
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.3.0
kubectl version v1.7.6
```

**Is Istio Auth enabled or not ?** NO
Did you install istio.yaml, istio-auth.yaml.... YES

**What happened**:
Installed istio under 'istio' name space (not the default istio-system)
On mac osx installed istioctl 0.3.0
Ran istioctl kube-inject -f <filename>

It exits silently

**What you expected to happen:**
After installing 0.2.12 and trying the same command, I got the PRECIOUS error message 
Error: could not read valid configmap "istio" from namespace  "istio-system": configmaps "istio" not found - Re-run kube-inject with `-i <istioSystemNamespace> and ensure valid MeshConfig exists

**How to reproduce it:**
install istio in a name space other than default and run istioctl without using '-i'

**Feature Request:**
Y/N

**Describe the feature:**

**Comment by GregHanson** [comment]
resolved by https://github.com/istio/istio/pull/2334
