### ISSUE TITLE
Mixer has an excessive number of disk writes impacting overall performance

### ISSUE THREAD

**Issue by jnativio** [istio/issues#134]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.2.12
kubectl version: v1.7.4-2+eb9172c211dc41
```

**Is Istio Auth enabled or not ?**
istio.yaml was installed.

**What happened**:
I installed istio.yaml 0.2.12  as is initially and then I changed some properties in order to minimize the performance impact on the workload. Even with all known tuning options it was observed a large number of disk writes during the load as well large CPU usage, causing the throughput to be a fraction of what obtained without the mixer.

**What you expected to happen:**
Less performance impact.

**How to reproduce it:**
Drive some workload to a microservices app using Istio with and without the mixer to compare the performance impact. 

**Feature Request:**
N

**Describe the feature:**

**Comment by ldemailly** [comment]
Issue moved to [istio/istio #2025](https://github.com/istio/istio/issues/2025) via [**ZenHub**](https://www.zenhub.com/)
