### ISSUE TITLE
istio_ca causes latency/5xx problems

### ISSUE THREAD

**Issue by kdillane** [istio/issues#138]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):
I did review open issues and did not find this one called out.

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
0.2.12

```
istioctl version: N/A
kubectl version: 1.8.0
```

**Is Istio Auth enabled or not ?**
istio.yaml

**What happened**:
We have seen an interesting problem in our Kubernetes cluster where there are periodic errors and latency increases hourly. This behavior seems to be caused by the istio-ca pod. When it attempts to renew the self-signed certificates in the cluster (presumably), it causes both our application Pods and the Istio Ingress to display high latency and 5xx responses.

**What you expected to happen:**
We do not expect periodic failures/latency spikes due to istio-ca.  When we disabled the istio-ca pods in our cluster and have seen the periodic failures disappear.

**How to reproduce it:**
At around 100 tps per node/Istio-Ingress, this should be obvious from Grafana graphs.

**Comment by kdillane** [comment]
Original issue: https://github.com/istio/istio/issues/2090

**Comment by andraxylia** [comment]
Will follow up on istio/istio#2090
