### ISSUE TITLE
minor native build issues

### ISSUE THREAD

**Issue by theganyo** [istio/issues#149]
A couple of very minor issues I ran into with the master build after pulling today: 

1. The build requires “dep” but doesn’t install it itself or list it in the dependencies.
2. Gopkg.lock is changed during build
3. security/docker/ca-certificates.tgz is created during build and not ignored

I’d be happy to submit a PR for necessary changes, but wanted verify potential solutions first:

1. Add prereq to DEV-GUIDE.md
2. Add a note in DEV-GUIDE.md? Add to .gitignore?
3. Add to .gitignore

**Comment by GregHanson** [comment]
@theganyo we have switched our vendor dir to a git submodule, so dep should no longer be a dependency.  If you find any other on-boarding concerns, feel free to submit a PR or open another issue for tracking
