### ISSUE TITLE
unable to connect to in-mesh TCP ports using pod ip directly

### ISSUE THREAD

**Issue by terinjokes** [istio/issues#150]
**Is this a BUG or FEATURE REQUEST?:**

BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

Y

**Bug:**

I'm unable to connect to generic in-mesh TCP ports.

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
kubectl version
```
Istio version: 0.4, installed from the "install" directory of istio/istio at the 0.4 tag.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**

Y

**What happened**:

A ClusterIP service was created with port name "tcp-test" pointing at deployments running a generic TCP service on the specified port. Connections from other containers in the Istio mesh were unable to connect to the TCP service.

There were no logs from any istio-proxy containers.

**What you expected to happen:**

TCP services were able to connect

**Comment by ldemailly** [comment]
you have to use the release file, not the source tree at the tag (the yaml in source tree were stale, now removed)

**Comment by terinjokes** [comment]
@ldemailly Thanks. That change wasn't clearly communicated. Thanks for removing the files. I'll close this if using the release templates resolves the issue.

**Comment by terinjokes** [comment]
@ldemailly There's no differences between what's in the 0.4 tarballs and what was in the repositories at the 0.4 tag.

**Comment by ldemailly** [comment]
Ah you're right, somehow 0.4.0 was patched up 
unlike https://github.com/istio/istio/blob/0.3.0/install/kubernetes/istio.yaml#L261
for instance

but where did you get istioctl from ?
can you do
```
istioctl version
```
as well as
```
istioctl kube-inject -f any.yaml | grep Image
```

**Comment by terinjokes** [comment]
I'm not using istioctl, I'm using the auto-injection initializer.

**Comment by ldemailly** [comment]
can you paste the output of
```
make -C samples/rawvm dump-images
```

**Comment by terinjokes** [comment]
```
      3 boostport/kubernetes-vault
      3 boostport/kubernetes-vault:latest
     14 busybox:1.27.2
[internal images omitted]
      1 docker.io/istio/istio-ca:0.4.0
      1 docker.io/istio/mixer:0.4.0
      1 docker.io/istio/pilot:0.4.0
      8 docker.io/istio/proxy:0.2.12
      1 docker.io/istio/proxy_debug:0.2.12
     22 docker.io/istio/proxy_debug:0.4.0
      8 docker.io/istio/proxy_init:0.2.12
     19 docker.io/istio/proxy_init:0.4.0
      1 docker.io/istio/sidecar_initializer:0.4.0
      2 gcr.io/google_containers/addon-resizer:1.0
      2 gcr.io/google_containers/explorer:1.0
      2 grafana/grafana:4.5.2
      1 istio/istio-ca:0.4.0
      1 istio/mixer:0.4.0
      1 istio/pilot:0.4.0
      8 istio/proxy:0.2.12
      1 istio/proxy_debug:0.2.12
     22 istio/proxy_debug:0.4.0
      8 istio/proxy_init:0.2.12
     19 istio/proxy_init:0.4.0
      1 istio/sidecar_initializer:0.4.0
      2 jaegertracing/jaeger-collector:0.9
      2 jaegertracing/jaeger-query:0.9
      4 lyft/envoy:0408b98cd2b150cb26e4b81844788c46059a2dfa
      2 openpolicyagent/kube-mgmt:0.4
      2 openpolicyagent/opa:0.5.12
      2 prom/statsd-exporter
      3 prom/statsd-exporter:latest
      1 prom/statsd-exporter:v0.5.0
      2 quay.io/coreos/grafana-watcher:v0.0.8
      2 quay.io/coreos/kube-state-metrics:v1.0.1
      2 quay.io/coreos/prometheus-operator:v0.15.0
     14 quay.io/pires/docker-elasticsearch-kubernetes:6.1.1
     12 quay.io/prometheus/node-exporter:v0.15.0
```

**Comment by ldemailly** [comment]
somehow you have a bunch of 0.2.12 left

did you upgrade from 0.2.12 ? it seems like the upgrade didn't work

if you check which pods do have 0.2.12 and redeploy those, it should help

about NodePort specifically though, you need to use the svcIp, you can't use the nodeIp directly, is that how you connect ?

**Comment by terinjokes** [comment]
@ldemailly We're creating a new service and new deployments, so 0.2.12 sidecars shouldn't be part of the problem (the new deployments are getting 0.4 sidecars). We're rotating the remaining deployments, so that should clear up soon.

I'm attempting to connect to the Kubernetes Service IP created from a type: NodePort service.

**Comment by ldemailly** [comment]
I assume you do have auth/mtls on ? any details on how it fails ? (connection closed ? hangs ? ...)

**Comment by ldemailly** [comment]
I haven't personally tested TCP NodePort, though I believe it should work - can you try a regular TCP service first ? (that works and I personally tested it and we have the mysql/mongodb regression tests for those)
https://github.com/istio/istio/blob/master/samples/bookinfo/kube/bookinfo-mysql.yaml

**Comment by terinjokes** [comment]
@ldemailly My apologies, I see where some of the confusion here is coming from. On Friday I said "A NodePort service was created" when I meant "A ClusterIP service was created". I've corrected the issue.

**Comment by terinjokes** [comment]
@ldemailly It seems in this case, the multiple parts of the service are communicating over the Kubernetes Service IP long enough to exchange direct IP addresses. They then switch to attempting to connect directly.

My guess, since istio_proxy is silent, is that mTLS can't be established properly, and a proxy somewhere closes the connection.

Is mTLS supposed to handle this case?

**Comment by ldemailly** [comment]
when you have the proxy injected all inbound traffic goes to the proxy

when you have mtls enabled, all traffic must present a certificate - and the outbound envoy capture makes it happen

but if you use the podip directly, instead of the clusterip, that traffic isn't processed properly as envoy looks at services (cluster ips)

**Comment by terinjokes** [comment]
@ldemailly Yeah, that's the behavior we assumed and feared. :frowning: 

Unfortunately, this is behavior of the application we can't control. It will always attempt to switch to the pod IPs.

**Comment by ldemailly** [comment]
how does it even know the podip ? maybe you can make whoever says that ip believe the pod's ip is the cluster ip ?

alternatively I think it should be possible to configure envoy to mtls secure pod-pod traffic within a k8s cluster maybe we can turn this into a feature request for pilot

@kyessenov, thoughts ? (and did I get the above mostly correct?)

**Comment by terinjokes** [comment]
@ldemailly The services use the service IP to coordinate, and part of that coordination is the pod IP.

In fancier terms: the application has a master election over the service IP, and then they attempt to connect to the elected master's IP address.

The service will only announce an IP address if it can bind to it, and the pod doesn't have the service's IP address in the network namespace.

**Comment by kyessenov** [comment]
I don't think we support mixed-case like this that uses both service VIP and pod IPs. 
For pure VIP case, we don't create separate TCP routes per each pod, as that has a potential to blow up the routing tables.
For pure pod IP case (called headless), we require that the service port be chosen as unique in the cluster. A route is created for that port (0.0.0.0:PORT) that lets traffic go passthrough. This is to support rich client libraries like the one for kafka, to do their own network functions (like LB).

**Comment by terinjokes** [comment]
@kyessenov It would be great if we could come up with something to opt-in handling mixed cases like this: where only some subset of pods needs be mixed, and thus not every pod in the cluster needs the routing rule. One of our motivations for our move to Kubernetes is to avoid needing to allocate cluster-unique ports.

In the short-term, having the service working with some caveat is better than not working at all. I can create a [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services). Is the 0.0.0.0:PORT rule an Istio route rule?

**Comment by rlguarino** [comment]
Is this something that will be addressed in future releases of Istio? I'm trying to get Prometheus to work and having a tough time without disabling MTLS.

**Comment by terinjokes** [comment]
@kyessenov Do you mind expanding on your kafka example? I searched the issues in a couple Istio repos, and I haven't seem anything similar.

**Comment by ldemailly** [comment]
Issue moved to [istio/istio #3398](https://github.com/istio/istio/issues/3398) via [**ZenHub**](https://www.zenhub.com/)

**Comment by axelbodo** [comment]
I'd like to ask regarding this, than how to solve per pod communication, like custom metric scapers, which need to communicate directly with pods, and not with services, even when mtls is also in effect.
