### ISSUE TITLE
Install all components using only helm install without the need of any external script

### ISSUE THREAD

**Issue by luisyonaldo** [istio/issues#151]
**FEATURE REQUEST**

**Bug:**
N

**Feature Request:**
Y

**Describe the feature:**
In other to install helm charts you nee to run `deployIstioHelmCharts.sh` which for me breaks the hole idea of using helm (stop using scripts and just one single tool).

The reason to use a script is because CRD need to be installed before installing the other resources that depend on them, but this is possible to do using helm hooks.

With this you need to run `helm install` only to install all istio charts which will install all istio components and configs.

**Comment by luisyonaldo** [comment]
https://github.com/istio/istio/pull/2461#issuecomment-355751318

**Comment by GregHanson** [comment]
I believe all items were addressed in https://github.com/istio/istio/pull/2461, if not please re-open
