### ISSUE TITLE
BookInfo doesn't work in large k8s environments

### ISSUE THREAD

**Issue by markvincze** [istio/issues#162]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**: Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.4.0
kubectl version: Client: 1.8.4, Server: 1.8.6-gke.0
```

**Is Istio Auth enabled or not ?**
No

**What happened**:
I installed the BookInfo sample on our GKE cluster in the default namespace with the following command:

```
kubectl apply -f <(istioctl kube-inject -f ./bookinfo.yaml)
```

Then I verified that the resources exist:
```
$ k get po
NAME                              READY     STATUS    RESTARTS   AGE
details-v1-546644797b-6s8km       2/2       Running   0          16m
productpage-v1-69b98bb596-7t7w4   2/2       Running   0          16m
ratings-v1-c9fcc6d88-b8r8b        2/2       Running   0          16m
reviews-v1-6b985ffbf6-fr8gt       2/2       Running   0          16m
reviews-v2-7fb94cfb88-jqzm4       2/2       Running   0          16m
reviews-v3-5b48884dfb-hqj7x       2/2       Running   0          16m
```

```
$ k get svc
NAME          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
details       ClusterIP   10.251.242.176   <none>        9080/TCP         16m
kubernetes    ClusterIP   10.251.240.1     <none>        443/TCP          1y
productpage   ClusterIP   10.251.249.229   <none>        9080/TCP         16m
ratings       ClusterIP   10.251.254.8     <none>        9080/TCP         16m
reviews       ClusterIP   10.251.248.88    <none>        9080/TCP         16m
```

Then I determined the IP address of the ingress:

```
k get ingress -o wide -n default
NAME         HOSTS     ADDRESS          PORTS     AGE
gateway      *         35.190.211.253   80        18m
```

Then if I opened `http://35.190.211.253/productpage` in my browser, I see this:

![image](https://user-images.githubusercontent.com/1122274/34867171-79605c46-f77f-11e7-8817-16e8614cc038.png)

I refreshed the page a couple of times, and after a while it started returning this response:

![image](https://user-images.githubusercontent.com/1122274/34867189-8b1812da-f77f-11e7-92a7-6e2caa44303f.png)

This is still the case ~25 minutes after deployment.

I uploaded the logs (by doing `k logs productpage-v1-69b98bb596-7t7w4 -c istio-proxy`) of the `istio-proxy` container of the `productpage` pod (the logs of the other container were empty) here: https://gist.github.com/markvincze/c05b12209660b1432a6ff9063e62c502

**What you expected to happen:**
I was expecting BookInfo to work properly.

**How to reproduce it:**
Commands described above.

**Comment by markvincze** [comment]
Update: after ~1 hour, the productpage can be opened again in the browser, but still displays the errors about fetching the details and the reviews. And the logs have the following couple of new lines.

```
[libprotobuf INFO external/mixerclient_git/src/check_cache.cc:155] Add a new Referenced for check cache: Absence-keys: Exact-keys: context.protocol, destination.ip, destination.service, destination.uid, source.ip, source.uid, 
[libprotobuf INFO external/mixerclient_git/src/check_cache.cc:155] Add a new Referenced for check cache: Absence-keys: source.uid, Exact-keys: context.protocol, destination.ip, destination.service, destination.uid, source.ip, 
[2018-01-12T09:35:34.725Z] "GET /details/0 HTTP/1.1" 404 NR 0 0 3 - "-" "python-requests/2.18.4" "efb22a4c-4aed-9db2-9261-b1d03309d990" "details:9080" "-"
[libprotobuf INFO external/mixerclient_git/src/check_cache.cc:155] Add a new Referenced for check cache: Absence-keys: source.uid, Exact-keys: context.protocol, destination.ip, destination.service, destination.uid, source.ip, 
[libprotobuf INFO external/mixerclient_git/src/quota_cache.cc:235] Add a new Referenced for quota cache: RequestCount, reference: Absence-keys: Exact-keys: context.protocol, destination.service, 
[2018-01-12T09:35:34.734Z] "GET /reviews/0 HTTP/1.1" 404 NR 0 0 4 - "-" "python-requests/2.18.4" "efb22a4c-4aed-9db2-9261-b1d03309d990" "reviews:9080" "-"
[2018-01-12T09:35:34.743Z] "GET /reviews/0 HTTP/1.1" 404 NR 0 0 1 - "-" "python-requests/2.18.4" "efb22a4c-4aed-9db2-9261-b1d03309d990" "reviews:9080" "-"
[2018-01-12T09:35:34.685Z] "GET /productpage HTTP/1.1" 200 - 0 3955 78 28 "172.20.93.39" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "efb22a4c-4aed-9db2-9261-b1d03309d990" "35.190.211.253" "127.0.0.1:9080"
```

**Comment by ayj** [comment]
Can you capture logs of the discovery container for `istio-pilot`?  The full list of lds/rds/cds/sds from Pilot when the problem occurs would also be useful. You can use https://github.com/istio/istio/blob/master/bin/istio-proxy-cfg to capture that data.

**Comment by markvincze** [comment]
I removed and redeployed the BookInfo sample (it's displaying the "upstream connect error or disconnect/reset before headers" error again), and captured the `istio-pilot` logs, uploaded here: https://gist.github.com/markvincze/c05b12209660b1432a6ff9063e62c502#file-istio-pilot_logs-txt
(the BookInfo pods were deployed at 10:16:00)

I'll try to collect the other info with `istio-proxy-cfg` too.

**Comment by markvincze** [comment]
@ayj,

Could you give some more guidance about how I should use `istio-proxy-cfg`? Should I pass in the name of the `istio-pilot` pod, or one of the BookInfo pods?

I tried it a couple different ways, but I'm always getting the same error:

```
 △ istio/istio-0.4.0/bin ./istio-proxy-cfg lds sidecar istio-pilot-55bb7f5d9d-9c7v7
Issue Query: curl 10.251.240.13:15003/v1/listeners/istio-proxy/sidecar~10.248.173.22~istio-pilot-55bb7f5d9d-9c7v7.istio-system~istio-system.svc.cluster.local
curl: (7) Failed to connect to 10.251.240.13 port 15003: Connection timed out

 △ istio/istio-0.4.0/bin ./istio-proxy-cfg lds sidecar productpage-v1-69b98bb596-nvqb6
Issue Query: curl 10.251.240.13:15003/v1/listeners/istio-proxy/sidecar~10.248.173.42~productpage-v1-69b98bb596-nvqb6.default~default.svc.cluster.local
curl: (7) Failed to connect to 10.251.240.13 port 15003: Connection timed out

 △ istio/istio-0.4.0/bin ./istio-proxy-cfg cache_stats
Issue Query: curl 10.251.240.13:15003/cache_stats
curl: (7) Failed to connect to 10.251.240.13 port 15003: Connection timed out
```

I checked, this is the IP of the `istio-pilot` service.

```
 △ istio/istio-0.4.0/bin k get svc -n istio-system
NAME            TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                                                            AGE
istio-ingress   LoadBalancer   10.251.246.230   35.190.211.253   80:32136/TCP,443:31175/TCP                                         12d
istio-mixer     ClusterIP      10.251.243.156   <none>           9091/TCP,15004/TCP,9093/TCP,9094/TCP,9102/TCP,9125/UDP,42422/TCP   12d
istio-pilot     ClusterIP      10.251.240.13    <none>           15003/TCP,443/TCP                                                  12d
prometheus      ClusterIP      10.251.245.87    <none>           9090/TCP                                                           12d
```

**Comment by ayj** [comment]
By default `istio-proxy-cfg` assumes its run from within the cluster. You can use `kubectl port-forward` to access the `istio-pilot` service from your workstation, e.g.

```bash
pilot_pod_name=$(kubectl -n istio-system get pod -listio=pilot -o=jsonpath='{.items[0].metadata.name}')
kubectl port-forward -n istio-system ${pilot_pod_name} 15003 &
export PILOT_URL=localhost:15003
```

You can then dump the xDS state from the perspective of a consuming pod. For example, the following captures what the productpage pod would see in the bookinfo sample.

```
bin/istio-proxy-cfg lds sidecar  productpage-v1-69b98bb596-nvqb6 > lds.txt
bin/istio-proxy-cfg cds sidecar  productpage-v1-69b98bb596-nvqb6 > cds.txt
bin/istio-proxy-cfg rds sidecar 9080 productpage-v1-69b98bb596-nvqb6 > rds.txt
bin/istio-proxy-cfg sds > sds.txt
```

**Comment by markvincze** [comment]
@ayj,
I did this, and after every `istio-proxy-cfg` command I see `curl` printing

```
curl: (52) Empty reply from server
```

And these were the outputs (in order):

```
Issue Query: curl localhost:15003/v1/listeners/istio-proxy/sidecar~10.248.27.30~productpage-v1-69b98bb596-gg2pb.default~default.svc.cluster.local
```

```
Issue Query: curl localhost:15003/v1/clusters/istio-proxy/sidecar~10.248.27.30~productpage-v1-69b98bb596-gg2pb.default~default.svc.cluster.local
```

```
Issue Query: curl localhost:15003/v1/routes/9080/istio-proxy/sidecar~10.248.27.30~productpage-v1-69b98bb596-gg2pb.default~default.svc.cluster.local
```

```
Issue Query: curl localhost:15003/v1/registration/
```

It's interesting btw that if I try to `curl` any of these URLs, it says "Empty reply from server", but if I open them in the browser, they properly return some Json. Do you know what can cause this?

(Even if I send the exact request as what the browser is sending (in the Dev tools right click and "Copy as curl"), it says empty reply.)

**Comment by ayj** [comment]
I'm not sure. You could try `curl -v`.

Can you copy the output from the browser into a [gist]( https://gist.github.com/) and link it here?

**Comment by markvincze** [comment]
@ayj,

Strange, I tried it again, and now opening the URL in Chrome gives the same error, it says `ERR_EMPTY_RESPONSE`.

If I try to curl with `-v`, I see this:

```
curl http://localhost:15003/v1/clusters/istio-proxy/sidecar~10.248.182.20~productpage-v1-68b86cf77b-2548x.default~default.svc.cluster.local -v 
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 15003 (#0)
> GET /v1/clusters/istio-proxy/sidecar~10.248.182.20~productpage-v1-68b86cf77b-2548x.default~default.svc.cluster.local HTTP/1.1
> Host: localhost:15003
> User-Agent: curl/7.47.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

(And in the other terminal I see the `Handling connection for 15003` message, so the port-forwarding seems to work.)

**Comment by ayj** [comment]
This is likely due to a combination of factors.

1) https://github.com/istio/istio/issues/2554 - slower sidecar proxy startup time in larger clusters. This can be observed by inspecting logs on the productpage's `istio-proxy` container, e.g.

```
[2018-01-24 20:50:53.577][13][warning][config] external/envoy/source/server/listener_manager_impl.cc:448] all dependencies initialized. starting workers
[2018-01-24 20:53:46.115][13][warning][main] external/envoy/source/server/drain_manager_impl.cc:62] shutting down parent after drain
```

Note the ~3 minute delay during start-up. This _should_ be fixed in a more recent version of the proxy. You can try a pre-release build from http://gcsweb.istio.io/gcs/istio-prerelease/daily-build, or wait for 0.5.0 to be released.

```bash
kubectl create -f <(bin/istioctl kube-inject --hub docker.io/jasonayoung --tag 0.5.0-pre20180124-17-29-51 -f samples/bookinfo/kube/bookinfo.yam
```

2) Bad default refresh intervals for xDS.

The default `discoveryRefreshDelay` 1s is too short for any non-demo cluster. `discoveryRefreshDelay` configures how frequently Envoy poll's Pilot discovery API (see refresh_delay_ms description at  https://www.envoyproxy.io/docs/envoy/v1.5.0/api-v1/cluster_manager/cds). Envoy adds random jitter so effective polling interval is randomized between `refresh_delay_ms` and `refresh_delay_ms * 2`.

Every doubling of `discoveryRefreshDelay` more than halves the number of HTTP requests each proxy makes to istio-pilot. 

3) Lack of horizontally scaled `istio-pilot`

The proxy will start to see network errors if a single `istio-pilot` is trying to serve too many requests per second. This can be observed by `exec`ing into the `istio-proxy` container on an injected application pod and running `curl localhost:15000/logging?level=info`.

```
[2018-01-23 22:53:40.606][109][info][upstream] external/envoy/source/common/upstream/cds_subscription.cc:70] cds: fetch failure: network error
[2018-01-23 22:53:40.982][109][info][client] external/envoy/source/common/http/codec_client.cc:23] [C223] connecting
[2018-01-23 22:53:40.983][109][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2018-01-23 22:53:42.219][109][info][client] external/envoy/source/common/http/codec_client.cc:23] [C224] connecting
[2018-01-23 22:53:42.219][109][info][upstream] external/envoy/source/common/upstream/cds_subscription.cc:70] cds: fetch failure: network error
[2018-01-23 22:53:42.939][109][info][client] external/envoy/source/common/http/codec_client.cc:23] [C225] connecting
[2018-01-23 22:53:42.940][109][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2018-01-23 22:53:43.707][109][info][client] external/envoy/source/common/http/codec_client.cc:23] [C226] connecting
[2018-01-23 22:53:43.708][109][info][upstream] external/envoy/source/common/upstream/cds_subscription.cc:70] cds: fetch failure: network error
```

Port exhaustion is also a possibility with under scaled `istio-pilot` and polling based v1 xDS API as the number of injected proxies increases, e.g.

```
root@istio-pilot-55bb7f5d9d-28sgv:/# ss -a | grep TIME-WAIT | wc -l
22359
```

Manually increasing the number of replicas helps alleviate this problem. Ideally the number of relicas could be auto-scaled in proportion to the resource usage and/or cluster size.

```bash
kubectl -n istio-system scale deployment istio-pilot --replicas=8
```

**Comment by ayj** [comment]
The above comment was in response to the original issue. The `istio-proxy-cfg` failures are likely due to #2 and #3 above.

**Comment by sakshigoel12** [comment]
markvincze@ any pending issue?

**Comment by ayj** [comment]
Pilot config caching performance has been improved in 0.6 which should partly address this issue. Closing for now. We should open an new issue if the problem persists with the latest release.
