### ISSUE TITLE
Way to pass the config to kubernetes client which is already built

### ISSUE THREAD

**Issue by vinaysinghbww** [istio/issues#166]
**Is this a BUG or FEATURE REQUEST?:** Feature Request

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**: I didn't find the answer

**Bug:**
Y/N: N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
Kubernates client-go: v5.0.1
istio libraries - v0.4

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml.... no

**What happened**:
I am using kubernetes for container orchestration and istio for routing rules. I already have a kubernetes client built and I was looking for a way to interact with routing rules. I didn't find a convincing way to have a single client which serves both the purpose. I was referring  https://github.com/istio/istio/blob/master/pilot/adapter/config/crd/client.go#L72 to create the istio client and but I can see there is the restClient inside Client struct which is not exported/exposed. 

**What you expected to happen:**
I am finding the way to pass the required config to the client which is already built or vice-versa. 

**How to reproduce it:**
NA

**Feature Request:**
Y

**Describe the feature:**
I am using kubernetes for container orchestration and istio for routing rules. I already have a kubernetes client built and I was looking for a way to interact with routing rules. I didn't find a convincing way to have a single client which serves both the purpose. I was referring  https://github.com/istio/istio/blob/master/pilot/adapter/config/crd/client.go#L72 to create the istio client and but I can see there is the restClient inside Client struct which is not exported/exposed.

**Comment by ayj** [comment]
dup of https://github.com/istio/istio/issues/6084
