### ISSUE TITLE
istio-ingress repeating "no secret needed" message every second

### ISSUE THREAD

**Issue by saturnism** [istio/issues#17]
Not sure why I see this log message continuously..
```
$ kubectl logs -f istio-ingress-.....

I0526 08:27:30.531678       1 ingress.go:120] no secret needed
I0526 08:27:31.532773       1 ingress.go:120] no secret needed
I0526 08:27:32.533969       1 ingress.go:120] no secret needed
I0526 08:27:33.535098       1 ingress.go:120] no secret needed
...
```

**Comment by rshriram** [comment]
cc @ijsnellf

**Comment by GregHanson** [comment]
@rshriram ijsnellf is out for vacation, I am looking into this

**Comment by GregHanson** [comment]
@saturnism did you create istio ingress following the steps  [here](https://istio.io/docs/tasks/installing-istio.html) ?  As of version 0.1.5 ingress is started with a log verbosity setting of 2
```bash
        args: ["proxy", "ingress", "-v", "2"]
```
and that log message should only appear in levels 4 and higher
```bash
		glog.V(4).Info("no secret needed")
```

**Comment by ijsnellf** [comment]
Should have been fixed by https://github.com/istio/pilot/pull/776.
