### ISSUE TITLE
The istio-ingress don't work well,so the bookinfo can't be curl

### ISSUE THREAD

**Issue by sandylss** [istio/issues#173]
**Is this a BUG or FEATURE REQUEST?:**
BUG
**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**:
Yes.I don't find some resolutions.
**Bug:**

Y
**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 
Version: 0.4.0
GitRevision: 24089ea97c8d244493c93b499a666ddf4010b547
GitBranch: 6401744b90b43901b2aa4a8bced33c7bd54ffc13
User: root@cc5c34bbd1ee
GolangVersion: go1.9.1
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Is Istio Auth enabled or not ?**

istio.yaml
**What happened**:
I can't access any service,they seem running success,somelike helloworld or bookinfo,but when I use curl ...  they  show me 

> curl http://$HELLOWORLD_URL/hello
curl: (7) Failed to connect to 172.16.1.87 port 30486: Connection refused

**What you expected to happen:**
I can view the Bookinfo web page.
**How to reproduce it:**
I install istio follow the guide https://istio.io/docs/setup/kubernetes/quick-start.html.
Once,the istio-ingress service kept dying and getting restarted,I follow https://github.com/istio/istio/issues/2336 comment out the statsd option did that for me. 
And,my k8s cluster not support loadbalancer ,so I edit the istio-ingress service replace loadbalancer to nodeport 

> $ kubectl get service -n istio-system 
> NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                            AGE
> grafana         ClusterIP   10.107.183.249   <none>        3000/TCP                                                           1h
> istio-ingress   NodePort    10.111.138.56    <none>        80:31328/TCP,443:30974/TCP                                         3h
> istio-mixer     ClusterIP   10.104.229.113   <none>        9091/TCP,15004/TCP,9093/TCP,9094/TCP,9102/TCP,9125/UDP,42422/TCP   3h
> istio-pilot     ClusterIP   10.108.4.142     <none>        15003/TCP,443/TCP                                                  3h
> prometheus      ClusterIP   10.105.113.255   <none>        9090/TCP                                                           1h
> servicegraph    ClusterIP   10.108.141.35    <none>        8088/TCP                                                           1h
> zipkin          ClusterIP   10.111.75.243    <none>        9411/TCP                                                           1h
> 

Then I follow the https://istio.io/docs/guides/bookinfo.html deploy bookinfo service 

> NAME                                READY     STATUS    RESTARTS   AGE
details-v1-6b87db6ff7-vw29b         2/2       Running   0          3h
productpage-v1-648f66468f-8mgg5     2/2       Running   0          3h
ratings-v1-6844b4646f-6wpl8         2/2       Running   0          3h
reviews-v1-58f9664dcc-4mqf4         2/2       Running   0          3h
reviews-v2-78b4b67c-vb4st           2/2       Running   0          3h
reviews-v3-bcf6495d9-d8l77          2/2       Running   0          3h

It seem running successd,then I use `export GATEWAY_URL=$(kubectl get po -l istio=ingress -n istio-system -o 'jsonpath={.items[0].status.hostIP}'):$(kubectl get svc istio-ingress -n istio-system -o 'jsonpath={.spec.ports[0].nodePort}')
` to determining the ingress IP and Port
I got 

> $ echo $GATEWAY_URL
172.16.1.87:31328

I use `curl -o /dev/null -s -w "%{http_code}\n" http://${GATEWAY_URL}/productpage
` got 

> $ curl -o /dev/null -s -w "%{http_code}\n" http://${GATEWAY_URL}/productpage
> 000
> 

I also point my browser to http://172.16.1.87/productpage to view the Bookinfo web page. It shows Unable to connect  .

I tried many times,but have no idea.
Can someone give me some resolutions?
thank u very very much~

**Comment by sandylss** [comment]
Now,I found the istio-ingress seems don't work well ,the logs like:

> ERROR: logging before flag.Parse: I0127 08:50:19.112661       1 main.go:70] Version root@cc5c34bbd1ee-0.4.0-24089ea97c8d244493c93b499a666ddf4010b547-dirty
ERROR: logging before flag.Parse: I0127 08:50:49.113260       1 main.go:114] Error retrieving availability zone from pilot: Get http://istio-pilot:15003/v1/az/istio-ingress/ingress~~istio-ingress-7df7c46c7-vbw85.istio-system~istio-system.svc.cluster.local: dial tcp: i/o timeout
ERROR: logging before flag.Parse: I0127 08:50:49.113365       1 main.go:124] Proxy role: proxy.Node{Type:"ingress", IPAddress:"", ID:"istio-ingress-7df7c46c7-vbw85.istio-system", Domain:"istio-system.svc.cluster.local"}
ERROR: logging before flag.Parse: I0127 08:50:49.113767       1 main.go:184] Effective config: binaryPath: /usr/local/bin/envoy
configPath: /etc/istio/proxy
connectTimeout: 10.000s
discoveryAddress: istio-pilot:15003
discoveryRefreshDelay: 1.000s
drainDuration: 45.000s
parentShutdownDuration: 60.000s
proxyAdminPort: 15000
serviceCluster: istio-ingress
zipkinAddress: zipkin:9411
ERROR: logging before flag.Parse: I0127 08:50:49.113787       1 main.go:201] Monitored certs: []envoy.CertSource{envoy.CertSource{Directory:"/etc/certs/", Files:[]string{"cert-chain.pem", "key.pem", "root-cert.pem"}}, envoy.CertSource{Directory:"/etc/istio/ingress-certs/", Files:[]string{"tls.crt", "tls.key"}}}
ERROR: logging before flag.Parse: I0127 08:50:49.113988       1 agent.go:164] Starting proxy agent
ERROR: logging before flag.Parse: I0127 08:50:49.114110       1 agent.go:186] Received new config, resetting budget
ERROR: logging before flag.Parse: I0127 08:50:49.114121       1 agent.go:261] Reconciling configuration (budget 10)
ERROR: logging before flag.Parse: I0127 08:50:49.114143       1 agent.go:281] Epoch 0 starting
ERROR: logging before flag.Parse: I0127 08:50:49.114228       1 config.go:49] writing configuration to /etc/istio/proxy/envoy-rev0.json
{
  "listeners": [],
  "lds": {
    "cluster": "lds",
    "refresh_delay_ms": 1000
  },
  "admin": {
    "access_log_path": "/dev/stdout",
    "address": "tcp://127.0.0.1:15000"
  },
  "cluster_manager": {
    "clusters": [
      {
        "name": "rds",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      {
        "name": "lds",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      {
        "name": "zipkin",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://zipkin:9411"
          }
        ]
      }
    ],
    "sds": {
      "cluster": {
        "name": "sds",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      "refresh_delay_ms": 1000
    },
    "cds": {
      "cluster": {
        "name": "cds",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      "refresh_delay_ms": 1000
    }
  },
  "tracing": {
    "http": {
      "driver": {
        "type": "zipkin",
        "config": {
          "collector_cluster": "zipkin",
          "collector_endpoint": "/api/v1/spans"
        }
      }
    }
  }
}ERROR: logging before flag.Parse: I0127 08:50:49.115063       1 watcher.go:270] Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingress --service-node ingress~~istio-ingress-7df7c46c7-vbw85.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189]
[2018-01-27 08:50:49.128][17][warning][main] external/envoy/source/server/server.cc:157] initializing epoch 0 (hot restart version=9.200.16384.256)
[2018-01-27 08:50:49.360][17][warning][main] external/envoy/source/server/server.cc:344] starting main dispatch loop
ERROR: logging before flag.Parse: I0127 08:51:40.538507       1 watcher.go:123] watchFileEvents: "/etc/certs//..1981_27_01_16_51_40.410778961": CREATE
ERROR: logging before flag.Parse: I0127 08:51:40.538556       1 watcher.go:123] watchFileEvents: "/etc/certs//..1981_27_01_16_51_40.410778961": MODIFY|ATTRIB
ERROR: logging before flag.Parse: I0127 08:51:40.538577       1 watcher.go:123] watchFileEvents: "/etc/certs//cert-chain.pem": CREATE
ERROR: logging before flag.Parse: I0127 08:51:40.538634       1 watcher.go:123] watchFileEvents: "/etc/certs//key.pem": CREATE
ERROR: logging before flag.Parse: I0127 08:51:40.538653       1 watcher.go:123] watchFileEvents: "/etc/certs//root-cert.pem": CREATE
ERROR: logging before flag.Parse: I0127 08:51:40.538666       1 watcher.go:123] watchFileEvents: "/etc/certs//..data_tmp": RENAME
ERROR: logging before flag.Parse: I0127 08:51:40.538734       1 watcher.go:123] watchFileEvents: "/etc/certs//..data": CREATE
ERROR: logging before flag.Parse: I0127 08:51:50.538729       1 watcher.go:136] watchFileEvents: notifying
ERROR: logging before flag.Parse: I0127 08:51:50.539079       1 agent.go:186] Received new config, resetting budget
ERROR: logging before flag.Parse: I0127 08:51:50.539093       1 agent.go:261] Reconciling configuration (budget 10)
ERROR: logging before flag.Parse: I0127 08:51:50.539182       1 agent.go:281] Epoch 1 starting
ERROR: logging before flag.Parse: I0127 08:51:50.539224       1 config.go:49] writing configuration to /etc/istio/proxy/envoy-rev1.json
{
  "listeners": [],
  "lds": {
    "cluster": "lds",
    "refresh_delay_ms": 1000
  },
  "admin": {
    "access_log_path": "/dev/stdout",
    "address": "tcp://127.0.0.1:15000"
  },
  "cluster_manager": {
    "clusters": [
      {
        "name": "rds",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      {
        "name": "lds",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      {
        "name": "zipkin",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://zipkin:9411"
          }
        ]
      }
    ],
    "sds": {
      "cluster": {
        "name": "sds",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      "refresh_delay_ms": 1000
    },
    "cds": {
      "cluster": {
        "name": "cds",
        "connect_timeout_ms": 10000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      "refresh_delay_ms": 1000
    }
  },
  "tracing": {
    "http": {
      "driver": {
        "type": "zipkin",
        "config": {
          "collector_cluster": "zipkin",
          "collector_endpoint": "/api/v1/spans"
        }
      }
    }
  }
}ERROR: logging before flag.Parse: I0127 08:51:50.539570       1 watcher.go:270] Envoy command: [-c /etc/istio/proxy/envoy-rev1.json --restart-epoch 1 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingress --service-node ingress~~istio-ingress-7df7c46c7-vbw85.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189]
unable to initialize hot restart: previous envoy process is still initializing

I don't know where I did wrong,can someone help me?

**Comment by zvikaga** [comment]
I'm also facing the same issue. The examples don't work here.
Is there any uesfull input here?
Thanks

**Comment by SUNSAHAR20** [comment]
Even I'm facing the same issue. Is it a bug due to istio-0.5.0? Is there any fix to it. It will be really helpful

**Comment by h4ckroot** [comment]
Same here !

**Comment by ldemailly** [comment]
can you try a TESTONLY matching your OS from
http://gcsweb.istio.io/gcs/istio-prerelease/daily-build/0.6.0-pre20180222-22-57-06/
(make sure to read https://github.com/istio/istio/wiki/Daily-builds#notes )

**Comment by sandylss** [comment]
I finally fix this problem use minikube..... when I use minikube deploy Istio,this problem gone.I don't know why,I guess Istio maybe doesn't support k8s on bare metal.

**Comment by ldemailly** [comment]
if one of you would like to try again with the 0.6.0 release, it would be useful to know what happened

**Comment by fudali113** [comment]
I have a similar problem.
```
[mike@k8s-node0 istio-0.6.0]$ ./bin/istioctl version
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

[mike@k8s-node0 istio-0.6.0]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
[mike@k8s-node0 istio-0.6.0]$ kubectl get pods
NAME                              READY     STATUS    RESTARTS   AGE
details-v1-64b86cd49-fnkw7        1/1       Running   0          1h
productpage-v1-84f77f8747-zk9p2   1/1       Running   0          1h
ratings-v1-5f46655b57-nrlxb       1/1       Running   0          1h
reviews-v1-ff6bdb95b-r248c        1/1       Running   0          1h
reviews-v2-5799558d68-z46mw       1/1       Running   0          1h
reviews-v3-58ff7d665b-7l76c       1/1       Running   0          1h
[mike@k8s-node0 istio-0.6.0]$ kubectl get pods -n istio-system
NAME                                      READY     STATUS    RESTARTS   AGE
istio-ca-59f6dcb7d9-xhdmx                 1/1       Running   0          13h
istio-ingress-779649ff5b-7gwsn            1/1       Running   97         13h
istio-mixer-7f4fd7dff-2ff2l               3/3       Running   0          13h
istio-pilot-5f5f76ddc8-4xgpv              2/2       Running   0          13h
istio-sidecar-injector-7947777478-86lnq   1/1       Running   0          13h
[mike@k8s-node0 istio-0.6.0]$
```

# istio-ingress log:
```
2018-03-14T02:29:34.363461Z	warn	Aborted all epochs
2018-03-14T02:29:34.363500Z	info	Epoch 0: set retry delay to 400ms, budget to 8
2018-03-14T02:29:34.763635Z	info	Reconciling configuration (budget 8)
2018-03-14T02:29:34.763717Z	info	Epoch 0 starting
2018-03-14T02:29:34.764369Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingress --service-node ingress~~istio-ingress-779649ff5b-7gwsn.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 -l info]
[2018-03-14 02:29:34.776][20][info][main] external/envoy/source/server/server.cc:184] initializing epoch 0 (hot restart version=9.200.16384.256.options=capacity=16384, num_slots=8209 hash=228984379728933363)
[2018-03-14 02:29:34.779][20][info][config] external/envoy/source/server/configuration_impl.cc:52] loading 0 listener(s)
[2018-03-14 02:29:34.779][20][info][config] external/envoy/source/server/configuration_impl.cc:92] loading tracing configuration
[2018-03-14 02:29:34.779][20][info][config] external/envoy/source/server/configuration_impl.cc:106]   loading tracing driver: envoy.zipkin
[2018-03-14 02:29:34.779][20][info][config] external/envoy/source/server/configuration_impl.cc:119] loading stats sink configuration
[2018-03-14 02:29:34.779][20][critical][main] external/envoy/source/server/server.cc:71] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': malformed IP address: istio-mixer
2018-03-14T02:29:34.780967Z	warn	Epoch 0 terminated with an error: exit status 1
2018-03-14T02:29:34.780987Z	warn	Aborted all epochs
2018-03-14T02:29:34.781036Z	info	Epoch 0: set retry delay to 800ms, budget to 7
2018-03-14T02:29:35.581162Z	info	Reconciling configuration (budget 7)
2018-03-14T02:29:35.581233Z	info	Epoch 0 starting
2018-03-14T02:29:35.583820Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingress --service-node ingress~~istio-ingress-779649ff5b-7gwsn.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 -l info]
[2018-03-14 02:29:35.598][24][info][main] external/envoy/source/server/server.cc:184] initializing epoch 0 (hot restart version=9.200.16384.256.options=capacity=16384, num_slots=8209 hash=228984379728933363)
[2018-03-14 02:29:35.601][24][info][config] external/envoy/source/server/configuration_impl.cc:52] loading 0 listener(s)
[2018-03-14 02:29:35.601][24][info][config] external/envoy/source/server/configuration_impl.cc:92] loading tracing configuration
[2018-03-14 02:29:35.601][24][info][config] external/envoy/source/server/configuration_impl.cc:106]   loading tracing driver: envoy.zipkin
[2018-03-14 02:29:35.601][24][info][config] external/envoy/source/server/configuration_impl.cc:119] loading stats sink configuration
[2018-03-14 02:29:35.601][24][critical][main] external/envoy/source/server/server.cc:71] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': malformed IP address: istio-mixer
2018-03-14T02:29:35.603586Z	warn	Epoch 0 terminated with an error: exit status 1

```

Could it be kube-dns?
@ldemailly

**Comment by ldemailly** [comment]
```
[2018-03-14 03:04:41.859][36][critical][main] external/envoy/source/server/server.cc:71] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': malformed IP address: istio-mixer
```
not sure how that happens - @kuat ?

**Comment by fudali113** [comment]
![image](https://user-images.githubusercontent.com/16189465/37387263-ae60f1b6-2796-11e8-9b22-98f638d777e5.png)
I don't have that file.

**Comment by kyessenov** [comment]
This file is auto-generated. Can you ssh into failed pods and extract that file?
cc @nmittler can we bump the log level for the agent to print the config? it should be printed the logs by default.

**Comment by fudali113** [comment]
I don't quite follow you.
Is there any way to solve my problem?
@kyessenov @ldemailly

**Comment by ldemailly** [comment]
we are trying to understand how did you end up with an envoy boostrap config that doesn’t parse.

**Comment by kyessenov** [comment]
@costinm how come the bootstrap config is missing? is there some hardcoded config file and the debug message is wrong?

**Comment by fudali113** [comment]
start log：
```
[mike@k8s-node0 istio-0.6.0]$ kubectl apply -f install/kubernetes/istio.yaml
namespace "istio-system" created
clusterrole "istio-pilot-istio-system" created
clusterrole "istio-sidecar-injector-istio-system" created
clusterrole "istio-mixer-istio-system" created
clusterrole "istio-ca-istio-system" created
clusterrole "istio-sidecar-istio-system" created
clusterrolebinding "istio-pilot-admin-role-binding-istio-system" created
clusterrolebinding "istio-sidecar-injector-admin-role-binding-istio-system" created
clusterrolebinding "istio-ca-role-binding-istio-system" created
clusterrolebinding "istio-ingress-admin-role-binding-istio-system" created
clusterrolebinding "istio-sidecar-role-binding-istio-system" created
clusterrolebinding "istio-mixer-admin-role-binding-istio-system" created
configmap "istio-mixer" created
service "istio-mixer" created
serviceaccount "istio-mixer-service-account" created
deployment "istio-mixer" created
customresourcedefinition "rules.config.istio.io" created
customresourcedefinition "attributemanifests.config.istio.io" created
customresourcedefinition "circonuses.config.istio.io" created
customresourcedefinition "deniers.config.istio.io" created
customresourcedefinition "fluentds.config.istio.io" created
customresourcedefinition "kubernetesenvs.config.istio.io" created
customresourcedefinition "listcheckers.config.istio.io" created
customresourcedefinition "memquotas.config.istio.io" created
customresourcedefinition "noops.config.istio.io" created
customresourcedefinition "opas.config.istio.io" created
customresourcedefinition "prometheuses.config.istio.io" created
customresourcedefinition "rbacs.config.istio.io" created
customresourcedefinition "servicecontrols.config.istio.io" created
customresourcedefinition "solarwindses.config.istio.io" created
customresourcedefinition "stackdrivers.config.istio.io" created
customresourcedefinition "statsds.config.istio.io" created
customresourcedefinition "stdios.config.istio.io" created
customresourcedefinition "apikeys.config.istio.io" created
customresourcedefinition "authorizations.config.istio.io" created
customresourcedefinition "checknothings.config.istio.io" created
customresourcedefinition "kuberneteses.config.istio.io" created
customresourcedefinition "listentries.config.istio.io" created
customresourcedefinition "logentries.config.istio.io" created
customresourcedefinition "metrics.config.istio.io" created
customresourcedefinition "quotas.config.istio.io" created
customresourcedefinition "reportnothings.config.istio.io" created
customresourcedefinition "servicecontrolreports.config.istio.io" created
customresourcedefinition "tracespans.config.istio.io" created
customresourcedefinition "serviceroles.config.istio.io" created
customresourcedefinition "servicerolebindings.config.istio.io" created
configmap "istio" created
customresourcedefinition "destinationpolicies.config.istio.io" created
customresourcedefinition "egressrules.config.istio.io" created
customresourcedefinition "routerules.config.istio.io" created
customresourcedefinition "v1alpha2routerules.config.istio.io" created
customresourcedefinition "destinationrules.config.istio.io" created
customresourcedefinition "externalservices.config.istio.io" created
service "istio-pilot" created
serviceaccount "istio-pilot-service-account" created
deployment "istio-pilot" created
service "istio-ingress" created
serviceaccount "istio-ingress-service-account" created
deployment "istio-ingress" created
serviceaccount "istio-ca-service-account" created
deployment "istio-ca" created
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=attributemanifest
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=attributemanifest
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=stdio
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=logentry
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=rule
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=prometheus
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=rule
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=rule
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=kubernetesenv
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=rule
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=kubernetes
```
delete log：
```
[mike@k8s-node0 istio-0.6.0]$ kubectl delete -f install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml
service "istio-sidecar-injector" deleted
serviceaccount "istio-sidecar-injector-service-account" deleted
deployment "istio-sidecar-injector" deleted
mutatingwebhookconfiguration "istio-sidecar-injector" deleted
[mike@k8s-node0 istio-0.6.0]$ kubectl delete -f install/kubernetes/istio.yaml
namespace "istio-system" deleted
clusterrole "istio-pilot-istio-system" deleted
clusterrole "istio-sidecar-injector-istio-system" deleted
clusterrole "istio-mixer-istio-system" deleted
clusterrole "istio-ca-istio-system" deleted
clusterrole "istio-sidecar-istio-system" deleted
clusterrolebinding "istio-pilot-admin-role-binding-istio-system" deleted
clusterrolebinding "istio-sidecar-injector-admin-role-binding-istio-system" deleted
clusterrolebinding "istio-ca-role-binding-istio-system" deleted
clusterrolebinding "istio-ingress-admin-role-binding-istio-system" deleted
clusterrolebinding "istio-sidecar-role-binding-istio-system" deleted
clusterrolebinding "istio-mixer-admin-role-binding-istio-system" deleted
configmap "istio-mixer" deleted
service "istio-mixer" deleted
serviceaccount "istio-mixer-service-account" deleted
deployment "istio-mixer" deleted
customresourcedefinition "rules.config.istio.io" deleted
customresourcedefinition "attributemanifests.config.istio.io" deleted
customresourcedefinition "circonuses.config.istio.io" deleted
customresourcedefinition "deniers.config.istio.io" deleted
customresourcedefinition "fluentds.config.istio.io" deleted
customresourcedefinition "kubernetesenvs.config.istio.io" deleted
customresourcedefinition "listcheckers.config.istio.io" deleted
customresourcedefinition "memquotas.config.istio.io" deleted
customresourcedefinition "noops.config.istio.io" deleted
customresourcedefinition "opas.config.istio.io" deleted
customresourcedefinition "prometheuses.config.istio.io" deleted
customresourcedefinition "rbacs.config.istio.io" deleted
customresourcedefinition "servicecontrols.config.istio.io" deleted
customresourcedefinition "solarwindses.config.istio.io" deleted
customresourcedefinition "stackdrivers.config.istio.io" deleted
customresourcedefinition "statsds.config.istio.io" deleted
customresourcedefinition "stdios.config.istio.io" deleted
customresourcedefinition "apikeys.config.istio.io" deleted
customresourcedefinition "authorizations.config.istio.io" deleted
customresourcedefinition "checknothings.config.istio.io" deleted
customresourcedefinition "kuberneteses.config.istio.io" deleted
customresourcedefinition "listentries.config.istio.io" deleted
customresourcedefinition "logentries.config.istio.io" deleted
customresourcedefinition "metrics.config.istio.io" deleted
customresourcedefinition "quotas.config.istio.io" deleted
customresourcedefinition "reportnothings.config.istio.io" deleted
customresourcedefinition "servicecontrolreports.config.istio.io" deleted
customresourcedefinition "tracespans.config.istio.io" deleted
customresourcedefinition "serviceroles.config.istio.io" deleted
customresourcedefinition "servicerolebindings.config.istio.io" deleted
configmap "istio" deleted
customresourcedefinition "destinationpolicies.config.istio.io" deleted
customresourcedefinition "egressrules.config.istio.io" deleted
customresourcedefinition "routerules.config.istio.io" deleted
customresourcedefinition "v1alpha2routerules.config.istio.io" deleted
customresourcedefinition "destinationrules.config.istio.io" deleted
customresourcedefinition "externalservices.config.istio.io" deleted
service "istio-pilot" deleted
serviceaccount "istio-pilot-service-account" deleted
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete attributemanifests.config.istio.io istioproxy)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete attributemanifests.config.istio.io kubernetes)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete stdios.config.istio.io handler)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete logentries.config.istio.io accesslog)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete rules.config.istio.io stdio)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete metrics.config.istio.io requestcount)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete metrics.config.istio.io requestduration)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete metrics.config.istio.io requestsize)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete metrics.config.istio.io responsesize)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete metrics.config.istio.io tcpbytesent)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete metrics.config.istio.io tcpbytereceived)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete prometheuses.config.istio.io handler)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete rules.config.istio.io promhttp)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete rules.config.istio.io promtcp)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete kubernetesenvs.config.istio.io handler)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete rules.config.istio.io kubeattrgenrulerule)
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": the server could not find the requested resource (delete kuberneteses.config.istio.io attributes)
Error from server (NotFound): error when stopping "install/kubernetes/istio.yaml": deployments.extensions "istio-pilot" not found
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": services "istio-ingress" not found
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": serviceaccounts "istio-ingress-service-account" not found
Error from server (NotFound): error when stopping "install/kubernetes/istio.yaml": deployments.extensions "istio-ingress" not found
Error from server (NotFound): error when deleting "install/kubernetes/istio.yaml": serviceaccounts "istio-ca-service-account" not found
Error from server (NotFound): error when stopping "install/kubernetes/istio.yaml": deployments.extensions "istio-ca" not found
```

I started the log with some errors, could this be the reason?

**Comment by fudali113** [comment]
I have solved my problem because I did not properly configure my kube-dns service.
@ldemailly @kyessenov

**Comment by hank-cp** [comment]
@fudali113 Could you please explain a little bit more what your problem with kube-dns? Facing the similar problem...

**Comment by sandylss** [comment]
@fudali113 hi，how to properly configure the kube-dns servuce? thank u~

**Comment by abhyuditjain** [comment]
@sandylss Did you find the solution? I am stuck on the same.
