### ISSUE TITLE
Expose option to specify concurrency (no. of threads) for envoy through pilot agent

### ISSUE THREAD

**Issue by mdhume** [istio/issues#175]
**Is this a BUG or FEATURE REQUEST?:** Feature Request

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**: Yes

**Feature Request:**
Y

**Describe the feature:** 
From our observations we have seen that even when limits are added to the envoy sidecar in K8s, the number of threads it spawns is equal to the number of cores on the base host rather than the number of cores allocated to the container.

Please expose the `concurrency` option provided by envoy through the proxy agent to allow us to tune that number.
https://www.envoyproxy.io/docs/envoy/latest/operations/cli.html?highlight=concurrency#cmdoption-concurrency

**Comment by myidpt** [comment]
https://github.com/istio/istio/pull/3065
https://github.com/istio/api/pull/341

**Comment by andraxylia** [comment]
Fixed.

**Comment by ldemailly** [comment]
I would like to hear some results on the effect of this. thanks.
