### ISSUE TITLE
Error in istio.io/api/mixer/v1/config/fixed_cfg.pb.go: unused import.

### ISSUE THREAD

**Issue by metacosm** [istio/issues#180]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What happened**:
Trying to process the API, got the following error:

istio.io/api/mixer/v1/config/fixed_cfg.pb.go:22:8: imported and not used: "istio.io/api/vendor/github.com/golang/protobuf/ptypes/struct" as google_protobuf

**What you expected to happen:**
No error reporting an unused import :)

**How to reproduce it:**
Import `fixed_cfg.pb.go` in a go file and try to `go build`.

**Comment by douglas-reid** [comment]
This has been fixed (see: https://github.com/istio/api/blob/master/mixer/v1/config/fixed_cfg.pb.go).
