### ISSUE TITLE
Missing webhook-patch-ca-bundle.sh

### ISSUE THREAD

**Issue by chrisgoffinet** [istio/issues#183]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**:
Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
kubectl version
```

**Is Istio Auth enabled or not ?**
istio.yaml

**What happened**:
When going through the guide about automatic sidecar injection, it references `webhook-patch-ca-bundle.sh` to generate a CA. This is missing in the latest `0.5` release, but it's in master.

**What you expected to happen:**

**How to reproduce it:**

**Feature Request:**
N

**Describe the feature:**

**Comment by ayj** [comment]
dup of https://github.com/istio/istio/issues/3030
