### ISSUE TITLE
Unable to setup automatic sidecar injection. Webhook cannot read PEM data

### ISSUE THREAD

**Issue by jntakpe** [istio/issues#184]
**Is this a BUG or FEATURE REQUEST?:**
BUG
**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**:
yes
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version : 0.5.0
kubectl version : 1.9.0
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
Not enabled, just istio.yaml

**What happened**:
Sidecar injection fails with the message : Error: failed to create injection webhook tls: failed to find any PEM data in certificate input

**What you expected to happen:**
Sidecar injection should be sucessful since is caBundle is set

**How to reproduce it:**
On OSX : 
Start minikube v0.25
Apply istio.yaml
Generate cert with : `./install/kubernetes/webhook-create-signed-cert.sh \
    --service istio-sidecar-injector \
    --namespace istio-system \
    --secret sidecar-injector-certs`
Apply configmap : `kubectl apply -f install/kubernetes/istio-sidecar-injector-configmap-release.yaml`
Add caBundle : `cat install/kubernetes/istio-sidecar-injector.yaml | \
     ./install/kubernetes/webhook-patch-ca-bundle.sh > \
     install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml`
Apply sidecar : `kubectl apply -f install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml`

**Feature Request:**
N

**Describe the feature:**

**Comment by ayj** [comment]
Minikube doesn't start the cert controller manage by default. @cmluciano recently updated the prerequisite instructions for minikube [here](https://istio.io/docs/setup/kubernetes/sidecar-injection.html#minikube). 

There could also be an race issue with cert approval vs. signing that should be fixed by https://github.com/istio/istio/pull/3123.

**Comment by zerbitx** [comment]
I'm having the same issue w/out minikube.  Using docker for mac edge w/kubernetes.

istioctl: 0.5.1
kubectl: 1.9.2

```
kubectl create -f install/kubernetes/istio.yaml

./install/kubernetes/webhook-create-signed-cert.sh \
    --service istio-sidecar-injector \
    --namespace istio-system \
    --secret sidecar-injector-certs

kubectl apply -f install/kubernetes/istio-sidecar-injector-configmap-release.yaml

kubectl label namespace default istio-injection=enabled

kubectl apply -f install/kubernetes/addons/prometheus.yaml

istioctl create -f telemetry/prom_telemetry.yaml

istioctl create -f telemetry/tcp_telemetry.yaml

kubectl apply -f install/kubernetes/addons/grafana.yaml

kubectl apply -f install/kubernetes/addons/zipkin.yaml

cat install/kubernetes/istio-sidecar-injector.yaml | \
     ./install/kubernetes/webhook-patch-ca-bundle.sh > \
     install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml

kubectl apply -f install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml

kubectl apply -f samples/bookinfo/kube/bookinfo.yaml
```
All of this outputs:
```
namespace "istio-system" created
clusterrole "istio-pilot-istio-system" created
clusterrole "istio-sidecar-injector-istio-system" created
clusterrole "istio-mixer-istio-system" created
clusterrole "istio-ca-istio-system" created
clusterrole "istio-sidecar-istio-system" created
clusterrolebinding "istio-pilot-admin-role-binding-istio-system" created
clusterrolebinding "istio-sidecar-injector-admin-role-binding-istio-system" created
clusterrolebinding "istio-ca-role-binding-istio-system" created
clusterrolebinding "istio-ingress-admin-role-binding-istio-system" created
clusterrolebinding "istio-sidecar-role-binding-istio-system" created
clusterrolebinding "istio-mixer-admin-role-binding-istio-system" created
configmap "istio-mixer" created
service "istio-mixer" created
serviceaccount "istio-mixer-service-account" created
deployment "istio-mixer" created
customresourcedefinition "rules.config.istio.io" created
customresourcedefinition "attributemanifests.config.istio.io" created
customresourcedefinition "circonuses.config.istio.io" created
customresourcedefinition "deniers.config.istio.io" created
customresourcedefinition "fluentds.config.istio.io" created
customresourcedefinition "kubernetesenvs.config.istio.io" created
customresourcedefinition "listcheckers.config.istio.io" created
customresourcedefinition "memquotas.config.istio.io" created
customresourcedefinition "noops.config.istio.io" created
customresourcedefinition "opas.config.istio.io" created
customresourcedefinition "prometheuses.config.istio.io" created
customresourcedefinition "rbacs.config.istio.io" created
customresourcedefinition "servicecontrols.config.istio.io" created
customresourcedefinition "stackdrivers.config.istio.io" created
customresourcedefinition "statsds.config.istio.io" created
customresourcedefinition "stdios.config.istio.io" created
customresourcedefinition "apikeies.config.istio.io" created
customresourcedefinition "authorizations.config.istio.io" created
customresourcedefinition "checknothings.config.istio.io" created
customresourcedefinition "kuberneteses.config.istio.io" created
customresourcedefinition "listentries.config.istio.io" created
customresourcedefinition "logentries.config.istio.io" created
customresourcedefinition "metrics.config.istio.io" created
customresourcedefinition "quotas.config.istio.io" created
customresourcedefinition "reportnothings.config.istio.io" created
customresourcedefinition "servicecontrolreports.config.istio.io" created
customresourcedefinition "tracespans.config.istio.io" created
customresourcedefinition "serviceroles.config.istio.io" created
customresourcedefinition "servicerolebindings.config.istio.io" created
attributemanifest "istioproxy" created
attributemanifest "kubernetes" created
stdio "handler" created
logentry "accesslog" created
rule "stdio" created
metric "requestcount" created
metric "requestduration" created
metric "requestsize" created
metric "responsesize" created
metric "tcpbytesent" created
metric "tcpbytereceived" created
prometheus "handler" created
rule "promhttp" created
rule "promtcp" created
kubernetesenv "handler" created
rule "kubeattrgenrulerule" created
kubernetes "attributes" created
configmap "istio" created
customresourcedefinition "destinationpolicies.config.istio.io" created
customresourcedefinition "egressrules.config.istio.io" created
customresourcedefinition "routerules.config.istio.io" created
service "istio-pilot" created
serviceaccount "istio-pilot-service-account" created
deployment "istio-pilot" created
service "istio-ingress" created
serviceaccount "istio-ingress-service-account" created
deployment "istio-ingress" created
serviceaccount "istio-ca-service-account" created
deployment "istio-ca" created
creating certs in tmpdir /var/folders/8j/xqpb_0rd46bf9gqphnnycsl127pysd/T/tmp.NM0N6CWw
Generating RSA private key, 2048 bit long modulus
......+++
...................................................................................................................+++
e is 65537 (0x10001)
certificatesigningrequest "istio-sidecar-injector.istio-system" deleted
certificatesigningrequest "istio-sidecar-injector.istio-system" created
NAME                                  AGE         REQUESTOR            CONDITION
istio-sidecar-injector.istio-system   <invalid>   docker-for-desktop   Pending
certificatesigningrequest "istio-sidecar-injector.istio-system" approved
secret "sidecar-injector-certs" created
configmap "istio-inject" created
namespace "default" not labeled
configmap "prometheus" created
service "prometheus" created
deployment "prometheus" created
serviceaccount "prometheus" created
clusterrole "prometheus" configured
clusterrolebinding "prometheus" configured
Created config metric/istio-system/doublerequestcount at revision 101163
Created config prometheus/istio-system/doublehandler at revision 101164
Created config rule/istio-system/doubleprom at revision 101165
Created config logentry/istio-system/newlog at revision 101166
Created config stdio/istio-system/newhandler at revision 101167
Created config rule/istio-system/newlogstdio at revision 101168
Created config metric/default/mongosentbytes at revision 101169
Created config metric/default/mongoreceivedbytes at revision 101170
Created config prometheus/default/mongohandler at revision 101171
Created config rule/default/mongoprom at revision 101172
service "grafana" created
deployment "grafana" created
deployment "zipkin" created
service "zipkin" created
service "istio-sidecar-injector" created
serviceaccount "istio-sidecar-injector-service-account" created
deployment "istio-sidecar-injector" created
mutatingwebhookconfiguration "istio-sidecar-injector" configured
service "details" created
deployment "details-v1" created
service "ratings" created
deployment "ratings-v1" created
service "reviews" created
deployment "reviews-v1" created
deployment "reviews-v2" created
deployment "reviews-v3" created
service "productpage" created
deployment "productpage-v1" created
ingress "gateway" created
Created config route-rule/default/productpage-default at revision 101311
Created config route-rule/default/reviews-default at revision 101313
Created config route-rule/default/ratings-default at revision 101315
Created config route-rule/default/details-default at revision 101316
```
This all seems to run without error, but each of the pods has 1/1 ready. Killing any of them comes back up with 1/1 ready, even with the namespace showing injection enabled.

**Comment by ayj** [comment]
You could verify the sidecar-injector pod is running and also the api-server logs for webhook errors. You might also want to configure the webhook for fail-close to avoid pods being created before the webhook is ready. Its a one-line change to the registration yaml. See https://github.com/istio/istio/pull/3724 or the snippet below. 

```yaml
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail                          # Add this line
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
```

**Comment by zerbitx** [comment]
Thanks for the quick reply.  I made the change to istio-sidecar-injector.yaml so that it would make it into the -with-ca-bundle version and applied.  I'm not seeing any difference.  I'm not sure which apiserver logs you're referring to.  The the injector seems to only be logging the contents of its configMap, the productpage logs nothing and all the other pods reviews/details etc start up fine with no errors in the log.  

_I should mention too, that using the "manual sidecar injection" works fine for me, and when running the  full set of commands I do a delete -f on the bookinfo.yaml and istio.yaml to start completely over each time._

**Comment by ayj** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster. You'll need to find the docker container running the k8s api-server and view the logs per the linked instructions.

**Comment by emmayang** [comment]
Same issue here, only manual injection works, and nothing happened with auto injection.

**Comment by ayj** [comment]
cc @yusuoh

**Comment by hobbytp** [comment]
I meet the same issue with k8s 1.9.3 and istio 0.7.1, I install istio by using "mutual TLS authentication" and install the sidecar injector webhook to try to enable auto injection. I can manually inject and successful, but there is not any error when I deploy service to namespace with istio-injection=enabled, but the pod number always equal 1


bash-4.1$ kubectl get pods -n istio-system
NAME                                     READY     STATUS    RESTARTS   AGE
istio-ca-86f55cc46f-pj4v4                1/1       Running   0          3h
istio-ingress-868d5f978b-zgncw           1/1       Running   0          3h
istio-mixer-65dc5549d6-nvwxz             3/3       Running   0          3h
istio-pilot-657cb5ddf7-zv4mb             2/2       Running   1          3h
istio-sidecar-injector-5b8c78fd6-nrbcw   1/1       Running   0          1h

----
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: 2018-04-12T12:36:48Z
  labels:
    istio-injection: enabled
  name: my-ns
  resourceVersion: "22734"
  selfLink: /api/v1/namespaces/nrf-ns
  uid: 2ad9d390-3e4e-11e8-a85f-005056073e98
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
----

Anything I can do to do more trouble shooting or collect info?

Thanks

**Comment by ayj** [comment]
Verify the `MutatingAdmissionWebhook` plugin is enabled per https://istio.io/docs/setup/kubernetes/quick-start.html.

**Comment by dotw** [comment]
@ayj thanks. this does work.

**Comment by rahulm95** [comment]
Same issue here. Manual injection is working completely fine whereas automatic isn't. FYI, already done this "failurePolicy: Fail"

**Comment by dreadbird** [comment]
@rahulm95  I have resovle the problem.
Tks for @ayj 's help.
The k8s do not enable the "MutatingAdmissionWebhook"  plugin by default.
You can verify the "admission-control" as flow:
`kubectl describe pod k8s-master-1 -n kube-system | grep admission-control
`
and find the plugin:
`--admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,PodSecurityPolicy,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
`

**Comment by sgandon** [comment]
using docker for mac this does not work out of the box.
I found the solution here https://forums.docker.com/t/modifying-the-apiserver-on-kubernetes-on-docker/45857/4
Basically you need to modify the kubernets setup like this.
```
screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
        ### sometimes you may have to press enter twice to have the prompt 
vi /etc/kubernetes/manifests/kube-apiserver.yaml
         ### add ,MutatingAdmissionWebhook,ValidatingAdmissionWebhook to the admission-control parameter, save it of course
```
And restart docker/kubernetes, after the auto injection works like a charm.
