### ISSUE TITLE
Document, test and improve "chained" ingress

### ISSUE THREAD

**Issue by costinm** [istio/issues#19]
In a multi-cluster environment, or if CDNs or other infrastructure is required, istio ingress
may be behind another L7 load balancer, which may handle TLS and route to a region/cluster
running istio.

The LB will update X-Forwarded-For, X-Forwarded-Proto - and possibly other headers in 
case of TLS-client authentication.

In this mode, the istio ingress should only accept traffic from the frontend (no external IP),
 - or should have a whitelist or other mean to identify traffic from the front load
 balancer ( so the injected attributes are accepted only from the front load balancer, 
and filtered out/rejected if they are sent by an attacker)

XFF is most common, and each load balancer has a number of extensions. For examples
if Envoy is used as a global/front load balancer it may use  x-envoy-external-address and
set other headers https://lyft.github.io/envoy/docs/configuration/http_conn_man/headers.html
Haproxy defines a number of TLS-related headers http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

**Comment by therc** [comment]
On a related note: how are proxies like Google's [Identity-Aware Proxy](https://cloud.google.com/iap/) or bitly's [oauth2_proxy](https://github.com/bitly/oauth2_proxy) supposed to be chained?

**Comment by kyessenov** [comment]
IAP proxy is a different use case. I think with regards to platform-provided proxy like GKE ingress controller, chaining them is a common use-case and as long as the proxy pass the origin information through headers, we should be ok to collect it in Istio. 

IAP proxy or any other single-purpose proxy can be set-up between GKE ingress and Istio ingress as a proxy pool deployment with manual configuration to pass-through requests to istio-ingress service. Again, the origin information must be preserved by this proxy.

**Comment by costinm** [comment]
IAP is a bit different - it may also use X-Goog-Authenticated-User-JWT, which is a JWT signed by 
IAP, adding an extra layer of protection. But AFAIK it's only available in some environments.
The critical part is accepting headers from "trusted" chained proxies, and rejecting headers from external users - ideally all components, including chained proxies, would use authenticated TLS, like 
istio auth enables, which will have a similar benefit. 

In general, the process for chaining IAP and IAP-like proxies would be similar - istio-ingress and the other components will need to know the list of injected headers, and have some way to verify the request is from the trusted proxy. 

In some cases it may be possible to chain IAP-like proxies behind Istio-ingress - it depends
a lot on whether you accept TLS-client cert authentication, and where you want to terminate 
the original TLS cert.

**Comment by ldemailly** [comment]
Issue moved to [istio/istio #467](https://github.com/istio/istio/issues/467) via [**ZenHub**](https://www.zenhub.com/)
