### ISSUE TITLE
Confusing Docs on disabling automatic injection

### ISSUE THREAD

**Issue by rlguarino** [istio/issues#192]
**Is this a BUG or FEATURE REQUEST?:**

REQUEST

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**:
Yes
**Bug:**
N

**Describe the feature:**
There should be an example of how to disable automatic injection on the docs [here](https://istio.io/docs/setup/kubernetes/sidecar-injection.html).

A quick example of a simple deployment with the annotation set would be wonderful.

It doesn't help that the 0.5 tag uses the annotations set on the deployment instead of the pod.

**Comment by ayj** [comment]
> It doesn't help that the 0.5 tag uses the annotations set on the deployment instead of the pod

I found one instance of deployment-level annotation in master (see https://github.com/istio/istio/pull/3664). The rest should have been fixed already.
