### ISSUE TITLE
Side container fails when running consul and ereka samples

### ISSUE THREAD

**Issue by kolobok01** [istio/issues#193]
Looks like sidecar manifest that include in samples for consul and eureka is broken
image: docker.io/istio/proxy_init:0.5.0 -exited
image: docker.io/istio/proxy_debug:0.5.0 - running
Tested on ubuntu 16.04 and macOS 
Steps to replicate . 

1. https://istio.io/docs/setup/consul/quick-start.html (all containers are healthy  -- pilot is running)
2. docker-compose -f samples/bookinfo/consul/bookinfo.yaml up -d (all containers are healthy)
3. docker-compose -f samples/bookinfo/consul/bookinfo.sidecars.yaml up -d (exited with no logs)
4. Force docker start xxxxx on exited conteiner out `failed with iptables: Chain already exists.`

Is there anything i am missing from quick-start ?

**Comment by kolobok01** [comment]
incorrect location

**Comment by Xiphin** [comment]
@kolobok01 I met the same issue. How did you fix it?

**Comment by kolobok01** [comment]
@Xiphin  https://github.com/istio/istio/issues/3403
