### ISSUE TITLE
prometheus.yaml creates service account in default namespace, should be istio-system?

### ISSUE THREAD

**Issue by saturnism** [istio/issues#204]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.5.1
GitRevision: 30acfe6528107ea333543309095659b93364b30d
User: root@2e4a18076b04
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?** istio.yaml, no auth

**What happened**: Tried to install promtheus.yaml, but the prometheus pod never appears. After trouble shooting the replicaset, it appears that service account `prometheus` was not found.

**What you expected to happen:** Prometheus pod starts properly.  Service account and cluster role binding in `prometheus.yaml` has no namespace defined, thus the deployment/replicaset failed to find the service account.

**How to reproduce it:** `kubectl apply -f prometheus.yaml` in the addons directory

**Feature Request:** N

**Describe the feature:** N/A

**Comment by nmnellis** [comment]
Added the fix here: https://github.com/istio/istio/pull/3478

**Comment by linsun** [comment]
@hklai and team thanks much for getting 0.5.1 out!  could we create a small release note for it?  i’d like to document the istio dashboard issue

**Comment by hklai** [comment]
@linsun Please use https://github.com/istio/istio/wiki/v0.5.1

**Comment by samkreter** [comment]
Just ran into this same problem following tutorial at https://istio.io/docs/tasks/telemetry/metrics-logs.html
