### ISSUE TITLE
istioctl inject defaults to EnableCoreDump=true, requires privileged istio-init

### ISSUE THREAD

**Issue by steffengy** [istio/issues#209]
istioctl inject defaults to EnableCoreDump = true,
which also requires privileged = true, so you'd need to pass --coreDump false.
(Not sure if that's also an issue when using initializers for injection)

**Comment by ldemailly** [comment]
cc @linsun

**Comment by ldemailly** [comment]
I guess we could also change the core dump default in istioctl and the injector to false; to match the new tied down setup of 0.5 ?

cc @ayj

**Comment by ayj** [comment]
It seems reasonable to switch core dump default to disabled in `kube-inject`. The release sidecar configuration template already excludes core dumps w/privileged=true (see https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-sidecar-injector-configmap-release.yaml.tmpl)

**Comment by cmluciano** [comment]
This is fixed with https://github.com/istio/istio/pull/3010
