### ISSUE TITLE
0.5.1 mixer memory leak under certain conditions

### ISSUE THREAD

**Issue by alexkoturanov** [istio/issues#210]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl 0.5.1
kubectl 1.9.3
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
No - used istio.yaml

**What happened**:
increasing memory usage for mixer (in GB) under load
![screenshot-koturano-02-15-18-at-11 33-am](https://user-images.githubusercontent.com/36204901/36277998-50747974-1247-11e8-85fc-10beacc8680c.PNG)

I have one mixer pod that is taking reports from 9 ingresses and 9 sidecar proxies.

Surprisingly, the problem went away after restaring the load test a couple of times.

See the attached screenshot - memory usage is ok and there is no report drops for the same load (3k req/sec)
![screenshot-koturano-02-15-18-at-11 46-am](https://user-images.githubusercontent.com/36204901/36278238-16693f16-1248-11e8-8ee2-895f560d7339.PNG)
![screenshot-koturano-02-15-18-at-11 50-am](https://user-images.githubusercontent.com/36204901/36278242-18677c38-1248-11e8-88ec-99a62aec5310.PNG)

**What you expected to happen:**
Mixer memory is stable

**How to reproduce it:**
the issue seems to be intermittent, see my description and screenshots at:
https://groups.google.com/forum/#!topic/istio-users/0er0BegsKvQ%5B1-25%5D

**Feature Request:**
N

**Describe the feature:**
n/a

**Comment by mandarjog** [comment]
note: @ldemailly @jnativio

**Comment by mandarjog** [comment]
Issue moved to [istio/istio #3531](https://github.com/istio/istio/issues/3531) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jnativio** [comment]
The behavior I saw in my environment is somewhat different. There is a performance regression on the mixer when installed with the default configuration. For the workload I use it impacted the throughput/response time in more than 50%. By disabling the Policy Checks, the mixer returns to normal (compared to 0.5.0), but starts using huge amount of memory.

![image](https://user-images.githubusercontent.com/18554027/36312621-1da970c4-12fd-11e8-831c-dc6a7b997aec.png)
