### ISSUE TITLE
Prometheus service account for 0.5.1 is broken

### ISSUE THREAD

**Issue by joshuajorel** [istio/issues#218]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: Y

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.5.1
GitRevision: 30acfe6528107ea333543309095659b93364b30d
User: root@2e4a18076b04
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-12-06T20:03:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
No.

**What happened**: 
The prometheus service account definition in `install/kubernetes/addons/prometheus.yaml` does not have the namespace definition. So when installing other components i.e. Grafana, those services crash. 

**What you expected to happen:** 
The prometheus service account should be installed in the `istio-system` namespace. 

**How to reproduce it:** 
Install the prometheus addon for kubernetes and the prometheus service account would have been installed in the default namespace.

**Comment by douglas-reid** [comment]
This was fixed in istio/istio#3478.
