### ISSUE TITLE
Istio pods in pending status after installation

### ISSUE THREAD

**Issue by isaias** [istio/issues#226]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

Yes, I've verified including the Setup and Troubleshooting Guide. The Automatic Sidecar Injection requirement is fine:

```
$ kubectl api-versions | grep admissionregistration

admissionregistration.k8s.io/v1beta1

```
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version

Version: 0.5.1
GitRevision: 30acfe6528107ea333543309095659b93364b30d
User: root@2e4a18076b04
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Is Istio Auth enabled or not ?**
I've installed istio.yaml and set the istio-ingress to NodePort

**What happened**:

The installation finished without error but on verification step, all pods are in Pending status and no errors/logs are displayed in logs. How to diagnose where is the problem? I've tried to see the Ubuntu general logs and don't have useful information.

```
kubectl get svc -n istio-system
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                            AGE
istio-ingress            NodePort    10.110.0.247    <none>        80:32000/TCP,443:32246/TCP                                         1h
istio-mixer              ClusterIP   10.99.93.212    <none>        9091/TCP,15004/TCP,9093/TCP,9094/TCP,9102/TCP,9125/UDP,42422/TCP   1h
istio-pilot              ClusterIP   10.108.3.248    <none>        15003/TCP,8080/TCP,9093/TCP,443/TCP                                1h
istio-sidecar-injector   ClusterIP   10.99.250.204   <none>        443/TCP                                                            56m

kubectl get pods -n istio-system
NAME                                      READY     STATUS    RESTARTS   AGE
istio-ca-797dfb66c5-p75zc                 0/1       Pending   0          1h
istio-ingress-67ff757554-shhs7            0/1       Pending   0          1h
istio-mixer-5bf5b5b94c-j8lcz              0/3       Pending   0          1h
istio-pilot-676d495bf8-wd95l              0/2       Pending   0          1h
istio-sidecar-injector-7b559f7f6f-xtn8l   0/1       Pending   0          55m

```
**What you expected to happen:**

The pods in Running state

**How to reproduce it:**

Create a cluster using kubeadm (Bare Metal or Amazon EC2) and them install Istio

**Feature Request:**
N

**Describe the feature:**

**Comment by isaias** [comment]
I've identified the problem. There was a problem in master/slave(s) communication. Now it is working fine.

**Comment by leighyu1983** [comment]
@isaias I met this problem on istio version 1.0.0 using k8s 1.11.0 and docker  18.06.1-ce. K8s cluster is setup using kubeadm.
