### ISSUE TITLE
source.service can not be collected.

### ISSUE THREAD

**Issue by taozix** [istio/issues#231]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
yes

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version = 0.6.0
kubectl version = 1.9.3
```

**What happened**:
deploy the service: haproxy-svc--->nginx-svc
service can be visited normally，but source.service is null , protocol is tcp;
![image](https://user-images.githubusercontent.com/4743796/36838694-ce5c8438-1d7a-11e8-981c-e31d1aee78ec.png)

**What you expected to happen:**
protocol is http & source.service should not be null.

**Comment by douglas-reid** [comment]
Can you provide more details on your deployment?

What are the port labels for the various svcs in your mesh?

**Comment by taozix** [comment]
hi,
haproxy-yaml:
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: haproxy
        track: stable
        version: v1
    spec:
      containers:
      - name: haproxy
        image: haproxy:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: haproxy



nginx-yaml:
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        track: stable
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:v1 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-1 
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: nginx
    version: v1

**Comment by douglas-reid** [comment]
The first issue I see is that you have specified the protocol for your ports as `TCP`.  If you wish to see http data, you will need to name them with a prefix of 'http-`.

Can you try that and see what happens?

**Comment by taozix** [comment]
thanks, http data such as source.service & source.version can be connected successful. but source.service will be null if sidecar listener using tcp mode.
