### ISSUE TITLE
AWS Cloudwatch adapter feature proposal

### ISSUE THREAD

**Issue by narehayrapetyan** [istio/issues#239]
Hello, I'm planning on contributing an AWS cloudwatch mixer adapter to send metrics to cloudwatch. I wanted to gauge interest and also see if there's anything I should look out for other than following the adapter development doc. Thanks!

**Comment by baldwinSPC** [comment]
@narehayrapetyan cool. we're planning to do the same. want to work together?

**Comment by narehayrapetyan** [comment]
@baldwinSPC great! I actually have a working cw metrics adapter, I just need to get internal approval before I can open a PR.

**Comment by baldwinSPC** [comment]
@narehayrapetyan awesome. happy to collab once it's up.

**Comment by narehayrapetyan** [comment]
@baldwinSPC I opened the [PR](https://github.com/istio/istio/pull/4617) if you want to take a look.
