### ISSUE TITLE
egress error - not able to access http service

### ISSUE THREAD

**Issue by stunn3r-kloud** [istio/issues#245]
**Is this a BUG or FEATURE REQUEST?:**
BUG
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Yes
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
Using 0.5.1 istio from official istio git repo, 1.9.2 GKE with alpha features enabled

**Is Istio Auth enabled or not ?**
istio.yaml

**What happened**:
I was not able to do apt-get from a container in a pod with istio-sidecar, that I figured out is because all external traffic is blocked by default. created egressrule yaml:

apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: apt-egress-rule
spec:
  destination:
    service: deb.debian.org
  ports:
    - port: 80
      protocol: http
    - port: 443
      protocol: https

rule got created but still I am not able to do run any apt-get commands

**What you expected to happen:**
I expected apt-get to run as it is running in pods not containing istio-sidecar

**How to reproduce it:**
deploy a pod with official nxinx image with istio-sidecar 
use the egress yaml above

**Feature Request:**
N

**Describe the feature:**
NA

**Comment by vadimeisenbergibm** [comment]
Please define:
```yaml
service: "*.debian.org"
```

`apt-get` accesses various URLs under `*.debian.org`, e.g. http://security.debian.org

**Comment by linsun** [comment]
please reopen when the above comment doesn't help.  Also the community is working on make this simpler by enable all external traffic by default.  see https://github.com/istio/istio/issues/4378
