### ISSUE TITLE
prometheus istio-mesh status DOWN	

### ISSUE THREAD

**Issue by fudali113** [istio/issues#249]
**Is this a BUG or FEATURE REQUEST?:**
BUG
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
[mike@k8s-node0 istio-0.6.0]$ ./bin/istioctl version
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version
[mike@k8s-node0 istio-0.6.0]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
YES
```
[mike@k8s-node0 istio-0.6.0]$ kubectl get po -n istio-system
NAME                                      READY     STATUS    RESTARTS   AGE
grafana-89f97d9c-9kq9j                    1/1       Running   0          40m
istio-ca-59f6dcb7d9-np7ln                 1/1       Running   0          4d
istio-ingress-779649ff5b-cf6qs            1/1       Running   0          4d
istio-mixer-7f4fd7dff-q4mr6               3/3       Running   0          4d
istio-pilot-5f5f76ddc8-v7nx8              2/2       Running   0          4d
istio-sidecar-injector-7947777478-jq97d   1/1       Running   0          4d
prometheus-cf8456855-gdh2d                1/1       Running   0          7h

[mike@k8s-node0 istio-0.6.0]$ kubectl get svc -n istio-system
NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                            AGE
grafana                  LoadBalancer   10.104.108.222   <pending>     3000:31314/TCP                                                     42m
istio-ingress            LoadBalancer   10.100.119.16    <pending>     80:31494/TCP,443:31210/TCP                                         4d
istio-mixer              ClusterIP      10.101.255.209   <none>        9091/TCP,15004/TCP,9093/TCP,9094/TCP,9102/TCP,9125/UDP,42422/TCP   4d
istio-pilot              ClusterIP      10.105.53.6      <none>        15003/TCP,8080/TCP,9093/TCP,443/TCP                                4d
istio-sidecar-injector   ClusterIP      10.110.21.60     <none>        443/TCP                                                            4d
prometheus               LoadBalancer   10.106.67.95     <pending>     9090:31313/TCP                                                     7h
```
**What happened**:
![image](https://user-images.githubusercontent.com/16189465/37825500-0150e7ba-2ecb-11e8-860e-720c04764187.png)

**What you expected to happen:**
istio-mesh status up
**How to reproduce it:**

**Comment by fudali113** [comment]
@douglas-reid can you help me ?

**Comment by douglas-reid** [comment]
@fudali113 sorry, i missed the notification for this issue. Do you know if the Mixer config for prometheus was properly installed and loaded by Mixer?  There is related steps for troubleshooting available at https://istio.io/help/troubleshooting.html#verify-mixer-is-sending-metric-instances-to-the-prometheus-adapter.

**Comment by katya-s** [comment]
@fudali113 I faced with the same issue and found out a workaround. Try applying istio configuration again (execute command from istio directory or specify full path):

`kubectl apply -f <path to istio folder>/install/kubernetes/istio.yaml`

(see manual - https://istio.io/docs/setup/kubernetes/quick-start.html#installation-steps)

**Comment by douglas-reid** [comment]
Closing this issue, as there has been no follow-up since Apr 15.  Feel free to re-open if still experiencing issues with 0.8+

**Comment by chaturangalagama** [comment]
I'm experiencing the same issue..

**Comment by chaturangalagama** [comment]
![image](https://user-images.githubusercontent.com/15343984/45864393-7f677c80-bd97-11e8-9ba0-9b996e05b288.png)

**Comment by morgulnet** [comment]
I got the same err ,fixed it like this
kubectl create clusterrolebinding cluster-admin-binding \
 --clusterrole=cluster-admin \
 --user=$(gcloud config get-value core/account)
