### ISSUE TITLE
RateLimiting is not working.

### ISSUE THREAD

**Issue by anandkumarpatel** [istio/issues#257]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Yes

**Bug:**
Yes

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version (minikube)
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T20:49:12Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

bug also repros with (aws cluser)
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T20:49:12Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Auth is NOT enabled

**What happened**:
After installing minikube & istio I followed the docs on how to setup ratelimiting with the bookinfo example. 
I also conducted test with a cluster spun up with kops on AWS. 

**What you expected to happen:**
I expected rate limiting to work. I tried following the docs https://istio.io/docs/tasks/policy-enforcement/rate-limiting.html

I also tried changing 
```
    maxAmount: 5000
    validDuration: 1s
```
to 
```
    maxAmount: 5
    validDuration: 10s
```
in `ratelimit-handler.yaml`

I also tried to apply rate limit resources provided in the sample itself.   https://github.com/istio/istio/blob/release-0.6/samples/bookinfo/kube/mixer-rule-ratings-ratelimit.yaml

Also tried changing the `maxAmount` and `validDuration` values. 

**How to reproduce it:**
1. download latest minikube (minikube version: v0.25.2) and start it how the docs say to (https://istio.io/docs/setup/kubernetes/quick-start.html)
```
  minikube start \
	--extra-config=controller-manager.ClusterSigningCertFile="/var/lib/localkube/certs/ca.crt" \
	--extra-config=controller-manager.ClusterSigningKeyFile="/var/lib/localkube/certs/ca.key" \
	--extra-config=apiserver.Admission.PluginNames=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota \
	--kubernetes-version=v1.9.0
```
2. follow docs exactly to setup istio 0.6.0 without auth and without auto injection
```
kubectl apply -f install/kubernetes/istio.yaml
```
3. follow docs to install bookinfo with manuall injection
```
kubectl apply -f <(istioctl kube-inject --debug -f samples/bookinfo/kube/bookinfo.yaml)
```
4. follow docs to try rate limiting https://istio.io/docs/tasks/policy-enforcement/rate-limiting.html
5. notice there is no rate limiting happening :'(

I could not see anything fishy in the logs beside this line:
```
2018-03-27T00:31:25.497461Z	error	adapter did not close all the scheduled daemons	{"adapter": "handler.memquota.istio-system"}
```

**Comment by anandkumarpatel** [comment]
Also found this in the metrics. 2 instances one with `error=true` and one with `error=false`
```
mixer_runtime_dispatch_count{adapter="memquota",error="false",handler="handler.memquota.istio-system",meshFunction="quota"} 0
mixer_runtime_dispatch_count{adapter="memquota",error="true",handler="handler.memquota.istio-system",meshFunction="quota"} 0
```

**Comment by mandarjog** [comment]
This is an omission in the docs.

Please add quotaspec and quotaspecbinding resources per
https://github.com/istio/istio/blob/master/samples/bookinfo/kube/mixer-rule-ratings-ratelimit.yaml

**Comment by anandkumarpatel** [comment]
Do I need to do something different than that file? I tried applying that file as well with the same result.

**Comment by anandkumarpatel** [comment]
Found the issue. Looking at the docs for `QuotaSpecBinding.QuotaSpecReference` https://istio.io/docs/reference/config/istio.mixer.v1.config.client.html#QuotaSpecBinding.QuotaSpecReference

It states:
```
Optional namespace of the QuotaSpec. Defaults to the value of the metadata namespace field.
```

The namespace for `QuotaSpec` in the [mixer-rule-ratings-ratelimit.yaml](https://github.com/istio/istio/blob/master/samples/bookinfo/kube/mixer-rule-ratings-ratelimit.yaml#L70) is `istio-system`. However the sample `bookinfo` app gets installed inside of `default` namespace. Adding `namespace: default` to the `services` in `QuotaSpecBinding` saved the day!

```
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  creationTimestamp: null
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: ratings
    namespace: default
  - name: reviews
    namespace: default
  - name: details
    namespace: default
  - name: productpage
    namespace: default
```

Will make a PR to update this and the docs

**Comment by ldemailly** [comment]
For reference we do have a working test of rate limits:

https://github.com/istio/istio/blob/0.7.1/tests/e2e/tests/mixer/mixer_test.go#L563

So indeed this is mostly a doc issue

**Comment by dotw** [comment]
adding namespace indeed works, @anandkumarpatel  you saved me.

**Comment by jeson114** [comment]
Thanks @anandkumarpatel  . This got me out of a puddle

**Comment by douglas-reid** [comment]
Seems like this is resolved. Closing.
