### ISSUE TITLE
Routing with conditions does not work correctly with Ingress

### ISSUE THREAD

**Issue by avalcepina** [istio/issues#260]
**Is this a BUG or FEATURE REQUEST?:**

Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

(However I tried also with 0.7.0)

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....

NO AUTH

**What happened**:

In a non-default namespace I defined a service pointing to 3 different versions. Then I defined 2 route rules. The lowest precedence one was sending everything to version 3, while the highest precedence one was splitting traffic between version 1 and version 2 if the request contained a header test with value test.
I verified that these conditions were being applied by by running curls from one of the pods so that I could reach the service and everything worked as expected.
I then defined an ingress that would forward requests to the service.
If I try to reach the service by sending request through the ingress I get a 404 if I don't specify the header, which means the lower precedence route rule is not being applied.

I also tried the same scenario with version 0.7.0, since I was hoping it might fix the issue. With 0.7.0 the behaviour is different but still wrong. If I send a request through the ingress without the header the highest precedence route rule is applied regardless of the fact that the condition is false. 
With curl from a pod, instead the route rules are still working correctly.

**What you expected to happen:**

I would expect the condition to work correctly also when using an Ingress.

**How to reproduce it:**

By using this configuration:

Service:

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-03-30T11:36:39Z
  labels:
    app: application
    test: test1
  name: demo-service
  namespace: vamp-demo
  resourceVersion: "2892723"
  selfLink: /api/v1/namespaces/vamp-demo/services/demo-service
  uid: 9cd19a54-340e-11e8-bb9c-42010a840081
spec:
  clusterIP: 10.43.249.176
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: application
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

RouteRules:

```
apiVersion: v1
items:
- apiVersion: config.istio.io/v1alpha2
  kind: RouteRule
  metadata:
    annotations: {}
    clusterName: ""
    creationTimestamp: 2018-03-30T11:37:35Z
    finalizers: []
    labels:
      app: application
      gateway: gateway1
    name: gateway1-1
    namespace: vamp-demo
    ownerReferences: []
    resourceVersion: "2892837"
    selfLink: /apis/config.istio.io/v1alpha2/namespaces/vamp-demo/routerules/gateway1-1
    uid: bde896f0-340e-11e8-bb9c-42010a840081
  spec:
    destination:
      name: demo-service
    precedence: 1
    route:
    - labels:
        version: version3
      weight: 100
- apiVersion: config.istio.io/v1alpha2
  kind: RouteRule
  metadata:
    annotations: {}
    clusterName: ""
    creationTimestamp: 2018-03-30T11:37:35Z
    finalizers: []
    labels:
      app: application
      gateway: gateway1
    name: gateway1-11
    namespace: vamp-demo
    ownerReferences: []
    resourceVersion: "2892839"
    selfLink: /apis/config.istio.io/v1alpha2/namespaces/vamp-demo/routerules/gateway1-11
    uid: bdf799c9-340e-11e8-bb9c-42010a840081
  spec:
    destination:
      name: demo-service
    match:
      request:
        headers:
          test:
            regex: test
    precedence: 11
    route:
    - labels:
        version: version1
      weight: 50
    - labels:
        version: version2
      weight: 50
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  creationTimestamp: 2018-03-30T11:36:11Z
  generation: 1
  labels:
    app: application
  name: ingress
  namespace: vamp-demo
  resourceVersion: "2892695"
  selfLink: /apis/extensions/v1beta1/namespaces/vamp-demo/ingresses/ingress
  uid: 8be85428-340e-11e8-bb9c-42010a840081
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: demo-service
          servicePort: 9090
        path: /.*
status:
  loadBalancer:
    ingress:
    - ip: 104.199.84.136
```

**Comment by avalcepina** [comment]
Through further experimenting (on 0.7.1) I noticed that if I specify a condition on every route rule everything works even through an Ingress.
This is still a big problem however, because there's no easy way to specify a match everything condition.

**Comment by avalcepina** [comment]
This is the sam issue reported in #4468

**Comment by linsun** [comment]
agree, it looks same as istio/istio#4468, please follow up with istio/istio#4468 for status.
