### ISSUE TITLE
Parameterize sidecar-injector policy in helm template

### ISSUE THREAD

**Issue by jsw** [istio/issues#263]
**Feature Request:**
Y

**Describe the feature:**

Parameterize the `policy` value 
https://github.com/istio/istio/blob/0.7.1/install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml#L13

**Comment by linsun** [comment]
Is this enabled here already?  https://github.com/istio/istio/blob/0.7.1/install/kubernetes/helm/istio/values.yaml#L74

**Comment by jsw** [comment]
I didn't notice that. So it looks like it's already in values.yaml, but the value in the template I linked is not referencing it, unless I'm misunderstanding the setup?

**Comment by sakshigoel12** [comment]
@mandarjog can you take a look and suggest what work needs to happen here?

**Comment by sakshigoel12** [comment]
@ayj adding you incase you can help here

**Comment by ayj** [comment]
I think this is what @jsw is asking for. The _policy_ value should be added to each of the value-*.yaml helm variants. 

```diff
$ git diff
diff --git a/install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml b/install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml
index ed3b48a52..b01d98686 100644
--- a/install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml
+++ b/install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml
@@ -11,7 +11,7 @@ metadata:
     istio: sidecar-injector
 data:
   config: |-
-    policy: enabled
+    policy: {{ .Values.policy }}
     template: |-
       initContainers:
       - name: istio-init
diff --git a/install/kubernetes/helm/istio/values.yaml b/install/kubernetes/helm/istio/values.yaml
index f8854671d..71f4113f5 100644
--- a/install/kubernetes/helm/istio/values.yaml
+++ b/install/kubernetes/helm/istio/values.yaml
@@ -179,6 +179,7 @@ sidecar-injector:
   serviceAccountName: default # used only if RBAC is not enabled
   replicaCount: 1
   imagePullPolicy: IfNotPresent
+  policy: enabled
   resources: {}
   # limits:
   #  cpu: 100m
```

**Comment by jsw** [comment]
@ayj Yes! Sorry I wasn't more clear. Basically I want to use the helm templates and override the default policy via command-line arg.

**Comment by yusuoh** [comment]
#5044

**Comment by jsw** [comment]
@sakshigoel12 I think we are good now that we can do `helm ... --set global.proxy.policy=disabled`?
