### ISSUE TITLE
Istio 0.7.1 doesn't contain certificates 

### ISSUE THREAD

**Issue by adamdyga** [istio/issues#266]
**Bug:**

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**

```
$ istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

$ minikube version
minikube version: v0.25.2
```
Operating system is OS.X
Istio is installed according to https://istio.io/docs/setup/kubernetes/quick-start.html :
```
curl -L https://git.io/getLatestIstio | sh -
```

**Is Istio Auth enabled or not ?**
Yes (enabled)

**What happened**:

The docs at https://istio.io/docs/tasks/security/plugin-ca-cert.html mention certificates at `install/kubernetes` directory, but the certificates are not there when you unpack Istio 0.7.1.

What's more, if you use the certificates listed at https://archive.istio.io/v0.6/docs/tasks/security/plugin-ca-cert, the point 4 in "Verifying the new certificates" section fails, because the chain file `/tmp/pod-cert-chain.pem` contains only one certificate. Is it expected to be like that?

**What you expected to happen:**

The tutorial at https://istio.io/docs/tasks/security/plugin-ca-cert.html  works.

**How to reproduce it:**

Follow the tutorial at https://istio.io/docs/tasks/security/plugin-ca-cert.html  with Istio 0.7.1

**Comment by wattli** [comment]
Sure, a fix is on the way.

**Comment by wattli** [comment]
@myidpt, FYI.

**Comment by wattli** [comment]
@adamdyga , we are working a fix now and to unblock you, please try the old website:
https://archive.istio.io/v0.6/docs/tasks/security/plugin-ca-cert

**Comment by adamdyga** [comment]
@wattli I did. As I wrote in my original post, if you use the certificates listed at https://archive.istio.io/v0.6/docs/tasks/security/plugin-ca-cert the tutorial fails at point 4. 
Additionally, if you use those certificates, the mutual TLS seems to be *not* working for me. At least when you verify it according to https://istio.io/docs/tasks/security/mutual-tls.html, the following command fails:
```
curl https://details:9080/details/0 -v --key /etc/certs/key.pem --cert /etc/certs/cert-chain.pem --cacert /etc/certs/root-cert.pem -k
```

**Comment by myidpt** [comment]
Sorry, this is a known issue and fixed at head:
https://github.com/istio/istio/pull/4640
Istio CA from the V0.6 release should not have this issue. You can use the head or V0.6 to test.
