### ISSUE TITLE
Manual sidecar injection in a GRPC endpoint in GKE 1.9 - istio 0.7.1

### ISSUE THREAD

**Issue by unludo** [istio/issues#273]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version : 0.7.1
kubectl version : client v1.8.6 - server v1.9.4-gke.1
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
I tried both

**What happened**:

I tried to manually inject istio into a running deloyment :

kubectl apply -f <(istioctl kube-inject --debug -f deployment-grpc.yml)

esp | 06.04.2018, 10:32:12 AM | ERROR:Fetching access token failed (url http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token, status code 404)
-- | -- | --
esp | 06.04.2018, 10:32:12 AM | INFO:Fetching an access token from the metadata service

**What you expected to happen:**

ESP running without error

**How to reproduce it:**
Create a GRPC endpoint in GKE and manually attach an istio sidecar.

**Feature Request:**
N

**Describe the feature:**

**Comment by linsun** [comment]
Believe this is GKE specific with metadata service cc @ldemailly @andraxylia

**Comment by xiaolanz** [comment]
I'm working on writing a tutorial for installing istio on endpoints. For this to work, you have to whitelist istio ip ranges at ingress during kube-inject: https://istio.io/docs/tasks/traffic-management/egress.html#calling-external-services-directly
