### ISSUE TITLE
appendHeaders does not work in istio 0.7.1

### ISSUE THREAD

**Issue by akyyy** [istio/issues#274]
**Is this a BUG or FEATURE REQUEST?:**
BUG

istioctl version: 0.7.1
kubectl version: 1.9.3-gke.0

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
istio.yaml

**What happened**:
appendHeaders does not work.

**What you expected to happen:**
appendHeaders would add headers to request.

**How to reproduce it:**
Create an istio routerule with a couple of additional headers. 
spec:
  appendHeaders:
    hello1: world1
    hello2: world2

When curl the proxy config, there should be corresponding request_headers_to_add like this:
 "request_headers_to_add": [
       {
        "key": "hello1",
        "value": "world1"
       },
       {
        "key": "hello2",
        "value": "world2"
       }
      ],

Lin Sun reproduced this issue.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-dev/7FA5TIhoZWg/E-2cn29ZAwAJ

**Comment by linsun** [comment]
FYI, this route rule is what I used:

```
$ kubectl describe routerule guestbook-all-v2
Name:         guestbook-all-v2
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  config.istio.io/v1alpha2
Kind:         RouteRule
Metadata:
  Cluster Name:
  Creation Timestamp:  2018-04-04T02:58:26Z
  Generation:          0
  Resource Version:    4269205
  Self Link:           /apis/config.istio.io/v1alpha2/namespaces/default/routerules/guestbook-all-v2
  UID:                 0b736826-37b4-11e8-b3a8-0a3857b8df6f
Spec:
  Append Headers:
    Hello:     world
    Revision:  configuration-example-00001
  Destination:
    Name:      guestbook
  Precedence:  1
  Route:
    Labels:
      Version:  2.0
Events:         <none>

```

**Comment by linsun** [comment]
just for the record - I can't recreate it with my service and route rule above.
