### ISSUE TITLE
Support for StatefulSets

### ISSUE THREAD

**Issue by FuzzOli87** [istio/issues#28]
Hello!

I was hoping to use Istio with my Kafka/Zookeeper clusters but after trying the inject command and reading through the docs, I see that StatefulSet is not a supported type. 

Is this in the works? Is StatefulSet something that I should even be using with Istio?

**Comment by kelseyhightower** [comment]
I'm working on this in https://github.com/istio/pilot/pull/896

**Comment by rshriram** [comment]
We have support for stateful sets now, thanks to @kelseyhightower
