### ISSUE TITLE
helm: inconsistent service name usage in zipkin subchart

### ISSUE THREAD

**Issue by ryane** [istio/issues#284]
**BUG**

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istio: master
istioctl version: n/a
kubectl version: 1.9.4
kubernetes version: 1.9.4
```

**Is Istio Auth enabled or not ?**

Yes, but not applicable.

**What happened**:

The ingress for zipkin uses an incorrect service name for the backend.

**What you expected to happen:**

The zipkin Ingress should reference the correct zipkin service name.

**How to reproduce it:**

```
helm install \
  --name istio \
  --namespace istio-system \
  --set global.securityEnabled=true \
  --set zipkin.enabled=true \
  --set zipkin.ingress.enabled=true \
  istio
```

```
$ kubectl -n istio-system get service -lapp=zipkin
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
zipkin    ClusterIP   10.19.241.220   <none>        9411/TCP   9m

$ kubectl -n istio-system get ingress istio-zipkin -o jsonpath='{.spec.rules[0].http.paths[0].backend.serviceName}'
istio-zipkin
```

The Service name is hardcoded: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/zipkin/templates/service.yaml#L4

But, the ingress uses the "zipkin.fullname" template for the corresponding backend service name: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/zipkin/templates/ingress.yaml#L2

notes.txt also uses the templated name in a few places: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/zipkin/templates/NOTES.txt

It is currently necessary for the zipkin service name to be hardcoded to "zipkin" as other components refer to "zipkin" explicitly and are not (easily) configurable (https://github.com/istio/istio/blob/32bbc32858c2e515fa399241542c40099d88cec9/install/kubernetes/helm/istio/templates/configmap.yaml#L73, for example). The zipkin subchart could be fixed to hardcode the service name to "zipkin" in the ingress.yaml and NOTES.txt, but, ideally, the service name could be configurable across all components (perhaps as part of https://github.com/istio/istio/issues/4853?).

**Comment by jeffmendoza** [comment]
@ryane Thanks for the report. Let's update the ingress.yaml to point to the hardcoded backend service name. As you mentioned, istio/istio#4853 covers the request to make the name configurable. Do you want me to make this change?

**Comment by ryane** [comment]
I can create a quick PR for it
