### ISSUE TITLE
extraneous newline in istioctl kube-injected yamls

### ISSUE THREAD

**Issue by omnilinguist** [istio/issues#286]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: YES

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version = 0.7.1
kubectl version = 1.8.3
```

**Is Istio Auth enabled or not ?** No (istio.yaml)

**What happened**: In https://github.com/istio/istio/blob/0b4526f6fb3f1b3b940e1d4a2f4448aee7880387/install/kubernetes/templates/istio-sidecar-injector-configmap-debug.yaml.tmpl, there is a section

```
      - args:
        - -c
        #/etc/istio/proxy value here matches ConfigPathDir const in context.go
        - sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t && ulimit -c
unlimited
```
where 'unlimited' has been put on a new line. However, after applying istioctl kubject, the "enable-core-dump" InitContainer fails to come up with this error:

```
$ kubectl logs [pod] -c enable-core-dump
/bin/sh: unlimited: not found
kernel.core_pattern = /etc/istio/proxy/core.%e.%p.%t
unlimited
```

This leads me to believe that the above newline between "sysctl..." and "unlimited" should not be there; since when I manually edited the istioctl-generated YAML file to join the two offending lines, the deploy succeeded and the pod was healthy.

However, it seems this newline has been there since at least 0.4.0, and I do not recall it failing before when testing it on 0.4.0, so not sure if anything changed? In either case, it seems like this should be fixed.

**What you expected to happen:** I've hacked around this for now as follows:
```
def fix_istio_yaml(input_yaml):
    # TODO HACK!! this should be removed once https://github.com/istio/issues/issues/286 is resolved
    import re
    return re.sub(r'ulimit -c\n.*unlimited', 'ulimit -c unlimited', input_yaml)
```
After doing this, the expected behaviour of `enable-core-dump` coming up successfully happens.

**How to reproduce it:** `istioctl kube-inject --includeIPRanges=100.64.0.0/13 -f [app.yaml]` & apply yaml

**Comment by ayj** [comment]
Thanks for reporting. See https://github.com/istio/istio/pull/4942 for the fix.
