### ISSUE TITLE
istioctl support for Openshift DeploymentConfig

### ISSUE THREAD

**Issue by debianmaster** [istio/issues#29]
istioctl kube-inject  can attach side card for `Deployment`  object  how can i make it to work for `DeploymentConfig`   which is openshift equivalent to `Deployment`
cc / @smarterclayton

**Comment by smarterclayton** [comment]
The way we generally handle this in kube and openshift is being able to locate the pod template to execute the patch.  Today, swagger and open api do at least communicate what is a pod template, although in practice everyone just hardcodes a list..  Generally finding the patch point by a simple map works well - the openshift resources is `apps.openshift.io/v1` and `DeploymentConfig` on OpenShift 3.6+.  There will definitely be other, non-core kube resources that have pod templates.

We've discussed having a subresource for things that have pod templates (`/deployments/foo/podtemplate`) that allowed GET, PUT, and PATCH.  It has not been implemented.  Canonical issue is https://github.com/kubernetes/kubernetes/issues/41677

**Comment by karmab** [comment]
hello, what's the status on this one, can i just hack around istioctl code ? where could i start

**Comment by ayj** [comment]
Here's a list of high-level things that need to be done to enable `DeploymentConfig` for `kube-inject` and the initializer.

* Add `DeploymentConfig` to the list of supported kinds for the initializer at https://github.com/istio/istio/blob/master/install/kubernetes/istio.yaml#L923. 
* Add `deploymentconfigs` resource to `InitializerConfiguration` at https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-initializer.yaml.tmpl
* Add `deploymentconfigs` resource to ClusterRole for initializer at https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-rbac-beta.yaml.tmpl#L36
* Verify that the code that looks up the to-be-patched `PodSpec` is correct for `DeploymentConfig` in `intoObject` at https://github.com/istio/pilot/blob/master/platform/kube/inject/inject.go#L445.

**Comment by jamesfalkner** [comment]
Welp, it's there now: https://github.com/istio/istio/commit/0198fc5ca214fcd7b3e9f15ae471146124bef59c

**Comment by ayj** [comment]
Yup, we can close this now. The initializer specific changes are no longer relevant now that that we're doing pod-level injection.
