### ISSUE TITLE
Zipkin traces impacted by server (shared context) spans from istio-policy

### ISSUE THREAD

**Issue by objectiser** [istio/issues#306]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl - local build associated with https://github.com/istio/istio/pull/5098 based off master 5f7b95f4f7fe4799982f61c0c4865bb7723fab4c

kubectl version:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

```

**Is Istio Auth enabled or not ?** No
Helm chart being developed in https://github.com/istio/istio/pull/5098

**What happened**:
When testing the new tracing chart, which supports both zipkin and jaeger backends based on a `tracing.provider` property, I found that some additional spans being reported by the `istio-policy` component are resulting in zipkin spans being "corrupted" for want of a better word.

Due to zipkin's shared span model, where spans from the client and server share the same span-id and their contents is combined into a single span in the backend - the `istio-policy` spans (which are being reported as server spans) are also being combined into the single span in the backend, resulting in things like the service and operation names being unpredictable, because it depends on the order in which the spans are combined.

For example:
![istio-helm-zipkin1](https://user-images.githubusercontent.com/164562/39364018-4b37514c-4a24-11e8-859e-b9343c885c97.png)
This images shows the trace from an `ordermgr` service calling an `accountmgr` service. Selecting the top span shows:
![istio-helm-zipkin2](https://user-images.githubusercontent.com/164562/39364051-79c9cf80-4a24-11e8-86c6-652880a34287.png)
where the shared span representing the request from `istio-ingress` to `ordermgr` is randomly being combined with `istio-policy` spans. And the `accountmgr` span:
![istio-helm-zipkin3](https://user-images.githubusercontent.com/164562/39364118-bb74631e-4a24-11e8-80dd-41e0ef3fda64.png)

This may also be the reason for the failing istio-pilot tests, which are trying to look for spans with operation name `default-route`. If the span (operation) names for these shared context spans are non-deterministic, it would explain the test fails.

**What you expected to happen:**
When using jaeger, the trace looks like this:
![istio-helm-jaeger](https://user-images.githubusercontent.com/164562/39364189-0f889132-4a25-11e8-92f4-5f6ddbe32a9c.png)
This is the type of hierarchy we should see with the zipkin backend. Jaeger is able to display the trace in this way, because it does not support the shared span model - if two or more spans report the same span id, it will allocate them a unique id.

**How to reproduce it:**
It should be reproducible with master (as needs the `istio-policy` spans being reported in the same trace instance as the application), using a normal zipkin deployment and the bookinfo sample.

Two solutions:
1) Rather than just reporting the server spans for `istio-policy` and `istio-mixer` - it would be better to also have the client spans. When zipkin reports a client span it will use a unique id.
2) Have a config option (possibly in envoy aswell) to disable shared span context.

**Comment by kyessenov** [comment]
Thanks for your investigation!

cc @douglas-reid @bianpengyuan as we have been trying to understand issues with istio-policy/istio-telemetry spans.

**Comment by kyessenov** [comment]
Is the crux of the issue is that the outgoing Check call re-uses the span from the client operation in the picture below:
```
(client app) ---> | policy check | ----> (server app)
                            |
                      (istio-policy)
```

Since both istio-policy and server app envoys report the operation for the same span, we get a race between them, depending which ones comes last to the zipkin collector.

For solution (1), should we initiate a new span on the call, and set the parent span to be the span from the client?

**Comment by bianpengyuan** [comment]
Right now Mixer filter just simply copies all tracing headers into grpc metadata: https://github.com/istio/proxy/blob/master/src/envoy/utils/grpc_transport.cc#L66, which collapses check call span into request span.

Agree we should make check call span a child span. Ideally we can make this configurable in case it is too noisy.

**Comment by objectiser** [comment]
@kyessenov @bianpengyuan 

Yes would be good if could create a child span, which would result in a unique span id. Currently this would result in the zipkin tracer just creating a component span (i.e. not a 'client' span) however that would be adequate to overcome this current issue. An enhancement would be required on Envoy's zipkin client to enable the child span to be classified as a client span - but that can be handled later.

To disable tracing of the check call, it would be necessary to make this child span creation conditional - but also set the X-B3-Sampled header property to 0 on the outbound http request, to ensure the istio-policy/mixer server span is not reported - as this would result in the same problem reported here.

**Comment by bianpengyuan** [comment]
PR is out istio/proxy#1593
