### ISSUE TITLE
Zipkin traces not showing up

### ISSUE THREAD

**Issue by debianmaster** [istio/issues#31]
i followed steps listed here https://istio.io/docs/tasks/zipkin-tracing.html
and pumped some traffic on /producpage  service.    no traces are showing up on zipkin!  i'm i missing anything?   

Note:  service mesh is running on top of openshift, and all other examples seem to work fine.

**Comment by ldemailly** [comment]
can you add the relevant logs ? anything in mixer or envoy logs that seems abnormal ?

**Comment by debianmaster** [comment]
<img width="1279" alt="screen shot 2017-06-14 at 1 24 08 pm" src="https://user-images.githubusercontent.com/1439169/27152896-44913c3c-5104-11e7-9a3d-eeb89ea4a43d.png">

no sign of any errors in mixer or envoy logs    i can see metadata but not any traces now.   i changed date ranges and tried too

**Comment by debianmaster** [comment]
is there any dependency on  kube 1.6  for distributed tracing to work?

**Comment by ldemailly** [comment]
also, are you running 0.1.6 or something else ?

**Comment by debianmaster** [comment]
i'm running 0.1.6 istio on openshift 1.5.1  which is  k8s 1.5   :)

**Comment by ldemailly** [comment]
Did you hit the "find traces" button ?

I just tried with the latest and it worked: (with some workaround below because of the manage->pilot rename) but please confirm if 0.1.6 doesn't work for you or it's just that UI issue with zipkin which tripped me over as well (not clicking the `find traces` button)
```
$ git clone https://github.com/istio/istio.git ; cd istio
$ source istio.VERSION 
$ export MANAGER_HUB=$PILOT_HUB  # Important/needed at the moment
$ export MANAGER_TAG=$PILOT_TAG  # ditto
$ curl -L $ISTIOCTL_URL/istioctl-osx > ./istioctl  # change the -osx to your env if needed
$ ./istioctl version
istioctl version:

Version: 0.2.0-ac94a44
GitRevision: ac94a44
GitBranch: master
User: jenkins@ubuntu-16-04-build-12744189088e0f
GolangVersion: go1.8
KubeInjectHub: docker.io/istio
KubeInjectTag: 0.1


apiserver version:

Version: 0.2.0-ac94a44
GitRevision: ac94a44
GitBranch: master
User: jenkins@ubuntu-16-04-build-12744189088e0f
GolangVersion: go1.8.1
# rest of the installation instructions as is
```

**Comment by debianmaster** [comment]
turns out this is a date issue on the container.   when docker is running container  host time is not synced into running container.

**Comment by Morriz** [comment]
So what steps can we take to fix this? I am running minikube on osx

**Comment by Morriz** [comment]
I found this one liner:
`minikube ssh -- docker run -i --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i date -u $(date -u +%m%d%H%M%Y)`

here: https://github.com/kubernetes/minikube/issues/1378

**Comment by Morriz** [comment]
And this one goes with it:
`minikube ssh -- sudo ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime`

But I still get not trace ;|

**Comment by Morriz** [comment]
Any idea what could be wrong? The date settings are now identical between host and guest vm.

I am using auto-injection.

**Comment by debianmaster** [comment]
@Morriz  this error is 0.1.6   i do not see this error anymore on the newer alpha release

**Comment by Morriz** [comment]
I am using 0.2.4, but I get no metrics in the zipkin nor jaeger

**Comment by debianmaster** [comment]
jaeger has some issue AFAIk,   zipkin is working for me  on 0.2.4 release

**Comment by ldemailly** [comment]
try master or wait a bit for 0.2.6 which should be today

**Comment by Morriz** [comment]
I deployed the book app in the `default` namespace (as in the tutorial). How is it going to deliver metrics to the `istio-system` namespace where I deployed the zipkin and jaeger services? The sidecars are running next to the pods in the 'default` namespace, no?

**Comment by debianmaster** [comment]
sidecar should send metrics to istio control plane in istio-system   , AFAIK

**Comment by Morriz** [comment]
Maybe it has to do with this: https://github.com/istio/istio/issues/936

**Comment by Morriz** [comment]
I managed to get output...it just took forever ;| Starting zipkin again after jaeger got zipkin working, but jaeger seems to discard input after a small window of receiving metrics
