### ISSUE TITLE
A ~3 minute delay when removing access from a listchecker 

### ISSUE THREAD

**Issue by reuvenharrison** [istio/issues#321]
**Is this a BUG or FEATURE REQUEST?:** Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.7.1
kubectl version 1.8.6
kubernetes version 1.8.8-gke.0
```

**Is Istio Auth enabled or not ?**yes
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
stable istio_auth.yaml.

**What happened**:
I have rule with a whitelist and a listchecker.
When I add a value to the 'overrides' list in the listchecker, istio enables access to the service immediatly.
When I remove a value from the 'overrides' list in the listchecker, istio takes ~3 mins to start denying access to the service.

**What you expected to happen:**
When I remove a value from the 'overrides' list in the listchecker I expect Istio to deny access immediatly. 

**How to reproduce it:**
Create a service with a label app=time.
 
Add a rule:
```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  clusterName: ""
  creationTimestamp: 2018-04-29T15:10:51Z
  deletionGracePeriodSeconds: null
  deletionTimestamp: null
  initializers: null
  name: time
  namespace: default
  resourceVersion: "11741"
  selfLink: /apis/config.istio.io/v1alpha2/namespaces/default/rules/time
  uid: 8149fc7b-4bbf-11e8-966e-42010a840054
spec:
  actions:
  - handler: time.listchecker
    instances:
    - time.listentry
  match: destination.labels["app"] == "time"
```
Add a listentry:
```
apiVersion: config.istio.io/v1alpha2
kind: listentry
metadata:
  clusterName: ""
  creationTimestamp: 2018-04-29T15:10:51Z
  deletionGracePeriodSeconds: null
  deletionTimestamp: null
  initializers: null
  name: time
  namespace: default
  resourceVersion: "11740"
  selfLink: /apis/config.istio.io/v1alpha2/namespaces/default/listentries/time
  uid: 812b5ba1-4bbf-11e8-966e-42010a840054
spec:
  value: source.labels["app"] | "unknown"
```
Add a listchecker:
```
apiVersion: config.istio.io/v1alpha2
kind: listchecker
metadata:
  clusterName: ""
  creationTimestamp: 2018-04-29T15:10:51Z
  generation: 0
  initializers: null
  name: time
  namespace: default
  resourceVersion: "981967"
  selfLink: /apis/config.istio.io/v1alpha2/namespaces/default/listcheckers/time
  uid: 810cd756-4bbf-11e8-966e-42010a840054
spec:
  blacklist: false
  overrides: admin
```
Now access the time service from a pod with a label: app=admin.
Edit the listchecker and delete 'admin' from 'overrides'.
Access the time service from a pod with a label: app=admin.
You will be able to access the time service for another ~3 mins.

**Feature Request:**
N

**Describe the feature:**

**Comment by douglas-reid** [comment]
cc: @geeknoid @mandarjog

**Comment by reuvenharrison** [comment]
Thanks @geeknoid - closing this issue.
