### ISSUE TITLE
Rabbitmq can not start after istioctl kube-inject

### ISSUE THREAD

**Issue by Viali** [istio/issues#327]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
No. I used the istio.yaml (without Auth enabled)

**What happened**:
The rabbitmq service in the Sock-shop demo(https://microservices-demo.github.io/docs/quickstart.html) failed to start.
All services are working fine without istioctl kube-inject. 
However, after applying istioctl kube-inject, the rabbitmq service can not start.

**What you expected to happen:**
I expected everything should be fine.

**How to reproduce it:**
git clone https://github.com/microservices-demo/microservices-demo
cd microservices-demo/deploy/kubernetes/
kubectl create namespace sock-shop
kubectl create -f <(istioctl kube-inject -f complete-demo.yaml)

or you can use the part I cut from the complete-demo.yaml via http://textuploader.com/dfoux 
then:
kubectl create namespace sock-shop
kubectl apply -f rabbitmq.yaml

**Feature Request:**
N

**Describe the feature:**

**Comment by frankh** [comment]
I also have this issue, with Istio Auth enabled

**Comment by Viali** [comment]
Did you solve it?

**Comment by frankh** [comment]
nope, given up on istio for now

**Comment by JohnDzialo** [comment]
+1

**Comment by ymesika** [comment]
Potential duplication of https://github.com/istio/istio/issues/5989
Please re-open if it's not.
