### ISSUE TITLE
Injected Istio Container fails Pod creation when a ResourceQuota exists for the namespace

### ISSUE THREAD

**Issue by andersjanmyr** [istio/issues#339]
Automatically injected Istio Container fails Pod creation when a ResourceQuota exists for the namespace even though I have added default values for the namespace and/or added resource requests and limits to the injector config map.

When the resource quota on the namespace is removed the pods are created with the proper limits set, but when the quota is on the namespace it fails before the pods come up to allow inspection.

Also, when I inject the sidecar manually before I create the pod, it works.

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Not enabled, installed with istio.yaml.

**What happened**:
When `istio-injection=enabled` the creation of the pod fails with a quota error.
```
  Warning  FailedCreate  1m               replicaset-controller  Error creating: pods "counter-7d4b857bc5-9vfv5" is forbidden: failed quota: tapir-rq: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```

Here's the namespace.
```
$ kubectl describe ns tapir
Name:         tapir
Labels:       istio-injection=enabled
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"test":"hello_world"},"name":"tapir","namespace":""}}

Status:  Active

Resource Quotas
 Name:            tapir-rq
 Resource         Used       Hard
 --------         ---        ---
 limits.cpu       1500m      6
 limits.memory    262217728  6Gi
 requests.cpu     500m       6
 requests.memory  96Mi       6Gi

Resource Limits
 Type       Resource  Min  Max  Default Request  Default Limit  Max Limit/Request Ratio
 ----       --------  ---  ---  ---------------  -------------  -----------------------
 Container  cpu       -    -    250m             500m           -
 Container  memory    -    -    32Mi             128Mi          -
```

**What you expected to happen:**
I expected the Pod to be created without error.

**How to reproduce it:**

1. Create a namespace with a resource quota and enable istio-injection.
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tapir-rq
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 6Gi
    limits.cpu: "6"
    limits.memory: 6Gi
```

2a. Add default limits to the namespace
```
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
  - default:
      cpu: 0.5
      memory: 128Mi
    defaultRequest:
      cpu: 0.25
      memory: 32Mi
    type: Container
```

2b. Alternative, add resource requests and limits to the `istio-inject` config map.

```
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
```

3. Deploy a container

```
kubectl run --image vn0wxf9/counter:latest counter
```

4. Check the error in the result set.

```
kubectl describe rs
```

**Comment by ayj** [comment]
How was your k8s cluster provisioned? It would be good to confirm that the `MutatingAdmissionWebhook` plugin is configured _after_ `LimitRanger` and before `ResourceQuota` plugins.

**Comment by andersjanmyr** [comment]
@ayj Good idea. But unfortunately it looks correct. 
```
admission-control: 'Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota'
```

**Comment by souravsekhar** [comment]
I had similar issue, updating initcontainers and istio-proxy containers with resource requests and limits in the istio-sidecar-injector-configmap and restarting the istio-ingress pod, worked for me. Also, i noticed, the resourcequota should be applied first before you enable injection on the namespace.

Hope this helps!

**Comment by souravsekhar** [comment]
I had similar issue, updating initcontainers and istio-proxy containers with resource requests and limits in the istio-sidecar-injector-configmap and restarting the istio-ingress pod, worked for me. Also, i noticed, the resourcequota should be applied first before you enable injection on the namespace.

Hope this helps!

**Comment by ayj** [comment]
Moving ResourceQuota workarounds the problem but essentially bypasses resuorce quota checks for the injected containers. The recommended plugin is list is https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use.

**Comment by markns** [comment]
Adding the resources to the istio-sidecar-inject configmap initContainer and istio-proxy also worked for me. If you're using helm, uncommenting the limits in values.yaml is enough for the istio-proxy, but for the initContainer the `resources` block must be added.

@ayj - could you explain in a bit more detail what you mean when you say "essentially bypasses resource quota checks"? My resource quota seems to be preventing the creation of pods exceeding the resource quota just fine.

**Comment by ayj** [comment]
@markns, my comment was referencing @souravsekhar's comment below. 

> Also, i noticed, the resourcequota should be applied first before you enable injection on the namespace.

ResourceQuota should run after injection. Otherwise, additional resources (i.e. containers/volumes) added _afterwards_ would not be subject to quota enforcement. 

,

**Comment by souravsekhar** [comment]
@ayj Thanks for the info! However, I see the sequence doesn't matter. I did try the  scenario where we run istio-injection after applying ResourceQuota on the namespace, and the quota enforcement works well.

I have the below quota on a namespace without istio-injection enabled at this time.

```
Name:			test-quota
Namespace:		testns
Resource		Used	Hard
--------		----	----
count/pods		0	20
count/replicasets.apps	0	10
limits.memory		0	400Mi
requests.memory		0	400Mi
```
Executed command to enable injection `kubectl label namespace testns istio-injection=enabled`
```
NAME               STATUS    AGE       ISTIO-INJECTION
testns             Active    5m        enabled
```
Resources are already set for istio-containers in the sidecar injector configmap as below
```
resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
```
Created a Replicaset with below resources
```
resources:
          limits:
            memory: 400Mi    
          requests:
            memory: 400Mi
```
And i see the quota enforcement works fine with below expected error:-
`1m		1m		3	replicaset-controller			Warning		FailedCreate	(combined from similar events): Error creating: pods "testapp-xxxx" is forbidden: exceeded quota: test-quota, requested: limits.memory=500Mi,requests.memory=500Mi, used: limits.memory=0,requests.memory=0, limited: limits.memory=400Mi,requests.memory=400Mi
`

NOTE: Enabling injection first and then applying resourcequota, also worked for me.

**Comment by ayj** [comment]
Interesting. Thanks for double checking @souravsekhar. It sounds like @andersjanmyr's original issue is likely due to their environment. @andersjanmyr, can you confirm that this is still an issue?

**Comment by andersjanmyr** [comment]
Aaargh! I had forgotten to add request and limit to the initContainer. 
After changing the initContainer configuration, it now works.
Thanks @souravsekhar and @markns for mentioning it. I wouldn't have thought about it otherwise.
Thanks to everyone else for taking the time to help me.
Closing it.

**Comment by souravsekhar** [comment]
@ayj I have a question which i believe can be a part of this discussion. As we know, we can set default memory limits and requests for a namespace using LimitRange that we basically use to assign resources to containers. However, istio-containers seem not to be privileged with this feature. To be precise, default memory limits or requests are not being applied on istio-containers even if we have a LimitRange in place.
Is this an expected behavior? if not, is there any permanent fix planned for this in near future?

**Comment by ayj** [comment]
I suspect that is because `LimitRange` runs _before_ the sidecar containers are injected. We probably need to add default resource limits to the sidecar containers. Changing the recommended plugin order will be difficult.

**Comment by souravsekhar** [comment]
@ayj  Thanks! Good piece of info
