### ISSUE TITLE
Gateway should be able to read TLS certificates from Secret

### ISSUE THREAD

**Issue by kirgene** [istio/issues#340]
**Is this a BUG or FEATURE REQUEST?:**
FEATURE REQUEST
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Y
**Bug:**
N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version git: 895d13c50a629bc69834448808d08a44b9de681c
kubectl version 1.10.2
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
Used generated file of the following command:
`helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set prometheus.enabled=true global.controlPlaneSecurityEnabled=true global.mtls.enabled=true sidecar-injector.enabled=true > istio-custom.yaml`

**What happened**:
I'm trying to make TLS termination on Gateway using certificates generated with cert-manager (LetsEncrypt). There are two properties in Gateway that should point to certificates: serverCertificate and privateKey ([reference](https://istio.io/docs/reference/config/istio.networking.v1alpha3.html#Server.TLSOptions))
The problem is that these properties consume only file path so I cannot use certificates stored in Secret.
**What you expected to happen:**
There should be an option to specify certificates from Secret, like built-in [Ingress Controller](https://kubernetes.io/docs/concepts/services-networking/ingress/) does via `tls.secretName` field:

> The TLS secret must contain keys named tls.crt and tls.key that contain the certificate and private key to use for TLS

**How to reproduce it:**

**Feature Request:**
Y

**Describe the feature:**

**Comment by wolfuser99** [comment]
is this feature already added?
