### ISSUE TITLE
ansible installer needs to support cluster version that have multiple digits in version string

### ISSUE THREAD

**Issue by jmazzitelli** [istio/issues#348]
I am running the Ansible installer from Istio: 0.7.1
I am running the latest minikube whose cluster version is 1.10.0 (notice the two-digit minor release number). The actual output of `kubectl version` is:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

The Istio Ansible Installer fails early during its assert checks because it expects only single-digits for major, minor, and patch release numbers.

I have already fixed this - see PR https://github.com/istio/istio/pull/5710

**Comment by ymesika** [comment]
Fixed by https://github.com/istio/istio/pull/6110
