### ISSUE TITLE
istio 0.8.0 ansible install on kubernetes is missing manifests

### ISSUE THREAD

**Issue by nrobert13** [istio/issues#368]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.8.0
kubectl version 1.9.2
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
ansible-playbook main.yml -e '{"cluster_flavour": "k8s"}' -e '{"istio": {"auth":true, "addon": ["prometheus", "jaeger", "servicegraph", "grafana"]}}'

**What happened**:

```
TASK [istio : Deploy Istio Auth from kubernetes file] *****************************************
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": "kubectl create -f ~/.istio/istio-0.8.0/install/kubernetes/istio-auth.yaml", 
    "delta": "0:00:00.250578", 
    "end": "2018-06-01 12:54:44.913083", 
    "rc": 1, 
    "start": "2018-06-01 12:54:44.662505"
}

STDERR:

error: the path "/root/.istio/istio-0.8.0/install/kubernetes/istio-auth.yaml" does not exist

```
istio.yaml is also missing. so I assume with auth:false wouldn't work either.

the content of the folder looks like this:
```
# ls -l ~/.istio/istio-0.8.0/install/kubernetes/
total 216
drwxr-xr-x 2 root root    26  1. Jun 00:29 addons
drwxr-xr-x 4 root root    89  1. Jun 00:29 helm
-rw-r--r-- 1 root root  1503  1. Jun 00:29 istio-citadel-plugin-certs.yaml
-rw-r--r-- 1 root root  2526  1. Jun 00:29 istio-citadel-standalone.yaml
-rw-r--r-- 1 root root  1943  1. Jun 00:29 istio-citadel-with-health-check.yaml
-rw-r--r-- 1 root root 98458  1. Jun 00:29 istio-demo-auth.yaml
-rw-r--r-- 1 root root 98047  1. Jun 00:29 istio-demo.yaml
-rw-r--r-- 1 root root  1610  1. Jun 00:29 mesh-expansion.yaml
-rw-r--r-- 1 root root  1053  1. Jun 00:29 README.md
drwxr-xr-x 2 root root    28  1. Jun 00:29 templates
```
most of the addons are also missing:

```
.istio/istio-0.8.0/install/kubernetes/addons/prometheus.yaml" does not exist
.istio/istio-0.8.0/install/kubernetes/addons/servicegraph.yaml" does not exist

#ls -l ~/.istio/istio-0.8.0/install/kubernetes/addons/
total 4
-rw-r--r-- 1 root root 1127  1. Jun 00:29 grafana.yaml
```

**What you expected to happen:**

have istio 0.8.0 deployed on the cluster

**How to reproduce it:**

```
install k8s 1.9.2
# git clone https://github.com/istio/istio.git
# cd istio/install/ansible
# ansible-playbook main.yml -e '{"cluster_flavour": "k8s"}' -e '{"istio": {"auth":true, "addon": ["prometheus", "jaeger", "servicegraph", "grafana"]}}'
```

**Comment by nrobert13** [comment]
Just found the instructions on how to get those missing manifests generated in the install/kubernetes/Readme.md:
`If you prefer to install Istio from checking out the istio/istio repostiory, you can run updateVersion.sh in the parent directory to generate the required installation files. This directory contains files needed for installing Istio on a Kubernetes cluster`

The problem is that the realeased istio-0.8.0-linux.tar.gz file ( downloaded and unpacked by ansible ) doesn't contain this script...

```
# ls -l ~/.istio/istio-0.8.0/install/          
total 4
drwxr-xr-x 2 root root   23  1. Jun 00:29 ansible
drwxr-xr-x 2 root root   59  1. Jun 00:29 consul
drwxr-xr-x 2 root root   59  1. Jun 00:29 eureka
drwxr-xr-x 3 root root   49  1. Jun 00:29 gcp
drwxr-xr-x 5 root root  264  1. Jun 00:29 kubernetes
-rw-r--r-- 1 root root 1487  1. Jun 00:29 README.md
```

**Comment by ymesika** [comment]
I believe that both the documentation and the Ansible scenario are correct.
1. The documentation mentions checking out the repository which has the script
1. Installing Ansible from the platform release zip files isn't possible because the playbooks are within the source zip file which also has the script
