### ISSUE TITLE
Question: Websocket upgrade example?

### ISSUE THREAD

**Issue by stonefury** [istio/issues#374]
Sorry, spent a very long time as being totally green to this service mesh.  I have a web socket service and all I want to do is find an example for how I inform Istio the service is a websocket, since it is currently failing.

I'm not understanding where websocketUpgrade goes, and then when I found where it might go I get an error saying I need a redirect, and so I keep chasing my tail.

tnx for any help or suggestion to add more example to the docs.

**Comment by ymesika** [comment]
If you are using v1alpha3 with Istio 0.8.0: https://github.com/istio/istio/issues/6061
