### ISSUE TITLE
BUG: proxy not report  and check ,and see no change in grafana

### ISSUE THREAD

**Issue by wansuiye** [istio/issues#377]
**Is this a BUG or FEATURE REQUEST?:**
yes

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
0.8.0
kubectl version
1.9.5
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
install 0.8.0,
no auth
no use helm

**What happened**:
if deployment file not decare ports ，the proxy not report(telemetry) and check(policy) 

**What you expected to happen:**
the proxy can report to telemetry and check policy well，meanwhile can see request change in grafana 

**How to reproduce it:**
eg bookinfo's details-v1，if delete line 47~48 in bookinfo.yaml ,it will not work ,but in 0.7.1 it can work even if the deployment not decare ports
```
ports:
- containerPort: 9080
```

**Feature Request:**
N

**Describe the feature:**

**Comment by mandarjog** [comment]
This is working as expected. `containerPort`s are captured by the inbound ip tables rules and redirected thru the proxy. If the port is not captured, you will not see any metrics.

**Comment by kyessenov** [comment]
Isn't that counter intuitive? Should we do the opt out instead?

**Comment by louiscryan** [comment]
See

https://github.com/istio/issues/issues/377
