### ISSUE TITLE
[BUG] Bookinfo tracing broken

### ISSUE THREAD

**Issue by oleg-filiutsich** [istio/issues#378]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}


```

**Is Istio Auth enabled or not ?**
I installed istio via commands
```
$ helm template ~/istio-0.8.0/install/kubernetes/helm/istio --name istio --namespace istio-system --set servicegraph.enable=true --set tracing.enabled=true --set grafana.enabled=true --set servicegraph.enabled=true > $HOME/istio.yaml

$ kubectl apply -f $HOME/istio.yaml

$ kubectl apply -f samples/bookinfo/kube/bookinfo.yaml
$ istioctl create -f samples/bookinfo/routing/bookinfo-gateway.yaml
```

**What happened**:
I call http://my_ip:31380/productpage
But not see correct request trace in jagger

I cant cach ful request chain in bookinfo service.
In browser I see that metrics    
    x-request-id
    x-b3-traceid
    x-b3-spanid
    x-b3-parentspanid
    x-b3-sampled
    x-b3-flags
    x-ot-span-context
not added to requests http://my_ip:31380/productpage.
[pic1](https://ibb.co/gVhfyT)
[pic2](https://ibb.co/gqR9Q8)

**What you expected to happen:**
![istio-tracing-details](https://istio.io/docs/tasks/telemetry/img/istio-tracing-details.png)
**How to reproduce it:**

**Comment by objectiser** [comment]
I believe you need to set the `istio-injection` label on the `default` namespace before deploying the example.

The helm template you have created would use auto injection by default, but that requires the label to be defined on the target namespace before the deployed services will be injected with the proxy sidecar.

**Comment by oleg-filiutsich** [comment]
it's working.
In my test cluster
```
$ kubectl label namespace default istio-injection=enabled
$ kubectl get namespace -L istio-injection
# Enable egress access for all
$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set servicegraph.enable=true --set tracing.enabled=true --set grafana.enabled=true --set servicegraph.enabled=true --set global.proxy.includeIPRanges="0.0.0.0/0"  -x templates/sidecar-injector-configmap.yaml | kubectl -f -
# Redeploy app bookinfo

```
