### ISSUE TITLE
Istio route rules not respected for traffic from outside Kubernetes cluster

### ISSUE THREAD

**Issue by kalantar** [istio/issues#38]
I created a service that selects among 2 deployments (different versions).
I created two istio route-rules.
The first defaults all traffic to v1.
The second sends requests that have a particular header to v2.
I then deployed the sleep sample so that I could test these rules from inside the cluster. I found that both rules worked as expected.
I then created an ingress so that I could initiate requests from outside the cluster.
When I tested it by sending requests from outside the cluster, I found that the default rule was applied to every request, including those that match the second rule.
Note that I am doing this in a non default namespace. However, this does not seem to be the issue, see also: https://groups.google.com/forum/#!topic/istio-users/yQEogcx2hJM

Here are the rules: 

    $ more *rule*
    ::::::::::::::
    default-route-rule.yml
    ::::::::::::::
    type: route-rule
    name: default-route
    namespace: user-kalantar
    spec:
      destination: echo.user-kalantar.svc.cluster.local
      precedence: 1
      route:
      - tags:
          version: one
        weight: 100
    ::::::::::::::
    user-route-rule.yml
    ::::::::::::::
    type: route-rule
    name: echo-user-rule
    namespace: user-kalantar
    spec:
      destination: echo.user-kalantar.svc.cluster.local
      precedence: 2
      match:
        httpHeaders:
          x-user:
            exact: test
      route:
      - tags:
          version: two

The ingress is: 

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: echo-ingress
      namespace: user-kalantar
      annotations:
        kubernetes.io/ingress.class: istio
    spec:
      backend:
        serviceName: echo
        servicePort: 80

**Comment by ijsnellf** [comment]
@kyessenov, could you take a look at this? You are better acquainted with ingress route rules and their limitations.

**Comment by frankbu** [comment]
To reproduce:
```
$ kubectl apply -f <(istioctl kube-inject -f samples/apps/helloworld/helloworld.yaml)

$ cat <<EOF | istioctl curl
type: route-rule
name: hello-default
spec:
  destination: helloworld.default.svc.cluster.local
  route:
  - tags:
      version: v1
EOF

$ cat <<EOF | istioctl create
type: route-rule
name: hello-canary
spec:
  destination: helloworld.default.svc.cluster.local
  precedence: 2
  match:
    httpHeaders:
      foo:
        exact: bar
  route:
  - tags:
      version: v2
EOF

$ curl -H "foo: bar" http://$HELLOWORLD_URL/hello # always returns v1
Hello version: v1, instance: helloworld-v1-1286076397-2nrdg
```

**Comment by rshriram** [comment]
fixed by PR 897 in istio/pilot.
