### ISSUE TITLE
Requests hang in fresh helm install on k8s v1.10.2-gke.3

### ISSUE THREAD

**Issue by kvudata** [istio/issues#393]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Yes, #152 seems potentially related but there were no error logs I could see in the proxy like that issue.

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.8.0
kubectl version
```
Installed Istio using [istio.io Kubernetes Quick Start instructions](https://istio.io/docs/setup/kubernetes/quick-start/#download-and-prepare-for-the-installation) and following the directions to [Render Kubernetes manifest with Helm and deploy with kubectl](https://istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template).
Also tried installing via `helm install`.

**Is Istio Auth enabled or not ?**
```
helm template istio-0.8.0/install/kubernetes/helm/istio --name istio --namespace istio-system > /tmp/istio.yaml
kubectl apply -f /tmp/istio.yaml
```

**What happened**:
Everything seemed to have installed fine i.e. all the deployments in the istio-system namespace were available, but pods with the proxy side car in the cluster were unreachable. Tried following the [Basic Authentication Policy Task](https://istio.io/docs/tasks/security/authn-policy/) but the first curl just hangs.
I verified that the proxied service was working within the pod by exec'ing into the proxy container and curl'ing localhost.
I also checked that the proxy-config's of the two proxy's had inbound/outbound clusters as expected.

Everything seems to work though on a cluster running k8s 1.9.7-gke.1

**What you expected to happen:**
Be able to connect to the proxied containers.

**How to reproduce it:**
Create a v1.10.2-gke.3 GKE cluster, install Istio, add some proxied containers.

**Feature Request:**
N

**Describe the feature:**
N/A

**Comment by kirgene** [comment]
Have the same issue with same environment

**Comment by ymesika** [comment]
@kvudata @kirgene Is it duplication of https://github.com/istio/istio/issues/5806 ?

**Comment by kvudata** [comment]
@ymesika, perhaps. That issue is specifically mentioning timeouts on the Gateway (which I did see as well) while this issue is in particular about hangs/timeouts between 2 proxy's.

**Comment by kirgene** [comment]
@ymesika Seems to be. Upgrading to 1.10.4-gke.0 (as mentioned in https://github.com/istio/istio/issues/5806) fixes this issue.

**Comment by ymesika** [comment]
@kirgene Thanks for verifying.
