### ISSUE TITLE
Error CrashLoopBackOff

### ISSUE THREAD

**Issue by ahsimon** [istio/issues#40]
Im getting the error CrashLoopBackOff  ,  is  mostly kind of  kubernets related , or could be more like docker related, why it causes crash in all the cluster? 
Im using minikube.

getting the log :$ kubectl  logs istio-egress-2038322175-p1h88
..
[2017-06-21 15:51:19.311][46][critical][backtrace] end backtrace thread 0
W0621 15:51:19.324500       1 agent.go:200] Epoch 0 terminated with an error: signal: segmentation fault (core dumped)
W0621 15:51:19.324533       1 agent.go:289] Aborted all epochs
I0621 15:51:19.324574       1 agent.go:220] Updated retry delay to 51.2s, budget to 1

**Comment by frankbu** [comment]
Is istio-egress the only service that is crashing?
What version of minikube are you using?

**Comment by ahsimon** [comment]
Hi Frank.


Thank you for post me back,

The answers :

Is istio-egress the only service that is crashing? Yes, the only one.

What version of minikube are you using?
minikube version: v0.19.1


Best Regard,

2017-06-29 10:19 GMT-04:00 Frank Budinsky <notifications@github.com>:

**Comment by frankbu** [comment]
Hard to say what might be wrong, given that it's only isito-egress. What version are you running? 
```
istioctl version
```
What yaml did you use to start istio? istio.yaml? What image is it using for egress?

Maybe you want to try to debug? https://istio.io/troubleshooting/#how-can-i-debug-issues-with-the-service-mesh

**Comment by ahsimon** [comment]
Frank,

Our team are trying to integrating istio  in our   microservices
architecture (were now working under the bluemix cloud services), and
we decide starting by  testing the bookinfo application  inside
minikube, following  the tutorial steps  to config the egress service
(https://istio.io/docs/tasks/egress.html), when  the service just
crush.



Let me know if you cant see the files below:


istioctl version:


Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8
KubeInjectHub: docker.io/istio
KubeInjectTag: 0.1


apiserver version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8.1




*istio.yml:*

$ cat istio.yaml
# GENERATED FILE. Use with Kubernetes 1.5+
# TO UPDATE, modify files in install/kubernetes/templates and run
install/updateVersion.sh
# Mixer
apiVersion: v1
kind: Service
metadata:
  name: istio-mixer
  labels:
    istio: mixer
spec:
  ports:
  - name: tcp
    port: 9091
  - name: configapi
    port: 9094
  - name: prometheus
    port: 42422
  selector:
    istio: mixer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-mixer
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: ignore
      labels:
        istio: mixer
    spec:
      containers:
      - name: mixer
        image: docker.io/istio/mixer:0.1.6
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        - containerPort: 9094
        - containerPort: 42422
        args:
          - --configStoreURL=fs:///etc/opt/mixer/configroot
          - --logtostderr
          - -v
          - "3"
---
# Pilot service for discovery
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
data:
  mesh: |-
    # Uncomment the following line to enable mutual TLS between proxies
    # authPolicy: MUTUAL_TLS
    mixerAddress: istio-mixer:9091
    discoveryAddress: istio-pilot:8080
    ingressService: istio-ingress
    zipkinAddress: zipkin:9411
---
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  labels:
    istio: pilot
spec:
  ports:
  - port: 8080
    name: http-discovery
  - port: 8081
    name: http-apiserver
  selector:
    istio: pilot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-pilot-service-account
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-pilot
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: ignore
      labels:
        istio: pilot
    spec:
      serviceAccountName: istio-pilot-service-account
      containers:
      - name: discovery
        image: docker.io/istio/pilot:0.1.6
        imagePullPolicy: Always
        args: ["discovery", "-v", "2"]
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      - name: apiserver
        image: docker.io/istio/pilot:0.1.6
        imagePullPolicy: Always
        args: ["apiserver", "-v", "2"]
        ports:
        - containerPort: 8081
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
---
################################
# Istio ingress controller
################################
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  labels:
    istio: ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
#   nodePort: 32000
    name: http
  - port: 443
    name: https
  selector:
    istio: ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress-service-account
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-ingress
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: ignore
      labels:
        istio: ingress
    spec:
      serviceAccountName: istio-ingress-service-account
      containers:
      - name: istio-ingress
        image: docker.io/istio/proxy_debug:0.1.6
        args: ["proxy", "ingress", "-v", "2"]
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
---

################################
# Istio egress envoy
################################
apiVersion: v1
kind: Service
metadata:
  name: istio-egress
spec:
  ports:
  - port: 80
  selector:
    istio: egress
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-egress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        istio: egress
    spec:
      containers:
      - name: proxy
        image: docker.io/istio/proxy_debug:0.1.6
        imagePullPolicy: Always
        args: ["proxy", "egress", "-v", "2"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
---



thanks in advance!



2017-06-30 13:17 GMT-04:00 Frank Budinsky <notifications@github.com>:

**Comment by frankbu** [comment]
Looks like you are using the latest istio stable version on a recent minikube, which does work for others, so I don't have any other ideas what might be wrong. Maybe you want to try to debug using the instructions in the link I provided earlier or if you give up you could try to run it on a bluemix free kubernetes cluster instead.

**Comment by ahsimon** [comment]
Ok,

We really know is about our minikube env, so we starting to move a real
cloud provider,

Thanks you so much for time.


2017-07-05 13:06 GMT-04:00 Frank Budinsky <notifications@github.com>:

**Comment by ldemailly** [comment]
closing this for now then - thanks!
