### ISSUE TITLE
Pod status stuck at ContainerCreating

### ISSUE THREAD

**Issue by yns01** [istio/issues#41]
I am trying to setup istio with minikube following the guide [here](https://istio.io/docs/tasks/installing-istio.html).

After running `kubectl apply -f install/kubernetes/istio.yaml`, the pods are stuck in ContainerCreating state: 

`> ➜  istio-0.1.6 kubectl get pods`

NAME                                                   READY     STATUS     

- grafana-1395297218-36b3z              0/1           ContainerCreating  
- istio-egress-815883402-n7qm9       0/1            ContainerCreating 
- istio-ingress-1054723629-x4t9n      0/1            ContainerCreating  
- istio-mixer-2450814972-nzd0z         1/1            Running  
- istio-pilot-1836659236-cdcx4          0/2            ContainerCreating
- prometheus-3067433533-hv6jk       0/1            ContainerCreating 
- servicegraph-3127588006-r05m0    0/1            ContainerCreating  
- zipkin-4057566570-m0tkm               0/1            ContainerCreating

Looking at the events for one of the pods: 

`kubectl describe pod zipkin-4057566570-m0tkm`

  13m		13m		1	default-scheduler				Normal		Scheduled	Successfully assigned zipkin-4057566570-m0tkm to minikube
  13m		13m		1	kubelet, minikube	spec.containers{zipkin}	Normal		Pulling		pulling image "docker.io/openzipkin/zipkin:latest"

All the pods are stuck at this step... Any support would be really helpful

**Comment by raveen-sharma** [comment]
Hi yns01,
I am also facing same issue while installing istio on Kubernetes cluster. How did you managed to resolve this?

**Comment by xstof** [comment]
Same here...

**Comment by ldemailly** [comment]
what errors/what do you see in the logs? which version of istio (should be 0.2.12) etc... please open a new issue with details

**Comment by Dakuan** [comment]
on minikube this can be caused by not having access to docker-registry, this can fix: `eval $(minikube docker-env)`
