### ISSUE TITLE
istioctl unable to find configmap when deploying application

### ISSUE THREAD

**Issue by jpweber** [istio/issues#42]
Trying to deploy an application I get the following error

```
kubectl -n dev create -f <(istioctl -n dev kube-inject -f foo.yaml)
Error: Istio configuration not found. Verify istio configmap is installed in namespace "dev" with `kubectl get -n dev configmap istio`
error: no objects passed to create
```
I run the recommended command and it shows that the config map does exist
```
bash-3.2$ kubectl get -n dev configmap istio
NAME      DATA      AGE
istio     1         12m
```

I've tried removing and reinstalling istio, which had no effect. I have seen this on k8s 1.6.2 and 1.6.6

istioctl version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8
KubeInjectHub: docker.io/istio
KubeInjectTag: 0.1

apiserver version:

Version: 0.2.0-ac94a44
GitRevision: ac94a44
GitBranch: master
User: jenkins@ubuntu-16-04-build-12744189088e0f
GolangVersion: go1.8.1

**Comment by frankbu** [comment]
It looks like you are running istio out of the `master` branch (Version: 0.2.0-ac94a44), which is currently in a pretty broken state, as we are restructuring components. The latest stable version is in branch `release-0.1`.

**Comment by jpweber** [comment]
Thanks, I'll switch to the stable and give it a try today.

**Comment by jpweber** [comment]
Yup that was it thank. closing.
