### ISSUE TITLE
Servicegraph fails to render if service name contains dash/minus/"-"

### ISSUE THREAD

**Issue by l2fprod** [istio/issues#43]
I have two services named 'lw-erp' and 'lw-controller'.

When going to the servicegraph at http://localhost:8088/dotviz I get an empty page.

I looked at the source code for the page, the embedded digraph is:

```
digraph "istio-servicegraph" {
unknown -> lw-erp [label="qps: 0.000000, version: v1"];
unknown -> lw-controller [label="qps: 0.000000, version: v1"];
unknown [label="unknown"];
lw-erp [label="lw-erp"];
lw-controller [label="lw-controller"];
}
```

the Javascript console shows:

```
Uncaught Error: syntax error in line 3 near '-'
    at render (viz-lite.js:1072)
    at Viz (viz-lite.js:1058)
    at dotviz:25
```

I tested the digraph with http://www.webgraphviz.com/ and it reports:
```
Error: :2: syntax error near line 2 context: unknown -> >>> lw- <<< erp [label="qps: 0.000000, version: v1"]; 
```

If I change the digraph to:

```
digraph "istio-servicegraph" {
unknown -> "lw-erp" [label="qps: 0.000000, version: v1"];
unknown -> "lw-controller" [label="qps: 0.000000, version: v1"];
unknown [label="unknown"];
"lw-erp" [label="lw-erp"];
"lw-controller" [label="lw-controller"];
}
```
where I put the names in double quotes (https://stackoverflow.com/questions/14958346/dot-dash-in-name) then it works and I get the expected result:

![image](https://user-images.githubusercontent.com/12746550/27783190-84b688b4-5fd5-11e7-9ba3-5cc8f37332ae.png)

So it seems Istio servicegraph should put quotes around the node names to avoid errors.

**Comment by douglas-reid** [comment]
This should be a straightforward fix. I'll take the action to patch and push a new docker image.

**Comment by douglas-reid** [comment]
OK. I've pushed a new image up with the fix for double-quoting.

Can you try again with the new image ?

**Comment by ldemailly** [comment]
please reopen if you are still encountering the same issue with the new image
