### ISSUE TITLE
istioctl version command fails with Bluemix Container Service on Kubernetes.

### ISSUE THREAD

**Issue by cvishal** [istio/issues#44]
$ istioctl version
istioctl version:
Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8
KubeInjectHub: docker.io/istio
KubeInjectTag: 0.1
apiserver version:
Error: an error on the server ("Error: 'dial tcp 172.30.206.203:8081: getsockopt: connection timed out'\nTrying to reach: 'http://172.30.206.203:8081/v1alpha1/version'") has prevented the request from succeeding

**Comment by frankbu** [comment]
Are you seeing this on a free or paid k8s cluster? Can you reproduce this problem, starting from scratch? Please provide instructions to reproduce.

**Comment by tjquinno** [comment]
FWIW we are seeing the same symptom in a different environment. My colleague has described our experience and how to reproduce it here: https://groups.google.com/d/topic/istio-users/pN883wGgPfM/discussion

**Comment by cvishal** [comment]
Hi Frank
I am using free cluster with Bluemix. I was following the istio documents mentioned in https://istio.io/docs/tasks/installing-istio.html. I created cluster, and exported KUBECONFIG env variable. Then I was able to install istio, bookinfo application and everything worked fine, until I started looking  into route-rule commands, which failed with above error. Then I tested 'istioctl version' which also failed same way.
Hope this helps.
Vishal

**Comment by aedocw** [comment]
I am hitting this issue as well, on a paid Bluemix cluster.  Everything works until I get to:
$ istioctl create -f samples/apps/bookinfo/route-rule-all-v1.yaml
Error: an error on the server ("Error: 'dial tcp 172.30.73.215:8081: getsockopt: connection timed out'\nTrying to reach: 'http://172.30.73.215:8081/v1alpha1/config/route-rule/default/productpage-default'") has prevented the request from succeeding

This works locally using minikube.

**Comment by ayj** [comment]
@cvishal, @aedocw, can you try the debug steps described [here](https://groups.google.com/d/msg/istio-users/pN883wGgPfM/s_ro12F9BgAJ)?

**Comment by aedocw** [comment]
@ayj thanks for those steps! Seems to confirm what is noted in the thread, that it's an issue with the k8s proxy.  This worked for me:

Window #1:
$ podname=$(kubectl get pod -l istio=pilot -o=jsonpath={'.items[0].metadata.name'})
$ kubectl port-forward ${podname} 8081

Window #2:
$ istioctl --kube=false create --configAPIService=localhost:8081/v1alpha1 -f istio/samples/apps/bookinfo/route-rule-all-v1.yaml 
Created config: route-rule productpage-default
Created config: route-rule reviews-default
Created config: route-rule ratings-default
Created config: route-rule details-default

**Comment by tjquinno** [comment]
We got similar advice in the Google group for istio, and that worked for us as well. That confirmed what @aedocw said that something with the k8s proxy was the problem.

We subsequently discovered that flannel was having problems communicating from the master to the slave node. After some suitable restarts (I was not directly involved so I don't know exactly what got restarted) `istioctl version` worked as expected for us.

**Comment by dcberg** [comment]
This was caused due to a kube-proxy config issue on a small number of clusters. Your cluster unfortunately was affected. The problem has been corrected and deployed. This issue can be closed.

**Comment by rshriram** [comment]
@cvishal ^^^

**Comment by cvishal** [comment]
Yes. Its working. Thanks
