### ISSUE TITLE
wishlist: add istioctl --context flag

### ISSUE THREAD

**Issue by chrishiestand** [istio/issues#49]
Personally, I consider the implicit `kubectl` context an anti-pattern. When managing multiple kubernetes clusters it may be easy to execute a dangerous command in production (e.g. when you meant to run it in a test environment). So I always use `kubectl --context` (via shell aliases or functions) to be very explicit about which cluster I'm working with (and possibly user or namespace). I think it would be beneficial to do the same with `istioctl`. So please add a `--context` CLI option to help avoid accidents.

I'm pretty new to istio - please correct me if I've missed something. Thanks.

**Comment by ymesika** [comment]
Implemented in https://github.com/istio/istio/pull/6101

**Comment by chrishiestand** [comment]
Thank you @ymesika !
