### ISSUE TITLE
Installation doc fails to mention sourcing istio.VERSION

### ISSUE THREAD

**Issue by saturnism** [istio/issues#5]
https://istio.io/docs/tasks/installing-istio.html

This used to call out `source istio.VERSION` but that step is currently missing.  As of 0.1.3, that step seems to be required.

**Comment by andraxylia** [comment]
It's not mandatory, I just tried 0.1.3 with the embedded istioctl.

**Comment by saturnism** [comment]
I installed the istioctl through the curl url. But it did ask me fore it. I only knew I needed to source in the VERSION file because I've seen the previous doc.

Interestingly enough, when I check my istioctl version, it says it's 0.1.2... But the package was supposedly 0.1.3. Would that cause the issue?
```
istioctl version
Version: 0.1.2-6dbd19d
GitRevision: 6dbd19d
GitBranch: unknown
User: jenkins@ubuntu-16-04-build-b6e6ae752ccba
GolangVersion: go1.8
getting-started-java $ which istioctl
/Users/rayt/Applications/istio-0.1.3/bin/istioctl
```

**Comment by ldemailly** [comment]
can you try again with 0.1.4 ?
```
curl -L https://raw.githubusercontent.com/istio/istio/3b6a0660f4c697045b9123e073b364aba988bf61/downloadIstio.sh | sh -
```

**Comment by ldemailly** [comment]
0.1.4 is now in so try 
```
curl -L https://git.io/getIstio | sh -
```
and let me know if you still have the issue

**Comment by ldemailly** [comment]
side note https://istio.io/docs/samples/bookinfo.html#start-the-application
does still mention to `source istio.VERSION` so we should remove it there too if that's not needed anymore

**Comment by andraxylia** [comment]
This step is no longer needed as of 0.1.4.

**Comment by ldemailly** [comment]
fixed
