### ISSUE TITLE
Error installing: unable to decode "install/kubernetes/istio-rbac-beta.yaml"

### ISSUE THREAD

**Issue by rvennam** [istio/issues#54]
I'm seeing error messages while trying to install Istio on minikube. I'm following [these](https://istio.io/docs/tasks/installing-istio.html) steps. 

```
~/istio-0.1.6$ kubectl api-versions | grep rbac
rbac.authorization.k8s.io/v1alpha1
rbac.authorization.k8s.io/v1beta1
```
```
~/istio-0.1.6$ kubectl apply -f install/kubernetes/istio-rbac-beta.yaml
unable to decode "install/kubernetes/istio-rbac-beta.yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "install/kubernetes/istio-rbac-beta.yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "install/kubernetes/istio-rbac-beta.yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "install/kubernetes/istio-rbac-beta.yaml": no kind "RoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "install/kubernetes/istio-rbac-beta.yaml": no kind "RoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "install/kubernetes/istio-rbac-beta.yaml": no kind "RoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "install/kubernetes/istio-rbac-beta.yaml": no kind "RoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
```

I'm able to get around this by installing the alpha instead.

**Comment by sdake** [comment]
@rvennam I'm not sure what version of Kubernetes you have, however, ClusterRole and RoleBinding alpha objects were renamed to something else recently (I think in Kubernetes 1.7.2 but may be earlier) and master of istio has followed suit.  Recommend updating to at least Kubernetes 1.7.3 (I use 1.7.5 on bare metal with kubeadm and don't have these errors).  As the objects were renamed, the rbac-beta.yaml won't work properly on older versions of Kubernetes.  Alternately if you are not using master, and using the "GetIstio.sh" script as your issue describes - that will download 0.1.6 (Which is incompatible with 1.7.3+) and your Kubernetes may be too new to work with the tarball that that getIstio.sh produces.

**Comment by ldemailly** [comment]
Please update or provide the version of your kubernetes cluster, it seems you maybe have something older than 1.5 ?

I just tried 0.1.6 against the current kubernetes 1.7.5 and it can apply rbac fine
```
istio-0.1.6 $ kubectl apply -f install/kubernetes/istio-rbac-beta.yaml 
clusterrole "istio-pilot" configured
clusterrole "istio-ca" configured
clusterrole "istio-sidecar" configured
rolebinding "istio-pilot-admin-role-binding" created
rolebinding "istio-ca-role-binding" created
rolebinding "istio-ingress-admin-role-binding" created
rolebinding "istio-sidecar-role-binding" created
istio-0.1.6 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rvennam** [comment]
> Kernel Version:
> 4.9.13
> OS Image:
> Buildroot 2017.02
> Container Runtime Version:
> docker://1.11.1
> Kubelet Version:
> v1.7.0
> Kube-Proxy Version:
> v1.7.0
> Operating system:
> linux
> Architecture:
> amd64

**Comment by sdake** [comment]
@rvennam I'm certain the interfaces have changed between 1.7.0 and 1.7.3 within Kubernetes related to the beta of rbac ClusterRole and RoleBinding.  .  Would you mind trying a newer version of Kubernetes?  I had the same problem and found a merge into istio which moved the beta of the rbac templates to a different name.

Regards
-steve

**Comment by ldemailly** [comment]
as I mentionned above the released, unmodified, 0.1.6 rbac file works fine with the current kubernetes cluster

**Comment by sdake** [comment]
@ldemailly I am possibly wrong (memory fuzzy), but I recall with commit a2049c9ff0f0cd505d6719cabdcc6332ed578157, beta rbac with Kubernetes 1.7.2 no longer functioned.  rbac started working again after 1.7.3.  I was doing many things though, and I have a lot of extra stuff in my repo sorting out PRs, so my work may have been the cause (but same symptoms and a revert of that patch got rbac working IIRC).  I no longer have the 1.7.2 RPMs to verify.

Regards
-steve

**Comment by ldemailly** [comment]
possibly, but istio-0.1.6 and istio-0.2.x both work k8s >= 1.7.3

**Comment by sdake** [comment]
agree, that has been my experience.

**Comment by rvennam** [comment]
I resolved my issues by updating kubectl
