### ISSUE TITLE
Istio upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by Abdul-Rehman-yousaf** [istio/issues#55]
I have setup k8s cluster on GKE and try to install istio, for that I have installed it and apply `istio-rbac-beta`, `istio.yaml` and `istio-auth.yaml`, after that I have applied `bookinfo.yaml` and when I try to access productpage it returns `upstream connect error `, 

what's wrong I have configured here?
Help  me, please!

**Comment by sdake** [comment]
@Abdul-Rehman-yousaf istio.yaml and istio-auth.yaml are exclusive.  You can either deploy without auth (istio.yaml) or with auth (istio-auth.yaml) both not _both_ at the same time.  I don't know if that is causing your specific problem (I have the same upstream connection error with just istio.yaml) - see istio/issues#53, however, your deployment of both won't help matters.  I'd also recommend using httpbin as a getting started sample to validate your environment as bookinfo.yaml is fairly complicated.

**Comment by ldemailly** [comment]
Thanks for trying istio, I'm closing this now but if you still have issues, please open a new issue answering all the questions in the template
