### ISSUE TITLE
Port Istio to CentOS

### ISSUE THREAD

**Issue by sdake** [istio/issues#56]
This is a continuation of issue istio/istio#653.

@ldemailly sure I can include how I built from source.  Note I did not rebuild the containers themselves - I sadly haven't determined how to use bazel to build the containers.  (Any tips here on the magic incantation?).  I am using the container versions in the install defaults from gcr.io for the above git revision in the manifests as they ship (without running the update script).  I left out the kube-inject step, however, I did do that work.  I'll try e2e tests with pilot (any tips on how to run them).  Still learning the code base and toolchain (i.e. istio noob:)

I noticed something odd when filing the bug last night - 192.168.0.0/16 was used as the pod cidr even though kubeadm was specified as 10.1.0.0/16.  May be a calico specific thing - although I believe I had calico running in the 10.1.0.0/16 pod cidr.

Another question for you beyond how to bazel build the containers - which CNI is used in the prow check testing?  I can't find documentation on this.  I can submit a PR for building on CentOS if desirable.  All the docs are built around Ubuntu and I'm not convinced the syscall/RTNETLINK interface is consistent in containers between Xenial and the CentOS 7.3 kernel (i.e. I would like to build my own containers for CentOS).

Note there will be a 1+ week lag as I am traveling Saturday until the 18th.

**Comment by sdake** [comment]
@ldemailly asked for build instructions for CentOS.  I'll submit these as a PR to the documentation once my CLA is sorted out and I've validated the instructions.  There is probably an easier way.  If anyone has optimizations - please add them in the comments and I will modify them in this issue and the PR.

(Work in progress - needs fresh install validation)
This should work on a Centos 7.3 minimal install with a full yum upgrade - Traveling until September 18th - will validate instructions on a fresh install post travel.

Building Istio from source on CentOS:
1. WARNING: Disable security features of CentOS to remove build hassles
   1. sudo setenforce 0
   1. sudo sed -i 's/enforcing/permissive/g' /etc/selinux/config
   1. sudo systemctl stop firewalld
   1. sudo systemctl disable firewalld
1. Install development toolthain
   1. sudo yum groupinstall "Development Tools"
   1. sudo yum groupinstall "Development Libraries"
1. Install go 1.8.3 RPMs from [Koji - CentOS Build System](https://cbs.centos.org/koji/buildinfo?buildID=17500)
1. Install bazel dependencies:
   1. sudo yum install java-1.8.0-openjdk java-1.8.0-openjdk-devel zlib-devel which findutils tar gzip zip unzip centos-release-scl-rh devtoolset-4-gcc devtoolset-4-gcc-c++
1. Build Bazel: (I'll provide an RPM when I return from travel post September 18th in Fedora's build system.)
   1. mkdir bazel
   1. cd bazel   
   1. curl -L https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel-0.5.4-dist.zip -o bazel-0.5.4-dist.zip
   1. unzip bazel-0.5.4-dist.zip
   1. scl enable devtoolset-4 bash
       1. note this pulls in the GCC 5.y.z toolchain needed for envoy as well as a bunch of magic to build java based tools like Bazel properly
   1. ./compile.sh
   1. If everything worked properly, you should see: Build successful! Binary is here: /home/sdake/bb2/output/bazel
   1. sudo cp /home/sdake/bb2/output/bazel /usr/bin/bazel

@ldemailly this was working on whatever I managed to check out priorerror:

1. Obtain some Istio repositories (WARNING this is incomplete at this time - this just shows how to obtain a built copy of istioctl for master using CentOS toolchain and libraries:
   1. export GOPATH=$HOME
   1. cd ~/
   1. git clone http://github.com/istio/pilot
   1. go get ./...
   1. cd ~/src/github.com/pilot
   1. bazel build //...
   1. this should build a copy of istioctl (and was on September 6th, but rerunning just this section of instructions results in below error.  May be an upstream defect or user error on my part.

```
WARNING: /home/sdake/.cache/bazel/_bazel_sdake/1ccc535e3724eec3dc7c2e6e638ebb3e/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:196:9: pkg_tar: renaming non-dict `files` attribute to `srcs`.
INFO: Found 64 targets...
ERROR: missing input file '//platform/kube:config'.
ERROR: /home/sdake/pilot/platform/kube/BUILD:34:1: //platform/kube:kubeconfig: missing input file '//platform/kube:config'.
ERROR: /home/sdake/pilot/platform/kube/BUILD:34:1 1 input file(s) do not exist.
INFO: Elapsed time: 34.342s, Critical Path: 0.05s
```
Possible user error - new to some of these toolchains.

**Comment by ldemailly** [comment]
quick note: we use the default that come with minikube, ibm bluemix, google gke and they all work.

for bazel I would just install the package (0.5.3) rather than build from source

do "make" in pilot instead of bazel directly (basically you are missing a symlink to kube/platform/config to your ~/.kube/config and some other setup make will take care of for you

**Comment by sdake** [comment]
@ldemailly I think I tried installing the bazel package (0.5.4) however it was built on Ubuntu (I think) and doesn't work on CentOS - hence the need to build from source.  I'll rebuild 0.5.3 since it seems like that is the recommended dependency.  I had picked up on 0.5.4 from some of the WORKSPACE requirements IIRC.

I was using make prior when I built istio, however, a new linter dep was introduced recently and I don't have it on my system.  I thought I'd just use bazel directly for documenting how to build from source as I've got to pack for travel tomorrow :).  Thanks for the tip about the symlinking - I'll sort out how to get the linter installed.

Thanks for the information about CNI - I'll find out with minikube uses and attempt using that CNI and see if that resolves the problem.

Cheers
-steve

**Comment by ldemailly** [comment]
`make setup` updates (or should update) all dependencies
worse case first do bazel clean and maybe also rm -rf vendor

safe travels ! when you come back I'm sure it'll be a lot easier to build/test

**Comment by sdake** [comment]
@ldemailly what was going wrong during the build is that on a fresh environment, I didn't have a copy of Kubernetes running nor had I copied the kubeconfig file into the new node.  Since there  was no kubernetes config file, the pilot build fails in mysterious ways.

At least we have the CentOS build documented now (in this issue).  I hope to be able to get a functional httpbin & bookinfo working soon.

Thank you for the wish of safe travel.

Out of curiosity, how are the containers built separately?  This is my first exposure to bazel, and while I see there are container bazel build scripts, I don't really understand what they do.

'm really keen to build my own containers outside of the CI system after I get bookinfo working.

Regards
-steve

**Comment by ldemailly** [comment]
you can build docker images directly after you produce the binaries, we do that in some repos
for instance: https://github.com/istio/pilot/blob/master/bin/push-docker

**Comment by sdake** [comment]
@ldemailly I've got httpbin and productpage samples functional.  I had to build centos binaries and get them in containers as some things between ubuntu and centos are not compatible at the kernel interface layer.  Prior I had 503 errors consistently and grafana was not reporting stats.  Now those problems are solved.  I am still using the CNI calico and that seems to work fine in this model.

I will submit some patches to add CentOS support to the automated building once I determine how to get ld.gold to build the proper static binaries.  I think the Ubuntu container images as well as the scratch images can still be used as base images as the Istio binaries are statically linked and then just copied into the container.  What is required of the prow infrastructure is to build the images against a CentOS system (to pull in libc, /usr/include, and all of the other kernel dependency interfaces such as rtnetlink, proc, ioctl, etc).  Unfortunately experience with docker has been consistent in this area - containers must be built for the target OS they are intended to run on.

I am jammed up with our CLA.  I know CLA is not your area - however if there is any suggestion you have to fix that, please shoot me a mail privately.

Thanks!
-steve

**Comment by sdake** [comment]
closing as the current dev model works well enough.
