### ISSUE TITLE
istio 0.2 initializer installation fails

### ISSUE THREAD

**Issue by saturnism** [istio/issues#64]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): YES

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.2.4
GitRevision: 9c7c291eab0a522f8033decd0f5b031f5ed0e126
GitBranch: master
User: root@822a7ac3ca86
GolangVersion: go1.8.3

kubectl version

saturnism@cs-6000-devshell-vm-3e3e92c9-4fe3-4c99-9bfa-6593223eb12f-3e:~/istio$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", 
Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", 
Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?** No

**What happened**:
```
kubectl apply -f install/kubernetes/istio-initializer.yaml
configmap "istio-inject" configured
serviceaccount "istio-initializer-service-account" configured
Error from server (Invalid): error when applying patch:
{"metadata":{"initializers":{"pending":[]}}}
to:
&{0xc4205c8840 0xc4201583f0 istio-system istio-initializer install/kubernetes/istio-initializer.yaml 0xc420ca6778 0xc420ca6a70 2149 false}
for: "install/kubernetes/istio-initializer.yaml": Deployment.apps "istio-initializer" is invalid: metadata.initializers: Invalid value: "null": field is immutable once initialization has completed
error validating "install/kubernetes/istio-initializer.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --val
idate=false
```

**What you expected to happen:**
Initializer should be installed w/o issues.

**How to reproduce it:**
Follow Istio installation instruction to create a GKE cluster, and then install initializer. However, initializer requires alpha feature. There is no instruction on how to do that.

**Feature Request:**
N

**Describe the feature:**
N/A

**Comment by saturnism** [comment]
in the cluster creation command, show the command line to enable alpha features in case someone wishes to test it.

**Comment by ldemailly** [comment]
for reference the instructions are on https://istio.io/docs/setup/kubernetes/automatic-sidecar-inject.html

**Comment by njoyce** [comment]
The above link is a 404, I think https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection is what you're looking for.

**Comment by ldemailly** [comment]
yes sorry, we kept changing the layout until recently
