### ISSUE TITLE
bookinfo guide doesn't show automatic sidecar injection command

### ISSUE THREAD

**Issue by saturnism** [istio/issues#66]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**

GKE 1.7.5, Istio 0.2.4

**Is Istio Auth enabled or not ?** No

**What happened**:
https://istio.io/docs/guides/bookinfo.html uses `istioctl inject` for proxy injection. should add instructions for those using kubernetes initializer.

**Comment by frankbu** [comment]
This is covered by https://github.com/istio/istio.github.io/pull/511
