### ISSUE TITLE
Doc: Circuit breaker doc/task is missing

### ISSUE THREAD

**Issue by saturnism** [istio/issues#69]
**Is this a BUG or FEATURE REQUEST?:** Bug

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl 0.2.4
kubectl 1.7.5
```

**Is Istio Auth enabled or not ?** No

**What happened**: Circuit breaker task/guide is missing. This was in 0.1.

**Comment by frankbu** [comment]
We have never had a circuit breaker task in 0.1: https://istio.io/v-0.1/docs/tasks/
It would be a nice feature request to add one.

**Comment by sakshigoel12** [comment]
https://istio.io/docs/tasks/traffic-management/circuit-breaking.html
