### ISSUE TITLE
Doc: `Enabling Simple Access Control` has incorrect YAML and command

### ISSUE THREAD

**Issue by lgfa29** [istio/issues#76]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
$ istioctl version
Version: 0.2.4
GitRevision: 9c7c291eab0a522f8033decd0f5b031f5ed0e126
GitBranch: master
User: root@822a7ac3ca86
GolangVersion: go1.8.3

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d
97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d
97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?** Yes

**What happened**:
In the [Access control using denials](https://istio.io/docs/tasks/security/basic-access-control.html#access-control-using-denials) section the YAML file includes an extra document in the end (`---`) that generates an error when running `istioctl`:

```
$ istioctl create -f mixer-rule-ratings-denial.yaml
Created config denier/default/handler at revision 18061
Created config checknothing/default/denyrequest at revision 18062
Error: 1 error occurred:
* kind  is not known
```

The command is also wrong because it has an extra `istioctl` after `-f`:

```
istioctl create -f ~istioctl~ mixer-rule-ratings-denial.yaml
```

**Comment by mandarjog** [comment]
Thanks Luiz for the issue.
I have fixed the doc issue and added an issue for istioctl.

**Comment by ZackButcher** [comment]
@mandarjog can we close this one since https://github.com/istio/pilot/issues/1351 was fixed as well?

**Comment by mandarjog** [comment]
Done.
