### ISSUE TITLE
Trouble configuring secure ingress

### ISSUE THREAD

**Issue by bismarck** [istio/issues#77]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.2.4
GitRevision: 9c7c291eab0a522f8033decd0f5b031f5ed0e126
GitBranch: master
User: root@822a7ac3ca86
GolangVersion: go1.8.3
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
Yes.
**What happened**:
I was following https://istio.io/docs/tasks/traffic-management/ingress.html#configuring-secure-ingress-https but I am unable to create a secure ingress.  I don't have a ingress controller running in my cluster so I was trying to access the service via nodeport

```
curl -k https://$SECURE_INGRESS_URL/ip
curl: (7) Failed to connect to 10.71.22.68 port 30695: Connection refused
```

I'm also seeing the following in my istio-ingress pod logs when I create the actual ingress object:
```

[2017-09-25 21:15:28.691][29][warning][upstream] external/envoy/source/server/lds_subscription.cc:65] lds: fetch failure: Failed to load certificate '/etc/istio/ingress-certs/tls.crt'
[2017-09-25 21:15:29.787][29][warning][upstream] external/envoy/source/server/lds_subscription.cc:65] lds: fetch failure: Failed to load certificate '/etc/istio/ingress-certs/tls.crt'
[2017-09-25 21:15:31.719][29][warning][upstream] external/envoy/source/server/lds_subscription.cc:65] lds: fetch failure: Failed to load certificate '/etc/istio/ingress-certs/tls.crt'
```

**What you expected to happen:**
As the docs indicate, I should see output like the following
```
curl -k https://$SECURE_INGRESS_URL/ip
{
  "origin": "129.42.161.35"
}
```

**How to reproduce it:**
Follow the steps indicated in the docs and try to access the secured ingress via node port.

**Comment by rhodgin** [comment]
I also ran into this issue but in my case I had an ingress control. The configuration of secure ingress looked good but requests to https://$SECURE_INGRESS_URL/ip would just time out.

**Comment by linsun** [comment]
i also hit the same.  I believe Saurabh too yesterday.  @andraxylia also indicated: https on port 443 works, it’s verified by pilot e2e tests, but it is not auth/mtls. One needs to send “-key Host -val ” + host”, but afaik they are not verified @isaiah

**Comment by ijsnellf** [comment]
@bismarck: What environment are you in? GCP, IBM cloud or Minikube?

**Comment by bismarck** [comment]
@ijsnellf I'm on AWS.  Cluster built with KOPS and using weave.

**Comment by linsun** [comment]
I did some digging on this for bluemix.  For istio-ingress with service type load balancer, we don't support SSL termination (envoy doesn't support SSL termination per my understanding), which means https://{gateway-ip}/productpage won't work as the bookinfo product page doesn't support ssl termination.

For bluemix container service, we have our own ingress, and I was able to reach bookinfo via https via our own ingress then istio ingress.

**Comment by ijsnellf** [comment]
@bismarck: it looks like our docs were out of date for ingress. @kyessenov updated them here https://github.com/istio/istio.github.io/pull/554. Following the updated docs should fix your issue. Let us know if that works.

**Comment by bismarck** [comment]
@ijsnellf :thumbsup: That fixed my issue.

**Comment by ldemailly** [comment]
awesome, thanks for verifying ! closing this then
