### ISSUE TITLE
cleanup.sh refers to `route-rule`

### ISSUE THREAD

**Issue by sublimino** [istio/issues#78]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):
Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl 0.2.4
kubectl 1.7.5
```

**Is Istio Auth enabled or not ?**
istio-auth.yaml applied

**What happened**:
Running cleanup.sh results in 

```
namespace ? [default]  
using NAMESPACE=default
...
Error: "route-rules" not recognized. Please use non-hyphenated resource name "routerules"  
```

**What you expected to happen:**
Route rules deleted. Fixes required in https://github.com/istio/istio/blob/master/samples/bookinfo/kube/cleanup.sh#L31-L32 

**How to reproduce it:**
`samples/bookinfo/kube/cleanup.sh`

**Feature Request:**
N

**Describe the feature:**

**Comment by ZackButcher** [comment]
And that's why I should read the full issue and not just the first post...thanks for writing the fix!

**Comment by ldemailly** [comment]
thanks for the fix !
