### ISSUE TITLE
Ingress host header doesn't represent the actual host name / IP

### ISSUE THREAD

**Issue by saturnism** [istio/issues#8]
It seems like requests through the ingress proxy will automatically be enriched w/ host header.
However, the header seem to indicate the internal host name, rather than the Ingress IP / hostname that the browser actually used to connect.

In this case, I entered through an Ingress IP, but the header to the service was "helloworld-ui-service.default.svc.cluster.local:80", this caused my Java application (Spring Boot) to think that "helloworld-ui-service.default.svc.cluster.local" is the domain name it should redirect the users to.

```
 [2017-05-22T02:59:50.385Z] "GET / HTTP/1.1" 200 - 0 3126 603 598 "77.60.103.234" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "93b734a6-1a38-9403-95d9-f3158a4e3532" "helloworld-ui-service.default.svc.cluster.local:80" "127.0.0.1:8080"
```

**Comment by ldemailly** [comment]
Which client is not providing Host: header ? it's mandatory since HTTP/1.1 afaik

This being said I guess we should pick up an external/default server name from somewhere

**Comment by kyessenov** [comment]
Yes, we're going to relax the host requirement on in the incoming traffic to sidecars. It's validating the host name matches the service, which is not always true or desired.

**Comment by saturnism** [comment]
I'm pretty sure the headers were sent in from the browser, but the proxy may have overwritten it.

**Comment by saturnism** [comment]
So the request header from the browser is like this:
```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
DNT:1
Host:aaa.bbb.ccc.ddd
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Name
```

On Istio's envoy proxy for the service, I see:
[2017-05-26T08:24:52.247Z] "GET / HTTP/1.1" 200 - 0 3287 131 124 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "cf29a615-1405-97e6-a39c-6dcd5591be26" "helloworld-ui-service.default.svc.cluster.local:80" "127.0.0.1:8080"

**Comment by ldemailly** [comment]
@saturnism can you confirm the 0.1.6 release fixes your issue
https://github.com/istio/istio/releases/tag/0.1.6
or
`curl -L https://git.io/getIstio | sh -`

**Comment by duhuasong** [comment]
Error: failed to connect to Kubernetes API. kubernetes configuration file "/root/.kube/config" does not exist

**Comment by ldemailly** [comment]
Please use 0.2.12

And you need to point to a valid kubeconfig on windows (--kubeconfig path)

**Comment by duhuasong** [comment]
use  0.1.5 on cetnos7,i don't know how to make valid kubeconfig ?

**Comment by duhuasong** [comment]
use 0.1.5 on centos7,i don't know how to make valid kubeconfig ?

**Comment by ldemailly** [comment]
istio 0.1.5 ? I'm curious where did you get that release ?

**Comment by duhuasong** [comment]
the isoctl of newest release can not run on centos7，the error ：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x11f21d9]

goroutine 1 [running]:
main.getDefaultNamespace(0xc4202200e0, 0x12, 0x0, 0x0)
        cmd/istioctl/main.go:700 +0x99
main.glob..func4(0x1c32060, 0x1c5ebe8, 0x0, 0x0)
        cmd/istioctl/main.go:86 +0x39
github.com/spf13/cobra.(*Command).execute(0x1c32060, 0x1c5ebe8, 0x0, 0x0, 0x1c32060, 0x1c5ebe8)
        external/com_github_spf13_cobra/command.go:637 +0x549
github.com/spf13/cobra.(*Command).ExecuteC(0x1c319a0, 0x11f7c53, 0x0, 0x0)
        external/com_github_spf13_cobra/command.go:729 +0x339
github.com/spf13/cobra.(*Command).Execute(0x1c319a0, 0x0, 0x154)
        external/com_github_spf13_cobra/command.go:688 +0x2b
main.main()
        cmd/istioctl/main.go:531 +0xc0



could you   leave mailbox for my help ?thanks！

**Comment by ldemailly** [comment]
it does run if you have a working .kubeconfig
and/or you pass the -n default flag
