### ISSUE TITLE
All Bookinfo pods are in CrashLoopBackOff

### ISSUE THREAD

**Issue by my3sons** [istio/issues#84]
**Bug:**
Y

istioctl version:
Version: 0.2.6
GitRevision: 081ffece00c82cb9de33cd5617682999aee5298d
GitBranch: master
User: root@69916ebba0fc
GolangVersion: go1.8.3

kubectl version:
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not ?**
DISABLED

**What happened**:
I am attempting to run the Istio Bookinfo app and after running the following command:
`kubectl --namespace istio-system apply -f <(istioctl kube-inject -f samples/bookinfo/kube/bookinfo.yaml)`

I see that all the corresponding pods are in CrashLoopBackOff state:

NAME                              READY     STATUS             RESTARTS   AGE
details-v1-1832799045-6q0rk       1/2       CrashLoopBackOff   7          14m
grafana-3907236758-mrfld          1/1       Running            0          1h
istio-ca-2429693513-4xl0l         1/1       Running            0          16h
istio-egress-2117248550-69nsz     1/1       Running            0          16h
istio-ingress-95513216-2bkpx      1/1       Running            0          16h
istio-mixer-1022595437-hfsbd      2/2       Running            0          16h
istio-pilot-4166718918-gpld5      1/1       Running            0          16h
productpage-v1-3921420951-0q3zj   1/2       CrashLoopBackOff   7          13m
prometheus-4086688911-d9gds       1/1       Running            0          1h
ratings-v1-830437469-gjz4n        1/2       CrashLoopBackOff   7          14m
reviews-v1-704982164-4nbvb        1/2       CrashLoopBackOff   7          14m
reviews-v2-36871126-3qkx2         1/2       CrashLoopBackOff   7          14m
reviews-v3-162017856-8v41g        1/2       CrashLoopBackOff   7          13m
servicegraph-1321163238-z0crq     1/1       Running            0          1h
zipkin-3660596538-nn22s           1/1       Running            0          1h

Looking into the logs of the pods, I am seeing an error like the following in each of the Bookinfo pods:

`
Error from server (BadRequest): a container name must be specified for pod productpage-v1-3921420951-0q3zj, choose one of: [productpage istio-proxy] or one of the init containers: [istio-init enable-core-dump]
`
Below is the deployment yaml for the same pod:

root@carey-VirtualBox:/mnt/share/git/istio# kubectl --namespace istio-system get deployment productpage-v1 -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"sidecar.istio.io/status":"injected-version-root@69916ebba0fc-0.2.6-081ffece00c82cb9de33cd5617682999aee5298d"},"creationTimestamp":null,"name":"productpage-v1","namespace":"istio-system"},"spec":{"replicas":1,"strategy":{},"template":{"metadata":{"annotations":{"sidecar.istio.io/status":"injected-version-root@69916ebba0fc-0.2.6-081ffece00c82cb9de33cd5617682999aee5298d"},"creationTimestamp":null,"labels":{"app":"productpage","version":"v1"}},"spec":{"containers":[{"image":"istio/examples-bookinfo-productpage-v1:0.2.3","imagePullPolicy":"IfNotPresent","name":"productpage","ports":[{"containerPort":9080}],"resources":{}},{"args":["proxy","sidecar","-v","2","--configPath","/etc/istio/proxy","--binaryPath","/usr/local/bin/envoy","--serviceCluster","istio-proxy","--drainDuration","45s","--parentShutdownDuration","1m0s","--discoveryAddress","istio-pilot.istio-system:8080","--discoveryRefreshDelay","1s","--zipkinAddress","zipkin.istio-system:9411","--connectTimeout","10s","--statsdUdpAddress","istio-mixer.istio-system:9125","--proxyAdminPort","15000"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"INSTANCE_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"docker.io/istio/proxy_debug:0.2.6","imagePullPolicy":"IfNotPresent","name":"istio-proxy","resources":{},"securityContext":{"privileged":true,"readOnlyRootFilesystem":false,"runAsUser":1337},"volumeMounts":[{"mountPath":"/etc/istio/proxy","name":"istio-envoy"},{"mountPath":"/etc/certs/","name":"istio-certs","readOnly":true}]}],"initContainers":[{"args":["-p","15001","-u","1337"],"image":"docker.io/istio/proxy_init:0.2.6","imagePullPolicy":"IfNotPresent","name":"istio-init","resources":{},"securityContext":{"capabilities":{"add":["NET_ADMIN"]},"privileged":true}},{"args":["-c","sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t \u0026\u0026 ulimit -c unlimited"],"command":["/bin/sh"],"image":"alpine","imagePullPolicy":"IfNotPresent","name":"enable-core-dump","resources":{},"securityContext":{"privileged":true}}],"volumes":[{"emptyDir":{"medium":"Memory","sizeLimit":"0"},"name":"istio-envoy"},{"name":"istio-certs","secret":{"optional":true,"secretName":"istio.default"}}]}}},"status":{}}
    sidecar.istio.io/status: injected-version-root@69916ebba0fc-0.2.6-081ffece00c82cb9de33cd5617682999aee5298d
  creationTimestamp: 2017-09-30T13:19:14Z
  generation: 1
  labels:
    app: productpage
    version: v1
  name: productpage-v1
  namespace: istio-system
  resourceVersion: "99493"
  selfLink: /apis/extensions/v1beta1/namespaces/istio-system/deployments/productpage-v1
  uid: f4b17207-a5e1-11e7-881b-080027f9032b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"name":"istio-init","image":"docker.io/istio/proxy_init:0.2.6","args":["-p","15001","-u","1337"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{"add":["NET_ADMIN"]},"privileged":true}},{"name":"enable-core-dump","image":"alpine","command":["/bin/sh"],"args":["-c","sysctl
          -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t \u0026\u0026 ulimit
          -c unlimited"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
        pod.beta.kubernetes.io/init-containers: '[{"name":"istio-init","image":"docker.io/istio/proxy_init:0.2.6","args":["-p","15001","-u","1337"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{"add":["NET_ADMIN"]},"privileged":true}},{"name":"enable-core-dump","image":"alpine","command":["/bin/sh"],"args":["-c","sysctl
          -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t \u0026\u0026 ulimit
          -c unlimited"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
        sidecar.istio.io/status: injected-version-root@69916ebba0fc-0.2.6-081ffece00c82cb9de33cd5617682999aee5298d
      creationTimestamp: null
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - image: istio/examples-bookinfo-productpage-v1:0.2.3
        imagePullPolicy: IfNotPresent
        name: productpage
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - proxy
        - sidecar
        - -v
        - "2"
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - istio-proxy
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:8080
        - --discoveryRefreshDelay
        - 1s
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --connectTimeout
        - 10s
        - --statsdUdpAddress
        - istio-mixer.istio-system:9125
        - --proxyAdminPort
        - "15000"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: docker.io/istio/proxy_debug:0.2.6
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources: {}
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 1337
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        image: docker.io/istio/proxy_init:0.2.6
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - -c
        - sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t && ulimit -c
          unlimited
        command:
        - /bin/sh
        image: alpine
        imagePullPolicy: IfNotPresent
        name: enable-core-dump
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: "0"
        name: istio-envoy
      - name: istio-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio.default
status:
  conditions:
  - lastTransitionTime: 2017-09-30T13:19:15Z
    lastUpdateTime: 2017-09-30T13:19:15Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

**Comment by my3sons** [comment]
Looking into this a bit further, I am seeing the following error message in the istio-proxy log file for each of the Bookinfo related pods:

{
  "log": "E1002 12:55:45.243602       1 main.go:227] lookup failed for udp address: lookup istio-mixer.istio-system on 10.96.0.10:53: no such host\n",
  "stream": "stderr",
  "time": "2017-10-02T12:55:45.255823682Z"
}

**Comment by ldemailly** [comment]
Which kubernetes provider is this on ?

Looks like you may be having issue reaching via udp the statsd that runs along mixer,
try removing the `--statsdUdpAddress ...` from your deployment

cc @kyessenov

**Comment by linsun** [comment]
should we document this for 0.2?  By removing `--statsdUdpAddress ...`, what is the user impact?  Would mixer stop working?

**Comment by ldemailly** [comment]
Yes we should and no it has no effect on mixer, only the extra envoy stats

**Comment by wangkirin** [comment]
I tried the bookinfo with the same problem, could you provide more details about the  `--statsdUdpAddress` option?  how to config it ?   thx~~~

**Comment by ldemailly** [comment]
@wangkirin try `kubectl edit configmap -n istio-system istio` and comment out the
`      statsdUdpAddress: istio-mixer.istio-system:9125 ` line to `#      statsdUdpAddress: istio-mixer.istio-system:9125`

**Comment by chymy** [comment]
the three reviews pods fail (reviews-v1, reviews-v2, reviews-v3). 
They all crash for what appears to be the same error - the reviews container in the pod logs:

CWWKE0005E: The runtime environment could not be launched.
CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
com.ibm.ws.kernel.boot.LaunchException: Caught unexpected exception java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.rethrowException(KernelBootstrap.java:510)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:206)
        at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:245)
        at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:120)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:60)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:36)
Caused by: java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
        at com.ibm.ws.kernel.boot.internal.KernelUtils.cleanDirectory(KernelUtils.java:203)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.clearServerStateDir(KernelBootstrap.java:221)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:100)
        ... 4 more

Kubernetes Server version is 1.8.5
istio:0.4

Thanks!

**Comment by chymy** [comment]
Thanks! it does not work without istio！

**Comment by chymy** [comment]
server 
memory：  80G
disk: 4T

**Comment by ldemailly** [comment]
there must be something off in your setup, that's plenty of resources 
(how many cores?)

**Comment by chymy** [comment]
2 CPUs，32Cores.

**Comment by ldemailly** [comment]
k there must be something basic going on - check logs of your k8s components?
(or maybe it's an unstable version or...)

**Comment by chymy** [comment]
**tailf /var/log/messages**

k8s-master kube-apiserver: E0306 14:32:18.164383   25320 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *scheduling.PriorityClass: the server could not find the requested resource (get priorityclasses.scheduling.k8s.io)

Above log，is there anything to do with _bookinfo_？

**Comment by ldemailly** [comment]
not that I know, no
