### ISSUE TITLE
Don't know if  circuit breaker is working.

### ISSUE THREAD

**Issue by fleeto** [istio/issues#85]
**Is this a BUG or FEATURE REQUEST?:**
Bug
**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.2.6
kubectl version 1.7.6
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
istio.yaml

**What happened**:

The pod which is returning http 500 kept working on the requests.

**What you expected to happen:**

I think it should be wiped from the worker's list after it returned code 500 twice.

**How to reproduce it:**
All workloads running in the "default" namespace.

**default route rule**

~~~yaml
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: cb-default
spec:
  destination:
    name: svc-frontend
    labels:
      version: v1
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 2
      sleepWindow: 15m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
      httpMaxPendingRequests: 1
~~~

**Destination Policy**

~~~yaml
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: cb-default
spec:
  destination:
    name: svc-frontend
    labels:
      version: v1
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 2
      sleepWindow: 15m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
      httpMaxPendingRequests: 1
~~~

I'm using a StatefulSet as the service's backend.

The image of the StatefuleSet comes from php:apache, I'd put a php file in it:

~~~php
<?php
if (false===strpos(gethostname(), "-2")) {
  header('HTTP/1.1 500 Internal Server Error');
  return;
}
header("Content-type: text/plain");
echo "From: ".gethostname()."\n";
echo "Version: ".$_ENV['SERVICE_VERSION']."\n";
~~~

**Feature Request:**
Y/N

**Describe the feature:**

**Comment by rshriram** [comment]
Hi, I think I know what is happening. To confirm, can you run the same setup without a statefulset? i.e., as a normal service and see if the circuit breaker works?

**Comment by GregHanson** [comment]
@fleeto are you still seeing this in istio version 0.5.1 or later?

**Comment by GregHanson** [comment]
closing until issue can be reproduced in istio version 0.5.1 or later

**Comment by jeson114** [comment]
i can see this issue in 0.7.1
