### ISSUE TITLE
ingress works only if the service's port is named `http` 

### ISSUE THREAD

**Issue by tjquinno** [istio/issues#88]
**Is this a BUG or FEATURE REQUEST?:**
Y

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):
Yes - related to https://github.com/istio/issues/issues/83 which was closed by the author. 

Unless I missed a published restriction as to k8s service port naming having to be `http` for istio ingress to work, this is either a code bug or a doc bug.

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.2.4
GitRevision: 9c7c291eab0a522f8033decd0f5b031f5ed0e126
GitBranch: master
User: root@822a7ac3ca86
GolangVersion: go1.8.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4+coreos.0", GitCommit:"4bb697e04f7c356347aee6ffaa91640b428976d5", GitTreeState:"clean", BuildDate:"2017-08-22T08:43:47Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
No. Used istio.yaml to install.

**What happened**:
Ingress for a service does not work if the port is _not_ named `http` (is either named something else or is not named at all). The `curl` command accessing the ingress port returns a 404 and the ingress service's pod also logs a 404, the log message indicating that, seemingly, ingress was unable to map the path to a service name and port.

In a separate experiment a colleague had set up nginx for ingress and that worked regardless of the service's port naming.

**What you expected to happen:**
Ingress would work regardless of the name (if any) specified for the service's port.

**How to reproduce it:**
1. Temporarily edit the existing `samples/httpbin/httpbin.yaml` file to remove the port name 'http' or change it to something else. 
2. `kubectl apply -f samples/httpbin/httpbin.yaml`
3. Define ingress for `httpbin` as specified here: https://istio.io/docs/tasks/traffic-management/ingress.html#configuring-ingress-http
4. Try to access the service using the `/headers` or `/delay/3` (or any other matching path).

**Comment by cmeury** [comment]
FYI, I think the ingress adds the service clusterIP and port as the last segment when it *can* map it but the service returns an actual 404. See the difference at the end of the log lines and the respective returned headers in my case (with redacted host names):

## No mapping

HTTP request:

```
$ http https://example.com/m/headers
HTTP/1.1 404 Not Found
content-length: 0
date: Thu, 05 Oct 2017 06:12:33 GMT
server: envoy
```

Ingress log:

```
[2017-10-05T06:12:33.579Z] "GET /m/headers HTTP/1.1" 404 NR 0 0 0 - "91.1.2.3 10.4.3.0" "HTTPie/0.9.9" "1e5148f2-8261-9b4a-b58b-2fb1713dd845" "example.com" "-"
```

## Mapping

HTTP request:

```
$ http https://example.com/m/headers
HTTP/1.1 404 Not Found
content-length: 19
content-type: text/plain; charset=utf-8
date: Thu, 05 Oct 2017 06:13:10 GMT
server: envoy
x-content-type-options: nosniff
x-envoy-upstream-service-time: 24

404 page not found
```

Ingress log:

```
[2017-10-05T06:13:11.070Z] "GET /m/headers HTTP/1.1" 404 - 0 19 30 24 "91.1.2.3, 10.4.0.1" "HTTPie/0.9.9" "427f2205-79f0-97a8-bfb7-25f464601205" "example.com" "10.4.0.15:8080"
```

**Comment by tjquinno** [comment]
@cmeury Sorry, I'm not sure what your point was.

In this error case the ingress service is unable to map the request unless the port name is 'http'. You can see this by going through the steps to reproduce it and supplying the same valid path when trying to contact the service via the ingress service in both scenarios. If the target service's port is named 'http' then the `curl` returns the expected output. If the port is named otherwise you get 404 for the very same path.

I didn't include it before but here's an example from the ingress pod's log, which is one way my colleague and I initially realized that the mapping was not happening (as opposed to the message reaching the service and the service returning a 404):
```
[2017-10-04T20:29:35.779Z] "GET /echo/ HTTP/1.1" 404 NR 0 0 0 - "10.99.56.0" "curl/7.54.0" "4fd617ac-874b-97b0-83de-3ddea050fccf" "w.x.y.z:30281" "-"
```

**Comment by cmeury** [comment]
Forgot the most important point, my example was with a port named `http-something`, not purely `http`. But I am unsure what exactly my point was, so let's just pretend this never happened :)

**Comment by tjquinno** [comment]
Is this a bug?

Is this a documented restriction/requirement? If so, I'd welcome a pointer to the doc.

**Comment by ayj** [comment]
/cc @rshriram @kyessenov @andraxylia 

See https://istio.io/docs/setup/kubernetes/sidecar-injection.html#pod-spec-requirements for documentation on named ports for sidecars. Traffic to non-named ports (or those with `http` prefix) are treated as plain TCP traffic. 

This might have something to do with k8s ingress being L7 routing plain TCP traffic and sidecar not having proper config to handle it?

**Comment by tjquinno** [comment]
Thanks for the pointer. 

Through experimentation a while ago I found (and discussed in the istio Google group) that in 0.1.6 I had to use sidecar injection for ingress to work although people there said that should not be needed. 

I have found in 0.2.x that I don't need the sidecar injection for ingress to work. 

The page you referenced is all about sidecars. I was asking about ingress specifically. Are you suggesting that sidecar injection should be necessary for the istio ingress controller to work?

I'd suggest that the doc about ingress be explicit about any requirements or lack of requirements -- port naming, sidecar injected.

**Comment by cmeury** [comment]
As far as I understand the Istio Ingress is just another Envoy instance. So to be able to use ingress objects, the target service has to be running an istio-proxy as well.

**Comment by costinm** [comment]
@cmeury:  Istio ingress should be able to target any service, even without istio-proxy. 

However, if auth/mTLS is enabled, the target service must either have istio-proxy or implement an equivalent mTLS protocol, i.e. the port must use the certificates signed by istio-ca ( from the secrets). This is currently a bit hard to setup, so if mTLS is enabled it's highly recommended you use istio-proxy 
on every service.

**Comment by GregHanson** [comment]
@cmeury @tjquinno are you still having this problem in istio version 0.5.1 or later?

**Comment by ldemailly** [comment]
I guess we could document more prominently this limitation and possibly have other ways to discover a service is http but closing for now
