### ISSUE TITLE
Reduce pilot's RBAC permissions to the strictly needed ones

### ISSUE THREAD

**Issue by mdhume** [istio/issues#89]
**Is this a BUG or FEATURE REQUEST?:** Feature Request

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):
Yes (I asked on google groups - https://groups.google.com/forum/#!topic/istio-users/NrQ6iABjcqo  and they asked me to create an issue. It is related to https://github.com/istio/pilot/issues/1375)

**Bug:**
N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.2.6
kubectl version 1.7.7
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
Not enabled, used istio.yaml

**What happened**:
I wanted to restrict the RBAC permissions given to pilot by setting verbs to "get", "list", "watch" for "customresourcedefinitions" instead of "*" . Pilot failed to start with the error - I1005 20:40:51.945100 1 client.go:169] registering CRD "routerules.config.istio.io" Error: failed to register custom resources. User "system:serviceaccount:istio-system:istio-pilot-service-account" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope.

**What you expected to happen:**
Expected Pilot to start since CRDs are created at start time.

**How to reproduce it:**
Set RBAC permissions for "customresourcedefinitions" to "get", "list", "watch"

**Feature Request:**
Y

**Describe the feature:**

**Comment by andraxylia** [comment]
Pilot only needs to create CRDs, not all resources.
The issue is to separate the CRD from pods, svc, etc, and use explicit get, list, watch, create instead of *.

**Comment by andraxylia** [comment]
Triaged and moved to  istio/istio#1048.
