### ISSUE TITLE
Feature Request: Allow cluster-wide or namespace-wide intercepted egress ranges

### ISSUE THREAD

**Issue by saturnism** [istio/issues#9]
Currently, Istio intercepts all egress by default. There is away to specify which ranges to intercept using `--includeIPRanges` , see [doc](https://istio.io/docs/tasks/egress.html) but it's configured per deployment basis.

It would be useful to be able to specify the inclusion ranges, or exclusion ranges w/ a namespace default, or a cluster-wide default, rather than per-deployment basis.

**Comment by saturnism** [comment]
Duplicate of https://github.com/istio/manager/issues/515

**Comment by rshriram** [comment]
leaving this open for tracking

**Comment by ayj** [comment]
This should be fixed by https://github.com/istio/pilot/pull/1104. Its now possible to set the `includeIPRange` in the initialzier ConfigMap which applies to the entire cluster (or subset of namespaces in the cluster).
