### ISSUE TITLE
sample configurations in doc is incomplete

### ISSUE THREAD

**Issue by saturnism** [istio/issues#90]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
Version: 0.2.7
GitRevision: 6b145c189aad8306b13af1725123bebfbc7eefd4
GitBranch: master
User: root@f1eeb85f62ab
GolangVersion: go1.8

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.5-gke.1", GitCommit:"2aa350cad8d86efa8c94811b70bd67646daf5772", GitTreeState:"clean", BuildDate:"2017-09-27T17:38:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?** No

**What happened**:
Reading the [Routing Rules](https://istio.io/docs/reference/config/traffic-rules/routing-rules.html) doc. The sample route rule in the doc starts with:
```
metadata:
  name: my-rule
  namespace: default # optional (default is "default"
```

It should also include `apiVersion` and `kind`, e.g.:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  ...
```

[Egress Rule](https://istio.io/docs/reference/config/traffic-rules/egress-rules.html) and [Destination Policies](https://istio.io/docs/reference/config/traffic-rules/destination-policies.html) should also be updated w/ the proper `apiVersion` and `kind` in the sample snippets.

**Comment by linsun** [comment]
Thanks for reporting this, a PR is welcomed!
