### ISSUE TITLE
mixer status code is not linked to the reference doc

### ISSUE THREAD

**Issue by saturnism** [istio/issues#91]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Yes

**Bug:** Y

**What happened**:
In [Istio / Status RPC](https://istio.io/docs/reference/api/mixer/status.html#google.rpc.Status.details), in the field table, `google.rpc.Code` is not linked to the actual code. `google.rpc.Status.details` link does not work. 

**What you expected to happen:**
When referencing external values (such as gRPC codes), doc should be linked.

**How to reproduce it:**

**Feature Request:**
Y/N

**Describe the feature:**

**Comment by linsun** [comment]
Thanks for reporting this, a PR is welcomed!

**Comment by ayj** [comment]
Issue moved to [istio/istio.github.io #653](https://github.com/istio/istio.github.io/issues/653) via [**ZenHub**](https://www.zenhub.com/)
