### ISSUE TITLE
There shouldn't be "." inside the tar files of the release packages.

### ISSUE THREAD

**Issue by fleeto** [istio/issues#96]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
kubectl version
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....

**What happened**:

It will  change current folder's owner if current user has the permission.

**What you expected to happen:**

**How to reproduce it:**

~~~bash
mkdir abc
cd abc
tar -xvf ~/istio-0.2.7-linux.tar.gz`
ls -la ..
...

We will see:
...
drwxr-xr-x.  3 195408 5000      25 Oct  4 04:44 abc
...
~~~

**Feature Request:**
N

**Describe the feature:**

**Comment by costinm** [comment]
I can't reproduce it - and not sure how it could happen, tar will create a new directory but it is not supposed to change anything in the current directory. Can you double check and provide the permissions of the 
parent dir before/after ?

**Comment by costinm** [comment]
Laurent checked - and indeed there is a "." entry in the tar, it's a valid bug.

**Comment by costinm** [comment]
Issue moved to [istio/istio #1112](https://github.com/istio/istio/issues/1112) via [**ZenHub**](https://www.zenhub.com/)
