### ISSUE TITLE
The command "kubectl get quota" should return the list of quota object.

### ISSUE THREAD

**Issue by fleeto** [istio/issues#97]
**Is this a BUG or FEATURE REQUEST?:**

Bug

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.2.7
kubectl version: v1.7.6
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....

No

**What happened**:

After I created a quota object.

Run the command:  `kubectl get quota`.

It returned:

~~~
No resources found.
~~~

**What you expected to happen:**

There should be the list of quota objects

**How to reproduce it:**

kubectl apply -f quota.yaml

quota.yaml:

~~~yaml
apiVersion: config.istio.io/v1alpha2
kind: quota
metadata:
  name: requestcount
spec:
  dimensions:
    source: source.service | "unknown"
    destination:  destination.service | "unknown"
~~~

then run `kubectl get quota`

**Feature Request:**
N

**Describe the feature:**

**Comment by douglas-reid** [comment]
CRs require pluralization. Running `kubectl get quotas --all-namespaces` will retrieve this information.

**Comment by fleeto** [comment]
@douglas-reid You are right, I can list it with the command `kubectl get quotas`

**Comment by mandarjog** [comment]
@fleeto you should use plural normally,  Singulars works most of the times if the shortname is not claimed by another config object.

for example `kubectl get routerule` works just fine.

In your example the `v1/ResourceQuota` kind claims `quota` as a shortname, so it does not work.
