### ISSUE TITLE
Create a default set of prometheus alerts

### ISSUE THREAD

**Issue by nmnellis** [istio/issues#99]
**FEATURE REQUEST**
**Describe the feature:**

For users that have Prometheus installed, document a set of alerts that an istio user might find useful after istio is running. Some metrics may need to be created to effectively monitor istio.

A short list of nice to have monitors:
* High response times between two http services
* Number of 4xx or 5xx errors abnormally high
* Increase in response volume

There are more but this is a start

**Comment by douglas-reid** [comment]
@nmnellis Great idea! I think there is lots of ripe territory for improving the observability story here. Perhaps we should flesh out starting points in a document (for instance, should we also use Grafana alerting, etc.?), and then move that into actionable work items. Would you be interested in helping to start such a document (or help me in drafting one)?

**Comment by costinm** [comment]
Issue moved to [istio/mixer #1466](https://github.com/istio/mixer/issues/1466) via [**ZenHub**](https://www.zenhub.com/)
